### ISSUE TITLE
Deleting the folder with a custom gem and then creating new one with another name results in the project configuration fail

### ISSUE THREAD

**Issue by LB-BartoszCwiek** [o3de/o3de#10369]
**Describe the bug**
When a custom gem is created, after deleting the folder that contains it, creating a new one with another name results in the project configuration failure. Additionally, disabling a newly created gem via Project Manager and Configure Gems menu, still results in fail during project compilation. The same occurs when trying to build a newly created custom gem for the new project. For more detailed information, please refer to the attached log.

**Steps to reproduce**
1. Open CMD in the o3de directory.
2. Execute the following command: scripts\o3de create-gem --gem-name MyCppShapeExample --template-name CppToolGem --gem-path C:\o3de-gems\MyCppShapeExample to create a new Gem.
3. Open the Project Manager from the o3de directory.
4. Navigate to Configure Gems... page for the Project.
5. Search for the newly created Gem and enable it in the Project.
6. Press Save.
7. Rebuild the Project.
8. Delete the project folder with the newly created gem.
9. Repeat steps 1-7 and use another name for gem (e.g. scripts\o3de create-gem --gem-name MyCppShapeExample1 --template-name CppToolGem --gem-path C:\o3de-gems\MyCppShapeExample).

**Expected behavior**
The project is built successfully.

**Actual behavior**
The project configuration fails to compile.

**Screenshot**
![ProjectFail](https://user-images.githubusercontent.com/100559077/175954484-a4d02a93-c463-4f3e-a63d-9d8d57477187.png)

**Additional files**
[CMakeProjectBuildError.log](https://github.com/o3de/o3de/files/8992447/CMakeProjectBuildError.log)

**Found in Branch**
Development (25425ba)

**Desktop:**
- Device: PC
- OS: Windows
- Version: 10
- CPU: Intel Core i7-11700F
- GPU: NVIDIA GeForce RTX 3070

**Comment by lumberyard-employee-dm** [comment]
This is expected behavior.
The gem folder can't be deleted from the project without first disabling that gem from the project using the Project Manager or using the `scripts\o3de.bat disable-gem --gem-name MyCppShapeExample --project-path <project-path>` CLI command.

An enabled gem is enabled/disabled with a project via it's gem_name identifier.
Just deleting that folder doesn't disable the gem with project and it isn't the correct workflow to disabling a gem with a project
See https://www.o3de.org/docs/user-guide/project-config/add-remove-gems/#using-the-command-line-interface-cli
