### ISSUE TITLE
Recast Navigation: Some of colliders can fail to be calculated as obstacles after duplicating +10 PhysX Collider entities on a NavMesh

### ISSUE THREAD

**Issue by LB-MateuszSzweda** [o3de/o3de#10620]
**Describe the bug**
Duplicating a larger amount (+10) of entities based on **PhysX Collider** component on a NavMesh can lead to some of the new as well as old colliders failing to be calculated as obstacles for the navigating entities.

After duplication colliders look as if they are correctly registered on the Navmesh, however in game mode navigators can pass through them not registering them as obstacles.

Please note that simply deleting and duplicating a non registred collider again is sufficient to resolve the issue.

The issue has an inconsistent repro of 2/5 and more often affect the larger colliders.

For more information please refer to the attached video files.

**Prerequisites**

* **AutomatedTesting** project with **RecastNavigation** Gem was built and set as the active project.
* **Navtest3** level was unzipped and moved to the _o3de\AutomatedTesting\Levels_ directory

**Assets required**

[navtest3.zip](https://github.com/o3de/o3de/files/9092869/navtest3.zip)

**Steps to reproduce**

1. Launch the Editor and open the _navtest3_ level.
2. Move the _Navigator_ entity to the opposite end of the level.
3. Select +10 various _Obstacle_ entities and duplicate them.
4. Move the duplicated entities in front of the  _Navigator_ entity,
5. Enter the Game Mode.

**Expected behavior**
_Navigator_ entity correctly navigates through the level avoiding collision with  _Obstacle_ entities.

**Actual behavior**
_Navigator_ entity passes through some of _Obstacle_ entities.

**Screenshots/Video**

https://user-images.githubusercontent.com/86953456/178494182-b08d70f9-cf25-4692-ad72-e3db76da6584.mp4

https://user-images.githubusercontent.com/86953456/178494217-4b51b392-c11e-4041-9eb3-66e82616b02f.mp4

**Found in Branch**
Development [381a6e0]

**Desktop/Device:**
- Device: PC
- OS: Windows
- Version: 10 Pro
- CPU: AMD Ryzen 9 3900X
- GPU: GeForce RTX 2060 SUPER
- Memory: 16GB

**Comment by AMZN-Olex** [comment]
This issue is a consequence of running nav mesh update during entity activation, other colliders on the level are not yet activated so the nav mesh calculation misses entirely.

![image](https://user-images.githubusercontent.com/5432499/179616328-1a90303b-95e5-4181-8164-1ebbdd5c4445.png)

You can avoid this situation by waiting until all other entities have been activated in the level.

**Comment by AMZN-Olex** [comment]
If you wait one tick, this issue does not repro because one tick is enough to activate all other entities.

For example, I opened the attached test asset and modified to wait one tick, which solves the issue.
![image](https://user-images.githubusercontent.com/5432499/179617333-d5ec3900-0751-4747-b786-ac9f3b3d522e.png)

**Comment by LB-MateuszSzweda** [comment]
Change to the script was verified as fixing the above issue in all similar navigation scripts in Development (cd1594b). Thanks.
