### ISSUE TITLE
Linux: Input and On Variable Value Changed interaction is inconsistent

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#10637]
**Describe the bug**
On Linux, "On Variable Value Changed" node, and an "Input Handler" triggered simultaneously in the same graph results in an inconsistent behavior. Holding an input key modifying a given variable, in the beginning does not trigger the "On Variable Value Changed" node. After a while, both the input, and the "On Variable Value Changed" are working simultaneously. If another input (even one that is not picked up by the .inputbindings) is introduced, while the original input key is being held, the "On Variable Value Changed" node stops working until the original input key is not being held anymore.

It should be noted that on the attached video around for example 0:33 it looks as if the 1 key is not being held anymore on the screen key capture, while it is. The key is let go when the "On Variable Value Changed: {Value}" start getting printed to the Console, instead of the "Input: {Value}".

**Prerequisites**
Recreate .inputbindings (Tools > Asset Editor > File > New > Input Bindings), and .scriptcanvas (Tools > Script Canvas > File > New Script) assets as shown on the screenshots attached under the **Video, .inputbindings, and .scriptcanvas** section.

**Steps to reproduce**
1. Create an entity, add Input, and Script Canvas components to it.
2. Attach the .inputbindings, and .scriptcanvas assets mentioned in the **Prerequisites** section, to their respective components on the entity from step 1.
3. Enter the Game Mode.
4. Hold 1 on the keyboard, after a while press any other key without letting go of the 1 key.

**Expected behavior**
Console output while holding the 1 key does not change.

**Actual behavior**
Console output is affected by how long the 1 key is being held, and whether or not another input is introduced.

**Video, .inputbindings, and .scriptcanvas**

https://user-images.githubusercontent.com/86952082/178700842-358c0f33-12ec-45de-b7cd-7647a66d1703.mp4

.inputbindings asset:
![InputVarChangedIB](https://user-images.githubusercontent.com/86952082/178704385-b601a874-309d-4e7e-af8c-2e5c171e0449.png)
.scriptcanvas graph (Variable 1 is a Number type variable, with Default Value set to 0):
![InputVarChangedSC](https://user-images.githubusercontent.com/86952082/178704413-3695d961-a478-4473-a026-2b44892086cd.png)

**Found in Branch**
Development (f23a666)

**Desktop**
 - Device: PC
 - OS: Linux
 - Version: Ubuntu 20.04.3 LTS
 - CPU AMD Ryzen 5 3600
 - GPU NVIDIA GeForce RTX 2060 SUPER
 - Memory 16GB

**Comment by onecent1101** [comment]
@LB-ArturZieba I think there is misunderstanding of Heart Beat usage (and I don't follow why do you use Heart Beat node after on variable change, or what you are trying to achieve). Based on your graph, lemme explain what is the workflow will look like:
1. As you hold button and trigger +1 on variable, there will be multiple on variable change event gets sent out and queued to be executed.
2. When multiple on variable events get triggered and reach Heart Beat node, this is the problem comes. First, Heart Beat node holds an internal cycle to repeat action you connected to Pulse slot; Second, Heart Beat node will restart a new cycle which will stop on going cycle whenever you hit Start slot. 

Do you see what is problem? when multiple on variable events keep getting executed, it will keep ping Heart Beat node to start, and Heart Beat node will keep canceling ongoing cycle. In this case, you can't control the behavior, as you can't guarantee what step the last cycle has reached. And even worse, in the graph, you are modifying the variable inside Heart Beat cycle. In this way, behavior is unexpected for sure.

Please let me know what you are trying to do in the graph, then I can guide you how to make a correct graph.

**Comment by LB-ArturZieba** [comment]
This issue was reported mostly due to the different behavior on both systems, as mentioned in the description. 

While the explanation provided cleared things up, and makes sense that this would cause unexpected behavior (potentially working differently on both OS), there is also a second part to this issue, and that is input. While using multiple inputs at once on Windows works without issue, on Linux the behavior shown on the original video still occurs, causing things like PhysX Character Controller movement to "stutter" (for example forward + right does not cause the entity to go diagonally, but to go in a stair-shape movement instead). Should this be reported as a separate issue?

Attaching videos from both the Windows and Linux OS (Development (1212214) build) to more clearly depict mentioned input issue:

https://user-images.githubusercontent.com/86952082/179751687-d86d40e6-4bca-4d9d-927f-9f07160c19b7.mp4

https://user-images.githubusercontent.com/86952082/179751717-e8381182-7d38-463f-a914-f47c36899365.mp4

**Comment by onecent1101** [comment]
Second part of issue feels like not part of this GHI, you should create a separate one.

And for second part of issue, the difference on video is very hard to tell. Another thing is if input and scriptcanvas can properly get print out on debug console as expected, the problem maybe related to physics or just rendering issue. Can you verify it? In any way, this GHI should be able to resolve now.
