### ISSUE TITLE
Component Mode Viewport UI Switcher

### ISSUE THREAD

**Issue by hultonha** [o3de/o3de#10662]
## Description

To improve the experience of using Component Edit Mode (internally known as 'Component Mode'), a new Viewport UI element will be introduced (the Switcher) to allow fast switching between Components that support a Component Mode on the entity. This will make Component Edit Modes much more discoverable and easier to use.

## Feature Points of Contact

Stakeholders: @hultonha, @amzn-ahmadkrm, @amzn-leenguy, @yuyihsu 

## Links

**Comment by amzn-ahmadkrm** [comment]
This comment is to log the PRs that were made for the creation of the switcher:

![image](https://user-images.githubusercontent.com/105638312/188612683-0009bf75-3a2b-49c0-bcf4-178023714fd5.png)

The switcher will replace the current workflow of switching between component modes by having the click the "Done" button in the Entity Inspector and clicking "Edit" of the new component mode. The user can click different components on the switcher and transition between the component modes seamlessly.

https://user-images.githubusercontent.com/105638312/188636794-f0075fe9-d9a6-426e-b0f0-657102de339d.mp4

Development PRs:

Initial PR for creating the component mode switcher:
https://github.com/o3de/o3de/pull/10399

Switcher speed improvement + Undo/Redo support:
https://github.com/o3de/o3de/pull/11203

Added support to change into a new component mode instead of ending and restarting:
https://github.com/o3de/o3de/pull/11436/files

Change Icon color to match UX design:
https://github.com/o3de/o3de/pull/11585

Fix interaction between the switcher and ImGui:
https://github.com/o3de/o3de/pull/11570

**Comment by hultonha** [comment]
Thanks very much for updating this @amzn-ahmadkrm, great to see! 🥳

**Comment by amzn-leenguy** [comment]
🎉
