### ISSUE TITLE
Streamline Physics Workflow UX

### ISSUE THREAD

**Issue by hultonha** [o3de/o3de#10668]
## Description

There are a number of areas in the Editor relating to physics workflows that are currently confusing and/or error-prone (most notably _Collider Setup_ and _Rigid Body and Global Settings_). This roadmap item is to track improvements to these areas (as well as more that are identified by the Rev The Engine (RTE) effort.

## Feature Points of Contact

Stakeholders: @hultonha, @greerdv, @moraaar, @SergeyAMZN, @yuyihsu

## Links

(see comments below for links to PRs)

**Comment by hultonha** [comment]
- https://github.com/o3de/o3de/pull/14024
- https://github.com/o3de/o3de/pull/13890
- https://github.com/o3de/o3de/pull/13557

**Comment by moraaar** [comment]
Make it easier for users to understand static vs dynamic colliders:
- https://github.com/o3de/o3de/pull/14418
- https://github.com/o3de/o3de/pull/14484
- https://github.com/o3de/o3de.org/pull/2230

**Comment by moraaar** [comment]
Separate editor PhysX Collider in two components: PhysX Primitive Collider and PhysX Mesh Collider:
- https://github.com/o3de/o3de/pull/14850

**Comment by hultonha** [comment]
All related work has been completed. Closing issue 🥳 

Excellent work @moraaar 😄 🎉

**Comment by moraaar** [comment]
**[Impactful Change]** New PhysX Static Rigid Body component and Editor PhysX Collider split in two components

**What’s changing?**

- We are adding a new “PhysX Static Rigid Body” component and renaming “PhysX Rigid Body” component to “PhysX Dynamic Rigid Body”. PhysX Collider and Shape Collider components now require to add either a static or a dynamic rigid body component.

- The PhysX Collider component is being renamed to PhysX Primitive Collider, it will continue supporting the same primitive types: Box, Sphere, Capsule and Cylinder. We are adding a new component called PhysX Mesh Collider to handle the PhysX Asset type, which uses a PhysX Mesh asset (.pxmesh).

**Why are these change being made?**

- To make it easier for users to understand static vs dynamic colliders. A common mistake was to create an entity with a collider and try to move it (either by code or script canvas), which is incorrect, but there is nothing in the entity that suggests that’s not possible. Now when the user chooses to add a static rigid body it's explicitly chosen to be static, meaning it should not move. If the user chooses to add dynamic rigid body, then it's understood it can be moved.

- To make it easier for users to add colliders to the world, especially at entry level where users just want to add a collider quickly without having to worry about setting up PhysX Mesh assets in FBX Settings. In addition, having a PhysX Mesh Collider component allows us to continue improving the experience of using a PhysX Mesh asset in the future since it can be tweaked without affecting other collider types.

**When are these changes coming to O3DE?**

Changes are already integrated into development branch and will be released with O3DE 2023.05.0


**What actions will I need to take?**

There is a console command that automatically updates all the prefabs in a project. It includes a static rigid body into entities that had colliders and no rigid bodies. It also detects if a PhysX Collider uses PhysX Asset type, and if it does it replaces it with a PhysX Mesh Collider.
These are the steps:
1.	Run Editor. Do not open any level, just close the "Welcome to O3DE" screen.
2.	Wait until Asset Processor has finished processing all the assets
3.	Open Console: Tools > Console
4.	Enter the following console command to update prefabs: `ed_physxUpdatePrefabsWithColliderComponents`
5.	Wait until Asset Processor has finished processing all the assets
6.	Commit the prefabs changes into Github.

The command has already been executed in the following projects:
•	AutomatedTesting
•	o3de-multiplayersample
•	o3de-multiplayersample-assets

•	o3de-netsoaktest
•	o3de-physics-test-scene
•	loft-arch-vis-sample
•	NewspaperDeliveryGame
•	OpenXRTest
•	Robotics: RobotVacuumSample, ROSConDemo, ROS2 gem, WarehouseAssets gem, WarehouseSample gem, RosRobotSample gem, ProteusRobot gem.

**Q: I use PhysX Collider in my python scripts, do I need to update the scripts?**

Yes. 
All [the python scripts from AutomatedTesting](https://github.com/o3de/o3de/pull/14732) will be updated as part of this change, but any other script will need to do the following changes:
1.	When adding the component “PhysX Collider”, replace it with either “PhysX Primitive Collider” if using primitives or “PhysX Mesh Collider” if using PhysX Asset type.
2.	No further changes are needed for PhysX Primitive Colliders.
3.	For PhysX Mesh Colliders do not get/set the property “Shape Configuration|Shape”. PhysX Mesh Collider does not have shape property since it’s not needed anymore (it’s always PhysX Asset type).

**Q: I have C++ code using the PhysX::EditorColliderComponent class, do I need to update the code?**

Yes.
If you are creating and configuring PhysX::EditorColliderComponent classes directly in C++ you’d need to be aware of the following:
-	Update the calls to the bus PhysX::EditorColliderComponentRequests. Here is the [API deprecation](https://github.com/o3de/o3de/issues/14717) GHI with the full list of functions affected.
-	No further changes are needed if using primitives types.
-	If using PhysX Asset type then change the code to use PhysX::EditorMeshColliderComponent class instead.

**Q: Have the runtime components been modified?**

No. This is a change only on the editor collider component.

**Q: This seems like a big change. Have the API version in PhysX gem.json been updated?**

Yes. From 0.0.0 to 1.0.0
