### ISSUE TITLE
As a Dev I Want Renderer To Decide Null Font Usage

### ISSUE THREAD

**Issue by AMZN-Gene** [o3de/o3de#10868]
**Is your feature request related to a problem? Please describe.**
The ServerLauncher is set up to use null font even if the Server is loaded with rendering enabled

(search USE_NULLFONT in code for more info)

**Describe the solution you'd like**
The renderer should decide which font to use. Null renderer should use null font, and the normal renderer should load font.

=

**Comment by lmbr-pip** [comment]
Contents, debug draw text is not displayed by atom because:

`m_fontDrawInterface` in AtomViewportDisplayInfoSystemComponent is set to null.  Theres an explicit check ` AtomFontSystemComponent::OnCrySystemInitialize` that uses the Atom null font if using the dedicated server.

This logic should be updated so if we are rendering, a font is available for debug draw text.
