### ISSUE TITLE
Material Editor: duplicating files from the asset browser context menu allows users to copy files into folders that break references to other files and prevent the material from opening

### ISSUE THREAD

**Issue by HogJonny-AMZN** [o3de/o3de#10944]
**Describe the bug**
find an existing material in material editor asset browser, right-click on it to duplicate, save in a new location, then open the new duplicate.

**Assets required**
No new assets needed.

Prerequisits:
1. my engine repo is: c:\depot\o3de-dev
2. my project is in a separate repo: c:\depot\o3de-gamejam
3. I compile in an engine-centric way (I cmake configure my build, generally with more then one external game project repos.)

**Steps to reproduce**
1. start the material editor
4. go to the material editor asset browser
5. find an existing macbeth material
6. right-click on it, select duplicate, save the duplicate into your level folder:
7.     I saved in: c:\depot\o3de-gamejam\Levels\gradient-baker\baker_test.material
8. Ctrl+O to eopn ...
9. Browse to new .material to open it
10. ... see error

**Expected behavior**
Expected result: the new duplicate material will open.

**Actual behavior**
Actual result: errors on open, the new duplicate can not be opened.

**Screenshots/Video**
If applicable, add screenshots and/or a video to help explain your problem.

**Found in Branch**
latest development

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: windows
 - Version win11
 - CPU threadripper
 - GPU rtx-3070
 - Memory: system 128 GB

![image](https://user-images.githubusercontent.com/23222931/181607068-1ba38699-2dbb-43b4-af38-1ae7debeb9ee.png)

**Comment by gadams3** [comment]
I'm not sure that this in itself is a bug, at least not a unique one. It's duplicating the material files the same way as you would move or copy and paste files through the OS. While it could, it does not currently open the file to update any of the file references as part of duplicating. 

The old Macbeth materials are also using ../../ relative paths instead of asset folder relative paths which will not be resolvable if you're only copying the material file. You will have to resave the Macbeth materials with asset folder relative paths before or after you copy them.

I think we need to replace relative paths with gem and project aliased paths then update all of the materials and material types to use them. Then duplicating or moving materials or material types will always be able to find the files that they referenced unless those files get moved as well. There is already a bug reported for that issue.

**Comment by gadams3** [comment]
resolved by having the duplicate action duplicate in the same folder
