### ISSUE TITLE
Remove "Anim Graph Palette" window and move functionality (No dependency)

### ISSUE THREAD

**Issue by hultonha** [o3de/o3de#10963]
[Migrated from JIRA LYN-14133]

Please see the attached video called "CurrentState_HowToCreateNodes.mp4" to see the currently available ways on how to create nodes in the anim graph.

The aim of this task is to get rid of the "Anim Graph Palette" (first shown in the video) and improve the context menu based version (shown afterwards in the video).

The new workshow shall be like in the "Script Canvas" tool. Please see the video "NewWay_LikeInScriptCanvas.mp4" on how that shall work.

**Acceptance Criteria:**

- EMStudio::NodePaletteWidget code is removed from the project including the NodePaletteWidget.h/.cpp.
- The context menu provides a search widget to search for the available nodes as well as a tree view to easily select them (like in the previous node palette widget).

**Additional Info:**

https://user-images.githubusercontent.com/82228511/181770313-2a7586d2-154b-4e8d-a3de-eb62cf02ded1.mp4

https://user-images.githubusercontent.com/82228511/181770324-bc63c468-e6b3-489e-a795-f6e58b8bb124.mp4

**Comment by cgalvan** [comment]
This might be tricky since EMFX doesn't use `GraphCanvas`. Feel free to reach out to me if you have any questions.

**Comment by MiKom** [comment]
@cgalvan Maybe we won't need to fully switch EMFX to `GraphCanvas`. `NodePaletteWidget` and associated classes from `GraphCanvas` seem to be sufficiently independent from the rest of the `GraphCanvas` to be reusable in EMFX as long as I maintain my own tree of `NodePaletteTreeItem` objects.

I'll see how feasible this is on Monday.

**Comment by MiKom** [comment]
@bhanuja-s 

Hey, a question about the old palette window: are we sure we want to completely get rid of it? In other canvas-based tools we have the node palette available both under the context menu and in a separate dockable widget as well:

ScriptCanvas:
![image](https://user-images.githubusercontent.com/104767/185173557-c259a9de-c226-4f2c-adc1-4d65b2ce3717.png)

LandscapeCanvas:
![image](https://user-images.githubusercontent.com/104767/185174397-b6130f3d-32b4-41a4-adbf-9500acd31e64.png)

Maybe, for the sake of uniformity we should keep the node palette in the anim graph as a dockable widget?

**Comment by bhanuja-s** [comment]
@MiKom 

There are advantages to both methods of adding nodes, one allows, possibly advanced, users to quickly scan through the categories and add nodes and the other allows novice users to view and understand the node categories and its distinguishing features (colour, nodes, tooltips).

As for the dockable nature of the Node Palette, we should keep it in the Toolbar Menu and when clicked it would appear in the window (as it does now). Through this, users have multiple methods of adding nodes and can choose their preferred one.

Thoughts? @rainbj @yuyihsu

**Comment by MiKom** [comment]
> As for the dockable nature of the Node Palette, we should keep it in the Toolbar Menu and when clicked it would appear in the window (as it does now). Through this, users have multiple methods of adding nodes and can choose their preferred one.

Sure. That's exactly what I meant, providing the node palette adding through context menu *and* keeping the Node Palette dockable window. 

@hultonha If we're in agreement, I suggest we should update the task to not talk about removing the node palette dock but instead we could extend the task to also cover migration of the dock to the `NodePaletteWidget`.

**Comment by yuyihsu** [comment]
Agreed with @MiKom and @bhanuja-s 's assessment. The key point here is to make the right click context menu for adding nodes behave and look similarly to the ScriptCanvas's behavior. From user research we noticed that users are used to use the right click menu, instead of the palette (also because it's often hidden behind other windows), therefore we want to optimize the right click menu, but necessarily to get rid of the node palette. Let's move forward with @bhanuja-s 's suggestion. let us know if there's more questions.

**Comment by MiKom** [comment]
@yuyihsu I made it use the exact same palette widget in the context menu as ScriptCanvas:

https://user-images.githubusercontent.com/104767/185449520-044859aa-2494-420e-9fff-1c48b1859332.mp4

This way the users have exactly the same experience and UX as in other GraphCanvas-based tools.

It will require code cleanup and some additional features (like node coloring).

**Comment by yuyihsu** [comment]
Looks great @mikom. One thing can you help us look into is the logic how the nodes are displayed in the context menu in EMFX. currently if the nodes aren't usable based on context, those nodes will be hidden from the context menu. This behavior confused the users and limited their learnability. 

I'd like to change the behavior always display the nodes, but only gray out the nodes that aren't ready to be used in certain context, instead of hiding them. Users won't be able to add the grayed out nodes to the canvas, only the enabled ones.

What do you think? will this work?

**Comment by MiKom** [comment]
I have an initial version with greying-out:


https://user-images.githubusercontent.com/104767/185649444-4be7ed41-9ad0-43c6-b936-f67c8be13243.mp4

**Comment by FuzzyCarterAWS** [comment]
@hultonha

Added references to testing this in the Animation Editor Workflow Automation Updates.

https://github.com/o3de/sig-simulation/pull/22
