### ISSUE TITLE
Move anim graph node groups window functionality to context menu and remove plugin (No dependencies)

### ISSUE THREAD

**Issue by hultonha** [o3de/o3de#10961]
[Migrated from JIRA LYN-12677]

Please see attached video regarding the current workflow on how to create, edit and remove node groups.

The whole Node Groups window shall be removed and all of its functionality shall move to the context menu of the graph window.

**Acceptance Criteria:**
 * A new node group can be added when bringing up the context menu in empty graph space. A pop-up window will ask for the name as well as the color for the node group.
 * Node groups can be deleted via the context menu. The "Node Groups" menu item currently can only be accessed when having a node selected that is part of the group. This needs to be changed and that menu item needs to be accessible any time. Each node group can get a sub-element to remove it.

![image-2022-07-26-09-23-06-419](https://user-images.githubusercontent.com/82228511/181768947-720de8a3-5965-45ef-acaf-3765830a0b37.png)

- The same sub menu (Node Group -> NodeGroup2 -> X) can be removed to also provide an option to:
  - Change its color
  - Rename it
  - Show/hide it (change visibility flag)
- The code for EMStudio::NodeGroupWindow including the whole NodeGroupWindow.h/.cpp files are removed from the project

Additional Info:

https://user-images.githubusercontent.com/82228511/181769114-37cd1952-d095-45ac-a147-a98681a607a1.mp4

**Comment by hultonha** [comment]
Update: Discussed this, there several ways to implement this. Proposed solution would be to add icons to the right click context menu to open the different options (e.g. color or removing an item). To be discussed with sig-ui-ux

Tagging @bhanuja-s and @yuyihsu for visibility - this would be great to review and clarify.

**Comment by aambrosano** [comment]
@bhanuja-s @yuyihsu Would it be an option to be able to click/double click on the group name and display a line edit widget to update the group name? We can do something similar for the color. Namely render a coloured square on the left of the group name and when the user click we display the color picker and change the color.

Of course this solution is more complex than just adding items on the context menu.

What do you think?

**Comment by bhanuja-s** [comment]
After discussion with the UX team, we like the idea of improving these interactions with the use of right-click context menus. I think there are two stages of design for this: revisiting our context menus and refining them, and the second, which is @aambrosano's suggestion.

Currently, we can't click on a Node Group to select just that and manage it. We think it would be a useful implementation, as it would allow users to (as you said) double-click on the Group's label to rename it. Additionally, it would allow for the second stage of having a pop-up with the Edit Colour, Rename, Show/Hide and Delete icons (building on @aambrosano's suggestion).

I have attached the first stage of refining our menus, along with the double-click interaction for renaming the Group.

1.1.X - Right Click on Node (outside a Group)

![1 1 1](https://user-images.githubusercontent.com/84036086/184156585-a68f050d-2ab4-4ab2-ab31-21335369594a.png)

![1 1 2](https://user-images.githubusercontent.com/84036086/184156704-c9e9a82e-a9b8-4328-82b2-dea5b6b9c08a.png)

1.2.X - Right Click on Node (inside a Group)

![1 2 1](https://user-images.githubusercontent.com/84036086/184156758-a8c49a94-0c98-4389-ad28-904d2030d783.png)

1.3.X - Right Click on Node Group

![1 3 1](https://user-images.githubusercontent.com/84036086/184156779-14708ea9-ac3b-4588-84b6-5ae75002b3f3.png)

![1 3 2](https://user-images.githubusercontent.com/84036086/184156800-28eeff65-3b8b-4049-a8ad-06d78a266446.png)

1.4.X - Double-Click on Node Group Label

![1 4 1](https://user-images.githubusercontent.com/84036086/184156824-c9ec14a3-fae1-40ad-b5b3-3a8eb3534417.png)

Please let me know if you need clarification on any aspect. Thank you!

CC: @rainbj @amzn-leenguy @yuyihsu @amzn-jillich

**Comment by rainbj** [comment]
Only one small bit of feedback is how you have the name outside the node. Based on collapsing nodes, we should have the same name location as ScriptCanvas title location (inside node. If it lives outside the grouping, it looks like a new group standing by itself. This would be confusing for customers.

**Comment by bhanuja-s** [comment]
> Only one small bit of feedback is how you have the name outside the node. Based on collapsing nodes, we should have the same name location as ScriptCanvas title location (inside node). If it lives outside the grouping, it looks like a new group standing by itself. This would be confusing for customers.

Gotcha, I'll check out Script Canvas' paradigm and follow that! Thank you ☺️ 

Would you agree with the 1.3.X direction on hiding the node group? Rather than it disappearing completely, as we would no longer have the panel to make the group visible again.

**Comment by bhanuja-s** [comment]
I've redesigned the Node Group to be like Script Canvas'

![Group](https://user-images.githubusercontent.com/84036086/185392920-b45f07c2-2fa8-4c20-a8a6-38f4ffb9faaa.png)

**Comment by aambrosano** [comment]
@bhanuja-s Thank you!
I will follow your design as close as I can just by looking at it, but will need to have some metrics at some point to refine the implementation.

**Comment by aambrosano** [comment]
@bhanuja-s Just realized there's no way to change the group color with the current design.

**Comment by bhanuja-s** [comment]
> @bhanuja-s Thank you! I will follow your design as close as I can just by looking at it, but will need to have some metrics at some point to refine the implementation.

Sounds great!

**Comment by amzn-jillich** [comment]
The initial idea with the context menu was that the context menu will provide a list of node groups as sub menu entries and via that can be shown again. Does that still make sense after the UX changes @bhanuja-s, @yuyihsu ?

**Comment by bhanuja-s** [comment]
Hi, 

Apologies for any delay in this task - I've created the following designs for the new contextual toolbar.

Please invite me to a review when this work is semi-completed, I would like to test the implementation and the different workflows for any issues.

Please feel free to reassign the ticket to the dedicated developer, and to ping me for any further details or interactions (CC @hultonha).

Thank you!

#### 01 When Node Group is unselected

![01](https://user-images.githubusercontent.com/84036086/189189213-d8fd2069-dbf9-4883-b2b6-5b9fba4e4303.png)

#### 02 When Node Group is clicked on, or selected

![02](https://user-images.githubusercontent.com/84036086/189189240-a2cb8436-fd5c-4f4b-8ef2-41a53ffe85bc.png)

#### 03 When user clicks on first icon, or wants to change the colour (all such interactions must show the toolbar)

![03](https://user-images.githubusercontent.com/84036086/189189254-a477dcc1-ce44-4a33-96d9-8f5e0f6a7d56.png)

#### 04 When user clicks on second icon, or wants to rename the Node Group (all such interactions must show the toolbar)

![04](https://user-images.githubusercontent.com/84036086/189189266-c85a6376-6c9b-4fd1-be7b-f1e4d895887a.png)

#### 05 When user clicks on third icon, or wants to hide/show Node Group

![05](https://user-images.githubusercontent.com/84036086/189189275-57583cdd-a982-47ea-b670-cdbfe0c29083.png)

**Comment by hultonha** [comment]
This is excellent thank you @bhanuja-s! 😄 

@MiKom and @aambrosano - let us know if that answers your questions (feel free to ping me direct if there's anything to clarify). Thanks!

**Comment by MiKom** [comment]
The WIP branch from @aambrosano is located here: https://github.com/o3de/o3de/compare/development...aambrosano:o3de:10961-animgraph-use-context-menu-options-for-node-groups

**Comment by MiKom** [comment]
@hultonha It  probably needs some more work before PR can be opened. Not sure if it will be me who picks it up. Depends on who's done first with their current tasks.

**Comment by Be-ing** [comment]
I can pick this up following the [most recent mockups](https://github.com/o3de/o3de/issues/10961#issuecomment-1241034390). Unfortunately it @aambrosano's branch doesn't build because he forgot to commit a new file which was added to a .qrc file. @bhanuja-s do you have the Rename.svg file referenced in the branch? Or whatever icon you used for renaming in the mockup?

**Comment by bhanuja-s** [comment]
Hi, 

I've sent the SVG to Be, and have attached it to this message too. Thanks for your patience!


![Rename](https://user-images.githubusercontent.com/84036086/194079659-5adb3b3a-5b3c-451c-be51-e9222a8c7c9c.svg)

**Comment by hultonha** [comment]
That's great thank you @bhanuja-s! 😄

**Comment by Be-ing** [comment]
I rebased @aambrosano's [branch](https://github.com/o3de/o3de/compare/development...aambrosano:o3de:10961-animgraph-use-context-menu-options-for-node-groups), which turned out to be quite tricky with the merge conflicts introduced by https://github.com/o3de/o3de/pull/11595. So far, the old docked NodeGroupWindow has been removed and replaced with the [original design](https://github.com/o3de/o3de/issues/10961#issuecomment-1212064884) using a right click QMenu with standard QActions:

Right clicking outside of any nodes or groups brings up the new menu from https://github.com/o3de/o3de/pull/11595 + https://github.com/o3de/o3de/pull/12429 for creating new nodes:
![context-menu-rebased-new-node](https://user-images.githubusercontent.com/9455094/194464079-0fa757da-4721-422f-88c7-f2fd3f416396.png)

Right clicking a node allows creating a group:
![context-menu-rebased-new-group](https://user-images.githubusercontent.com/9455094/194464268-839ce21b-835f-4f89-9b85-15e849c755c7.png)

Right clicking a node after a group has been created allows assigning it to a group:
![context-menu-rebased-assign-group](https://user-images.githubusercontent.com/9455094/194464352-89885e3f-67c8-48ba-ac48-3679ea88ed7f.png)

Right clicking the group outside of the nodes' areas brings up a new menu for editing the group's properties
![context-menu-rebased-edit-group](https://user-images.githubusercontent.com/9455094/194464373-1bfcd075-bea2-4b98-b9df-76fcda05c807.png)

I will work on replacing this standard QAction menu for editing the group's properties with the [new design](https://github.com/o3de/o3de/issues/10961#issuecomment-1241034390), likely implemented using a QWidgetAction with a new custom QWidget.

**Comment by hultonha** [comment]
This looks great @Be-ing! Thank you very much for the update and all the additional screen shots, super helpful! 🙂 Tagging @bhanuja-s for visibility to review as well. Let us know when your rebased branch is published for PR and I'll be sure to take a look. Thanks!

**Comment by bhanuja-s** [comment]
Thank you for the update @Be-ing! This is great ☺️

**Comment by Be-ing** [comment]
@bhanuja-s 
> 02 When Node Group is clicked on, or selected
![mockup](https://user-images.githubusercontent.com/84036086/189189240-a2cb8436-fd5c-4f4b-8ef2-41a53ffe85bc.png)

I started working on this but it felt awkward and out of place to have left click bring up a toolbar. I'm also not sure it would be good to have only those icons without any explanatory labels showing. I think it would be better to go back to the regular right click context menu but cleaned up a bit to get rid of the submenus and reduce the number of dividers:

![nodegroup-menu](https://user-images.githubusercontent.com/9455094/195249150-9058a367-81f4-4631-90be-88aa053e7d6d.png)

Instead of single click bringing up a context menu, I propose to make single clicking in the group's area (including title area) select all the nodes in the group, then clicking and dragging would move the whole node group together.

I also propose reworking hiding/showing node groups. Instead of suspending a mini representation of the groups in the top left of the graph when hidden:

> 05 When user clicks on third icon, or wants to hide/show Node Group
![hidden-group](https://user-images.githubusercontent.com/84036086/189189275-57583cdd-a982-47ea-b670-cdbfe0c29083.png)

I propose making the node groups collapsible by placing an expand/collapse icon:
![expand-collapse-icons](https://user-images.githubusercontent.com/9455094/195251568-8c42548f-7f2b-4877-a950-659c91f8f204.png)

in the top left corner of the group, adjacent to the group name. This would allow removing "Hide Group" from the right click context menu, leaving only 4 entries in that menu.

**Comment by hultonha** [comment]
Thanks for the update @Be-ing. Leaving a brief update after we caught-up about it on the call.

- Decided clicking background should select nodes together so you can click and drag them together as a group (video showing this would be awesome)
- Context menu should display with right click to be consisted
- Collapsing groups would be cool but is likely out of scope of this ticket - we'll review with @bhanuja-s and decide the priority and I can create a follow-up ticket if required.

Thanks! And feel free to chime in @bhanuja-s if I missed anything or got anything wrong.

**Comment by hultonha** [comment]
Thanks for the update @bhanuja-s, let me know if you have any other questions @Be-ing. I'll create a separate issue for point 2 (to do group collapsing). How high priority would you say this is @bhanuja-s? Do we definitely need this now or is is something we can live without? Thanks!

**Comment by bhanuja-s** [comment]
I would state it as a Major, but not a Critical or Blocker!

**Comment by Be-ing** [comment]
> Instead of single click bringing up a context menu, I propose to make single clicking in the group's area (including title area) select all the nodes in the group, then clicking and dragging would move the whole node group together.

I implemented this:
[node-group-selection.webm](https://user-images.githubusercontent.com/9455094/196601186-267546cb-5760-48d2-80ee-018550ac33b1.webm)

A remaining question before I open a PR: Should nodes be able to belong to multiple groups, or should node groups be mutually exclusive? Currently the context menu allows assigning one node to multiple groups, but it only gets the background drawn as part of one group. It feels odd to have nodes able to belong to multiple groups; I suggest making groups mutually exclusive.

**Comment by hultonha** [comment]
That looks awesome @Be-ing! 😄 Thanks for including the video (tagging @bhanuja-s for visibility as well).

Hmm I think mutually exclusive makes the most sense agreed, if you try and assign a node to a different group it is removed from the existing one and added to the next one.

**Comment by bhanuja-s** [comment]
That looks great! I agree, mutually exclusive makes sense. I do have a question, when a user tries to move a node within a Node Group, what does that interaction look like, i.e. just to arrange it within the group itself?

**Comment by Be-ing** [comment]
I thought about that, but then clicking and dragging to move the whole group would require clicking on the background, not any of the nodes.

**Comment by Be-ing** [comment]
A better idea: when clicking on a node in a group, if all the nodes within the group are selected, clear the selection except for the clicked node.

**Comment by bhanuja-s** [comment]
> if all the nodes within the group are selected, clear the selection except for the clicked node

This is what I meant before, but I have a question, why would a user click on a node to move the group? The movement should be dictated by what they've selected. 

1. If the user clicks on a node, within or without a node group, then that node should move.
2. If the user clicks on multiple nodes, within or without a node group, then those nodes should move.
3. If the user clicks on the node group, its title or background, the group should move with all the nodes in their grouped position.

**Comment by FuzzyCarterAWS** [comment]
@hultonha @bhanuja-s @Be-ing 

Updated the workflow docs in o3de/sig-simulation#22
