### ISSUE TITLE
Show Terrain Queries is drawn inconsistently

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#11020]
**Describe the bug**
Debug lines drawn by Terrain World Debugger's "Show Terrain Queries" property are being misplaced by camera movement, causing them to not cover the PhysX Heightfield Terrain properly, and creating an unusual visual effect.

**Prerequisites**
Project with the Terrain Gem active.

**Steps to reproduce**
1. Create a new level.
2. Remove the Ground entity (required for visibility in later steps).
3. Select the Level.prefab in the Entity Outliner, add Terrain World, Terrain World Renderer, and Terrain World Debugger components to it.
4. Create a new entity, add PhysX Heightfield Collider, Terrain Physics Heightfield Collider, Axis Aligned Box Shape (set Dimensions to bigger numbers, for example X: 5; Y:5; Z:5), and Terrain Layer Spawner components to it.
5. Place the entity from step 4, so that it is within bounds of the Terrain World (for example Translate: X: 11; Y: 1.5; Z: 0).
6. In the Terrain World Debugger component on the Level.prefab, enable the Show Terrain Queries property.
7. Move the camera around the entity from step 4.

**Expected behavior**
Debug lines are drawn in the same place all the time.

**Actual behavior**
Debug lines are misplaced by the camera movement.

**Video**

https://user-images.githubusercontent.com/86952082/182380567-210ea4ef-7e2f-4d5a-95b2-483436c3ef19.mp4

**Found in Branch**
Development (4212e91)

**Desktop**
 - Device: PC
 - OS: Windows
 - Version 11
 - CPU AMD Ryzen 5 3600
 - GPU NVIDIA GeForce RTX 2060 SUPER
 - Memory 16GB

**Comment by invertednormal** [comment]
This is by design and allows people to easily debug exact points that don't lie on the grid lines. You can make it not move with the camera though - notice at the bottom of the "Show Terrain Queries" group, there is a toggle to either use the camera position or to specify a world possition. If you specify a world position then the queries will be based off of that point instead of the camera.

**Comment by mbalfour-amzn** [comment]
The current behavior is definitely by design, but the design might have gone a bit too far. 

As @invertednormal says, the points themselves intentionally move with the camera position so that you can see terrain queries at a lot of points around the camera, and this can be toggled to instead use an absolute position.

However, to make as many points visible as possible, there's a bit of extra logic to query the points centered around a point projected forward in _front_ of the camera, as opposed to just using the camera position itself. It was meant to be helpful, but it might be making things a bit more disorienting because rotating the camera without moving also causes the points to move around. I'll remove this extra logic so that camera rotation won't affect the queries, just camera position.

**Comment by LB-ArturZieba** [comment]
Issue verified as fixed on the Development (a88f38d) build, the Terrain Queries debug lines do not move with the camera rotation. Thank you for explanation, I did not notice the "Use Camera Position" property earlier.
