### ISSUE TITLE
Bug Report: Prefabs do not save Detour Navigation Mesh target Entity

### ISSUE THREAD

**Issue by ParasiteSt** [o3de/o3de#11054]
**Describe the bug**
If you have an entity that is utilizing the Detour Navigation Mesh Component you will see it have a target which will be the navigation mesh. If you create a prefab from this entity and retain the target id everything works with your prefabs. But when you restart the editor it loses all the connections that it had to entities outside of the prefab.

**Assets required**
Recast Navigation Gem
Prefab Builder Gem

**Steps to reproduce**
1. Create a new entity and add the Detour Navigation Mesh Component to it.
2. Create another new entity and add a Recast Navigation Mesh to it.
3. Target the second entity with the first entity's Detour Navigation Mesh Component.
4. Create a prefab with the first entity and retain the target id's
5. Restart the editor and see the bug.

**Expected behavior**
If I retain a target id with a prefab I would expect the prefab to continue to hold the target id after an editor restart.

**Actual behavior**
A prefab does not retain a target id when you do an editor restart.

**Found in Branch**
Development [8493375]

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version: 11

**Additional context**

**Comment by hultonha** [comment]
Tagging @AMZN-Olex for visibility

**Comment by AMZN-Olex** [comment]
Does the prefab contain both entities? if not, then a prefab can't reference an entity that is outside of the prefab.

**Comment by hultonha** [comment]
Interesting... is this a restriction of Prefabs right now then? 🤔 Will this not work until we have overrides? (Tagging @AMZN-daimini and @srikappa-amzn for visibility as they may be able to answer this). Thanks!

**Comment by AMZN-Olex** [comment]
It was the same with slices, too.

**Comment by AMZN-daimini** [comment]
> Interesting... is this a restriction of Prefabs right now then? 🤔 

Yes, you can't save references to entities outside the prefab (unless they're descendants). That's mostly cause it doesn't make sense and it's hard to handle the case where that relative path is not resolvable.

It probably would make sense for the references to be cleared on prefab creation though, so that may be the next step.

> Will this not work until we have overrides?

This would potentially work with overrides, but probably not if the reference is set before the prefab is created. You'd have to create the prefab, then expand it for overrides and set the reference then (so that it's saved to whatever the current focus is).


I do think this is by design, but the follow-up would be to have some logic that clears references to entities outside the newly created prefab during the creation process to prevent confusion. (Bonus points if it has a dialog/toast message telling the user that some references were lost)

**Comment by srikappa-amzn** [comment]
I agree that breaking the references during the creation itself is a cleaner way to prevent confusion. We'd have to be careful not to do something like string replacement to remove references in the template though because we recently found that it can be very expensive on large prefabs. (Currently duplicate logic does something similar, where replacing aliases is expensive).

It is also interesting that the references work immediately after creation but not when the editor restarts. That sounds like a bug to me. If the references are intact after creation, maybe we can keep them intact during saving and reloading as well. That might be also an avenue to pursue here.

**Comment by AMZN-daimini** [comment]
> I agree that breaking the references during the creation itself is a cleaner way to prevent confusion. We'd have to be careful not to do something like string replacement to remove references in the template though because we recently found that it can be very expensive on large prefabs. (Currently duplicate logic does something similar, where replacing aliases is expensive).
> 
> It is also interesting that the references work immediately after creation but not when the editor restarts. That sounds like a bug to me. If the references are intact after creation, maybe we can keep them intact during saving and reloading as well. That might be also an avenue to pursue here.

Well, references technically can work. The reason we don't save them to the template is that they would result in a relative path that goes to the ancestors of the prefab... so what happens if the prefab is instantiated in a different hierarchy and that path is unresolved?
If we were to cleanly handle that case (maybe a dialog pops up telling that a reference is not resolving, and allows to pick a different target?) then we could store these paths. But in the general case, it makes more sense to just clear them and allow them to be overridden, cause that is the more sane way of organizing prefabs :)

**Comment by srikappa-amzn** [comment]
> The reason we don't save them to the template is that they would result in a relative path that goes to the ancestors of the prefab
I don't think there is any explicit logic right now that removes references from the prefab. They either work if the relative paths can be resolved or they don't work if relative paths can't be resolved.

Discussed with @AMZN-daimini offline on this. Basically there are a couple of ways we can solve the problem of broken references:

1. Convert direct entity references to overrides during prefab creation. This can be done automatically by the prefab system or we can ask the user to give permission to do so.
Pros: Once prefab is created, references will always work no matter where they are instantiated
Cons: Can't work until overrides authoring is fully supported in the editor.

2. Let entity references work when they are outside of a prefab. For example, a wheel prefab referencing a car prefab will work. But if the wheel prefab is put under bike prefab, the reference will be broken. We can show a warning to the user about the broken references when they instantiate.
    - Pros: 1. Requires minimal effort. And can work without overrides support too. 2. References can keep working as long as prefabs are duplicated in the same hierarchy
    - Cons: 1. Can be confusing why instantiations break references when they are in a different hierarchy. 2. Would have to implement logic to resolve references for instantiations anyway. So you are implementing the first solution also in some fashion.

**Comment by ParasiteSt** [comment]
I did not realize their was a node in Script Canvas that allows for setting the Detour Mesh Entity. This is all that is needed for my issue, but should I keep this report open for the topic on targeting entities in prefabs? 
Tagging @hultonha and @AMZN-daimini for insight.

**Comment by hultonha** [comment]
Thanks for all the info and discussion @AMZN-daimini and @srikappa-amzn - perhaps we should open a separate issue (feature) for this if we do want to track it and close this issue as @ParasiteSt was able to find a workaround? Thanks for all the info, I didn't realize it was so complicated 😅

**Comment by ParasiteSt** [comment]
I am going to close this issue as I have found the best way to set the Mesh entity. Saving references to entities outside of the prefab does not make a lot of sense, and as long as there is ways to set references during runtime for components there should never be a reason to add such a feature.

**Comment by hultonha** [comment]
> I am going to close this issue as I have found the best way to set the Mesh entity. Saving references to entities outside of the prefab does not make a lot of sense, and as long as there is ways to set references during runtime for components there should never be a reason to add such a feature.

That's great to hear, thanks for following-up @ParasiteSt. If you find anything else let us know! 🙂
