### ISSUE TITLE
Setting language format to language which has a comma punctuation sign as a decimal separator breaks various default values in Editor

### ISSUE THREAD

**Issue by LB-MateuszSzweda** [o3de/o3de#11139]
**Describe the bug**
Setting a language format with Ubuntu **Region&Language** menu to a language which has a _comma_ punctuation sign instead of a _full stop_ before decimal numbers was observed to break several values in the Editor leading to problems such as:

- Debug colors being black.
- Mesh material colors being black.
- Incorrect values in PhysX materials from _Gems\PhysX\Assets\PhysX_ directory.

The formats which have a _comma_ punctuation sign before decimal numbers are, among others:
Polish, Italian, French, Cyprian, Turkish, Danish, Spanish.

This issue is not linux-specific.

For further information please refer to the screenshots comparing effects of Language formats and a video file.

**Prerequisites**:
 * Polish, Italian, French, Cyprian, Turkish, Danish or Spanish formats were downloaded for Ubuntu 20.04 LTS

**Steps to Reproduce**:
 1. Open **Region&Language** menu found in Ubuntu Settings.
 2. Set _Polish_ or _Danish_ as a format for language.
 3. Log off and log in on the Linux account to apply the format change.
 4. Launch the Editor and create a new level.
 5. Open the Asset Editor.
 6. Open the _Gems\PhysX\Assets\PhysX\glass.physxmaterial_ and take a note of its
 physical values and debug color.
 7. Change language format to United Kingdom and repeat steps 3-6.

**Expected behavior**
Changing language format to a language which has a _comma_ punctuation sign instead of a _full stop_ before decimal numbers
does not break default values in the Editor.

**Actual behavior**
Changing language format to a language which has a _comma_ punctuation sign instead of a _full stop_ before decimal numbers
does breaks default values in the Editor.

**Screenshots/Video**

https://user-images.githubusercontent.com/86953456/183427055-f99f4812-bbef-487b-981f-343e327bf9a0.mp4

![Glass phyxmaterial Polish language format](https://user-images.githubusercontent.com/86953456/183427075-387fbb88-5b32-4638-b234-586b27416019.png)
![Glass phyxmaterial US language format](https://user-images.githubusercontent.com/86953456/183427088-30525597-df9a-4480-afac-5533b259c897.png)
![Viewport Polish language format](https://user-images.githubusercontent.com/86953456/183427098-ae40e907-d7fe-4def-9df7-50a3076d8ff1.png)
![Viewport US language format](https://user-images.githubusercontent.com/86953456/183427113-93c07f2d-43b6-4ea9-8830-8e4de7c42a1c.png)

**Found in Branch**
Development (8b8ee81)

**Desktop/Device:**
- Device: PC
- OS: Linux
- Version: Ubuntu 20.04.4 LTS
- CPU: AMD Ryzen 9 3900X
- GPU: NVIDIA GeForce RTX 2060 SUPER
- Memory: 16GB

**Comment by forhalle** [comment]
This issue is not linux-specific.

@LB-MateuszSzweda  - Can you please provide additional information on the specific test you were running when this issue occurred? We are curious why this didn't occur before... Did you recently change your locale? If so, we may want to consider changing back the locale, and reducing the priority on this issue, as a larger localization pass is likely needed on the Engine.

Some related PRs:
#2389
#2387
#2982

**Comment by LB-MateuszSzweda** [comment]
@forhalle 

This occured for me when I've set up a new Ubuntu machine for testing and used its suggested Polish region during set up instead of United States.

In fact we encountered and logged several linked issues as a separate tickets and only now their main root cause was pinpointed, such tickets were:

https://github.com/o3de/o3de/issues/7519
https://github.com/o3de/o3de/issues/7717
https://github.com/o3de/o3de/issues/7718
https://github.com/o3de/o3de/issues/9927

While trying to pinpoint what specifically causes https://github.com/o3de/o3de/issues/9927 and why it did not reproduce on the developer machine it was noticed that material names and RGB values have a full stop signs in them which eventually lead to investigating launguage formats.

**Comment by jonatjano** [comment]
also linked to #10987

**Comment by nick-l-o3de** [comment]
FWIW, I have a tenative fix for this, and I'm working to test on windows and then linux.

The tenative fix is to use scoped, thread-local setlocale (which exists on unix platforms, windows, and ios, albeit in different syntax, and calling functions, so it will have to be PAL).   

Then to set that setlocale around any reader/writer or formatter of `%s` that pipes into files, including any calls to `strtod`, `strtold`, `atof`, etc.    I'm not going to apply it to the actual editor applications, though, since we WANT those to localize.  It has to be scoped around data read/write.

* I'll be setting it app-globally to AssetBuilder.exe, since all this is for is data read/write and that will mean it does not have to be something people writing builders have to care about
* I'll be scoping script access (Lua, etc) to include the invariant culture locale ("C"), since lua will crash and have weird problems if it tries to run code with LUA_NUMBERs encoded with comma as decimal.
* I'll be scoping console commands with the invariant culture, because they come from cfg or regset files which themselves should be considered portable data files that ought to work on other people's machines
* RApidJSON already reads and writes in invariant culture, as does a few parts of CryXML, which is why this problem is not widespread.   But ObjectStream does not.  I will fix that.
