### ISSUE TITLE
Bug Report: Unable to switch materials inside of Script Canvas.

### ISSUE THREAD

**Issue by ParasiteSt** [o3de/o3de#11307]
**Describe the bug**
There is no working nodes inside of script canvas that allows you to change the material of a given material slot on a mesh.

**Assets required**

**Steps to reproduce**
1. Go into script canvas after applying a new graph to an entity with a mesh component and at least one material attached.
2. Try to switch the material of the mesh from the default material to another via a node.
3. See error as there is no node that allows you to do such a thing, only switch parameters on the default material, not switch the whole material.

**Expected behavior**
There should be nodes in script canvas to change the material of a mesh entity that work with features in O3DE right now. (not utilizing old tech like the slice system)

**Actual behavior**
The only way to switch a material is in an old slice system asset id, which is no longer usable for o3de in its current or future form.

**Screenshots/Video**
These two nodes should work together without needing the use of Dynamic Slices (another approach is needed as slices are now seeming deprecated)
![image](https://user-images.githubusercontent.com/100494538/184887783-f5a78978-b284-42ba-8ec6-d14fb9c4ff04.png)
When clicking material asset id folder it brings up the Dynamic Slice ui.
![image](https://user-images.githubusercontent.com/100494538/184888043-6d8bb244-aefb-4fbe-ae00-789ca719f379.png)

**Found in Branch**
Development [cf79675]

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 11

**Additional context**
This is more of a blocker as the only other way to get the same end result is with C++, so it blocks any user without the knowledge of C++.

**Comment by ParasiteSt** [comment]
I did not understand the response I got on the O3DE server until the person rephrased it for me, and this is possible to do in LUA and C++, just Script Canvas does not have support as it needs a wrapper to gather the extra info for the materials, and for some reason it started by using Dynamic Slices, and needs to be switched to something like .material assets (if possible).

**Comment by gadams3** [comment]
@lsemp3d @carlitosan @onecent1101 @galibzon @lawsonamzn This problem is not exclusive to the material component. It affects every behavior context bound function, bus, and component that passes around asset IDs. This includes decals, materials, models, actors, UI, scripts, prefab spawning, dynamic vegetation, gradients, image based lighting, and so on.

This is a limitation that needs to be addressed in script canvas and all impacted components.

Script canvas partially implements support for asset IDs. Script canvas will display the asset ID slot on the node and allow the user to select an asset. However, it's hardcoded to treat all asset ID slots as dynamic slice assets because there is no asset type data to feed to the asset picker.

https://github.com/o3de/o3de/blob/development/Gems/ScriptCanvas/Code/Editor/GraphCanvas/DataInterfaces/ScriptCanvasAssetIdDataInterface.h#L68-L77

If script canvas recognized AZ::Data::Asset it could retrieve the asset ID and asset type information.

Several component functions pass around asset IDs and paths for compatibility with lua and Python, which have issues with AZ::Data::Asset. If all of the exposed buses can be updated to use AZ::Data::Asset in addition to making script canvas support it to get the asset ID and type info, then the issue would be resolved for all components.

Some systems like prefab spawning implement a custom wrapper that can be edited in the node inspector. Doing this for all of the affected components and asset types is not a viable option.

**Comment by gadams3** [comment]
Resolved by adding support for setting assets from script canvas nodes and node inspector. Also created a property handler that will allow editing asset IDs in any RPE. For script canvas, the one limitation is that the asset picker will not be filtered to the specific asset type until there is a mechanism to feed the asset type from behavior context to script canvas node.
https://github.com/o3de/o3de/pull/12023
