### ISSUE TITLE
[SMC] Use Python to Create Shader Variant List

### ISSUE THREAD

**Issue by santorac** [o3de/o3de#11380]
**Is your feature request related to a problem? Please describe.**
Shader Management Console (SMC) used to have a python script that would scan all material files to build a list of shader variants. Somewhere along the way, the original python script workflow was somewhat lost, the material scan was moved into C++, and it's run automatically whenever you open a .shader file. Consequently it's unclear what's going on when you open a .shader file, and there is no way to customize the scan.

**Describe the solution you'd like**

1. Move this process back to a python script. (Note that the asset scan should use the asset system's product dependencies to find all downstream materials; this will allow it to pick up indirect references like .fbx files that produce .material files. This should already be the case, this is the way it was done in the original prototype, but it might have changed during the move to C++). The old script still exists but has not been maintained and it likely needs some work to get it going again. See https://github.com/o3de/o3de/blob/development/Gems/Atom/Tools/ShaderManagementConsole/Scripts/GenerateShaderVariantListForMaterials.py 
1. Check to see how performant this process is. At one time, the process of scanning and loading the materials also ended up loading the textures which wasted a lot of time. If it's easy to fix this so texture are not loaded, go ahead and do that. If it's not easy, at least create a new GitHub Issue to track this work.
1. Do not automatically run this process when a .shader file is opened. Instead, prompt the user with a list of available Shader Actions:
    1. If a corresponding .shadervariantlist already exists, they could opt to open that file.
    1. The user may opt to run the default material scan script (GenerateShaderVariantListForMaterials.py).
    1. (The user may opt to run one of the other available python scripts ... but this Shader Action might not be available at this stage, could be covered by a separate ticket, see https://github.com/o3de/o3de/issues/11383).
1. The same Shader Actions could also show up in the asset browser's context menu. (I believe at least some of these context menu items already exist, but I don't know if they have been maintained, they might not work).

**Open Shader Dialog Prompt**
![image](https://user-images.githubusercontent.com/55155825/185489240-57106a6f-6f1c-423e-b486-0465707d1cb2.png)

**Context Menu**
![image](https://user-images.githubusercontent.com/55155825/185487858-02e3f42c-e1cd-4a18-b698-317782483d56.png)

**Describe alternatives you've considered**
There are several other ways users could work with shader variant list files, which can be implemented in addition to this material scan approach, described here: https://github.com/o3de/o3de/wiki/%5BAtom%5D-Shader-Management-Console-(SMC)#shader-management-use-cases

The exact design of the UI could change, especially based on feedback from @o3de/sig-ui-ux

**Comment by gadams3** [comment]
@santorac Here are some notes and recommendations based on how the tools framework operates and work that I've already done that might help simplify some things.

The current shader management console document and view classes are set up assuming that whatever file format it opens will result in an editable shader variant list displayed in a table view. The document class currently supports opening shader and shader variant lists source files. If it's opening a shader file, it automatically does the material and shader asset enumeration to build a shader variant list document from a shader source file. Think of this like being able to open different file formats using a spreadsheet application that all result in an editable spreadsheet, or really any other application that allows you to open multiple source types. 

If part of the goal is to remove the implicit conversion from shader to shader variant source list, you could
-just remove all support for opening shader source files from the document class and leave that for another tool
-or split the document class into two distinct document classes, one that opens shader variant lists and one that opens shader source files
--this will require registering both document classes with the application and creating a new view for raw shader source files.
---I'm not sure what that view would be since the shader source data can be displayed directly in the document RPE.

(An alternative would be introducing another file type to the existing document class that lets provide and configure the script that does the shader option enumeration.)

In order to support both document types
- create hand register a new document type specifically for shader source files
-- the easiest way to do this would be duplicating the existing document class and deleting the unused features from both. 
-- you can register the new class in the shader management console application class
- create and register a new view, or maybe a null view for shader source files (not sure what you would display since there's already the inspector)
- have opening the shader file just open the document, which should not require any additional processing

Recommendations instead of prompting the user when they open a document
- rename the save as child action label to "create or save shader variant list"
- have save as child function save and open the variant list
- use the existing run Python script file menu action to run your scripts
- add specific menu actions to the file menu and asset browser context menu to run specific scripts

I have already exposed pretty much everything to behavior context so it should be accessible through Python. The only thing missing is the product asset enumeration which would ideally be added to atom tools framework utilities. There is a function there for enumerating source asset files. should be registered with the behavior context.

If material crawl is moved outside of shader management console shader variant list document class, I would recommend invoking the scripts separately from the process of opening documents. Like from the file menu, run a Python script, have it crawl the project/gem folders, build all the variant lists, then open whichever documents

**Comment by etherealchain** [comment]
The requirement for this issue

1. Update GenerateShaderVariantListForMaterials.py to do material crawling in python
2. Change the behavior when double-click on a .shader file, make an Open Shader Dialog Prompt
3. Update the context menu to have the same option as Open Shader Dialog Prompt

anything else?

**Comment by gadams3** [comment]
Agreed. When I ported the majority of the scripts to C++, it was part of an operation to create a common framework and workflows for the atom tools that minimized the amount of custom code needed per application. I added a general purpose "Run Python on File..." menu option to asset browser context menu that passes in the selected file as a command line argument. If you search for EditorPythonRunnerRequestBus under o3de\Gems\Atom\Tools\ you will find all of the places that currently support running Python scripts in SMC, ME, MC: file menu, asset browser, command line.

GenerateShaderVariantListForMaterials.py currently processes whatever shader file is passed to the script as a parameter. It opens the shader file as a document in SMC, which automatically converts it to a shader variant list within the application, and asks the user whether they want to save in the project folder or the same folder as the shader file. Ideally, we would remove even that prompt that asks the user where they want to save the file if they can only be saved in two locations.

My recommendation would be turning GenerateShaderVariantListForMaterials.py into multiple scripts that don't require UI or user prompts.

- Create the script that does the crawl and builds the shader variant list for a single file using arguments for the input file path and output dir.
- Create another script that calls the above script and saves in the originating folder
- Create another script that calls the above script and saves in the project folder
- Create additional scripts that can invoke the other scripts for a list of files or a wild card
- Make sure you can invoke both of these from the pre-existing context menu options
- Once those scripts are operational, extend the tools framework to use registry settings to specify a list of dedicated scripts that can be added to the file menu, tools menu, or context menu. Already doing something very similar to this for the open recently used files list.
- Register your discrete scripts with the settings registry so they appear in the designated menus
- This will avoid the need for any user prompting, special UI, and provide generic way of adding other custom scripts to any of the tools.
- Double clicking on a shader file should do one of the following: nothing, auto converting to shader variant list as it currently does, or opening a shader file as its own document type with its own view for editing shader parameters.

**Comment by santorac** [comment]
> I would expect a double-click on .shader file to generate the shader variant list

I do not agree with this point. A user's natural expectation for UI's in general is that double-clicking on a file should simply open that file. The only time a user expects double-clicking to launch some procedure is when the file is an executable or script, and the .shader file is neither of these. I think these are the only appropriate options when the user double-clicks a .shader file...
1. Do nothing
2. Open and display the content of the .shader file
3. Show some kind of prompt that clearly communicates what's going on.

We should not silently launch a procedure that could potentially take minutes to complete.

I think for now, we could just do nothing since that's simplest. We can always add some double-click response in the future if someone wants it.

**Comment by santorac** [comment]
@gadams3 Just a heads up, some of what you are suggesting is covered by this other Issue: https://github.com/o3de/o3de/issues/11383

**Comment by santorac** [comment]
@gadams3 I'm fine with the idea of providing multiple scripts for saving in the different locations. But even if we do that, I still think SMC needs the save-prompt for picking one of the two possible locations. The user should be able to create some data first, and then save it later (or discard it if they want). Normally, an application would prompt the user for a save location when the file is saved the first time, but since the .shadervariantlist is a special circumstance, we can't allow the user to save it wherever they want. (Well I supposed we could allow that, but I think that would just be another "Custom Location" option on the prompt.) 

There is a separate Issue to capture this work: https://github.com/o3de/o3de/issues/11388

**Comment by gadams3** [comment]
Sounds good. I exposed a virtual function to let you override the save file selection behavior in PR mentioned above. You can override it with the popup dialog to select the file location and return the path.

**Comment by etherealchain** [comment]
Update:
I am able to revert GenerateShaderVariantListForMaterials.py and ShaderManagementConsoleRequestBus.h

Now the following flow is working correctly:
1. Right click on a .shader file, "Run Python on File...", select GenerateShaderVariantListForMaterials.py
2. Shader variant list is generated in python
3. The default path of the .shadervariantlist file is used to open a Document
4. The Document will be update with the generated shader variant list, without auto saving or any windows popup 

Now I'm trying to run GenerateShaderVariantListForMaterials.py by clicking "Create Shader Variant List"
From what I understand I can't modify `AtomToolsDocumentApplication::StartCommon` directly, instead I will have to somehow register the script to `ShaderManagementConsoleDocument`? 
I'm still trying to figure out how to do that, and I don't really understand what Guthrie means "registry settings"
```
Once those scripts are operational, extend the tools framework to use registry settings to specify a list of dedicated scripts that can be added to the file menu, tools menu, or context menu. Already doing something very similar to this for the open recently used files list. See AtomToolsDocumentSystem::GetRecentFilePaths, AtomToolsDocumentMainWindow::UpdateRecentFileMenu, and AtomToolsAssetBrowserInteractions::AddContextMenuActionsForSourceEntries.
```

After this is solved I can start to work on #11388
I am working in a fork of o3de/o3de, if its better I can work in fork of aws-lumberyard-dev/o3de, though I am not sure if the work flow will be the same

**Comment by gadams3** [comment]
Good morning. Do you have changes that need to be reviewed? As long as you're able to merge my changes into yours, I can quickly add the hooks to the main menu and asset browser context menu for registering and executing arbitrary scripts listed in the settings registry. That would benefit all the tools. The settings registry is the system that we use throughout the entire engine for configuring and initializing pretty much everything that's not using the legacy user setting system or QSettings. Registry settings are defined throughout the code base in JSON files with the setreg extension.

**Comment by etherealchain** [comment]
I see the changes had been merged to o3de/o3de, I am able to merge it now, thanks!

**Comment by gadams3** [comment]
Set up configurable script menu. You can plug your scripts into the settings registry file provided in the PR once it is submitted.

**Comment by etherealchain** [comment]
We can resolved this issue.

**Comment by santorac** [comment]
Yup, looks good. Even though we didn't make the dialog prompt, it's close enough to the original intent.
