### ISSUE TITLE
Assert is being printed in console after opening the Physics/ScriptCanvas_PostPhysicsUpdate level of AutomatedTesting project

### ISSUE THREAD

**Issue by LB-MateuszSzweda** [o3de/o3de#11709]
**Describe the bug**
Opening the AutomatedTesting project _Physics/ScriptCanvas_PostPhysicsUpdate_ level found in o3de\AutomatedTesting\Levels\Physics directory prints and assert in the console.

This issue also occurs on Linux platform and on the Development (9459742) builds.

For further information please refer to the full assert log found as an attachement.

**Assert**

**File:**
`C:/o3de/Code/Framework/AzCore/AzCore/Serialization/ObjectStream.cpp`
**Condition**
```
(14768) 'void __cdecl AZ::ObjectStreamInternal::ObjectStreamImpl::PreparseOldVersion(class AZ::SerializeContext &,class AZ::SerializeContext::DataElementNode &,class AZ::IO::GenericStream &,const class AZ::SerializeContext::ClassData *)'
(System) - Serialize was parsing old version class and found newer version element! This should be impossible!
```

**Line:** `284`

**Prerequisites**
**AutomatedTesting** project was built is ready to launch.

**Steps to reproduce**

1. Launch the Editor and open the Physics/ScriptCanvas_PostPhysicsUpdate level.

**Expected behavior**
No errors, asserts or warnings are triggered after opening the level.

**Actual behavior**
Opening the level prints an assert into the console.

**Found in Branch**
Stabilization/2210 (d3760da)

**Desktop/Device:**
- Device: PC
- OS: Windows
- Version: 10 Pro
- CPU: AMD Ryzen 9 3900X
- GPU: NVIDIA GeForce RTX 2060 SUPER
- Memory: 16GB

**Additional context**
[PhysicsScriptCanvas_PostPhysicsUpdate Assert.txt](https://github.com/o3de/o3de/files/9470493/PhysicsScriptCanvas_PostPhysicsUpdate.Assert.txt)

**Comment by hultonha** [comment]
Tagging @FuzzyCarterAWS - this indeed seems like a legit issue but if this is coming from a test we intend to remove that it may be simpler to just delete the test than trying to fix the assert. It's possible this is also related to https://github.com/o3de/o3de/issues/11708. Thanks!

**Comment by FuzzyCarterAWS** [comment]
@hultonha Since we don't have a lot of script canvas coverage for the PhysX SC Nodes at this time, I instructed Warsaw to manually run the test levels to check for SC errors. 

These levels however are running on outdated SC Scripts and may need to be updated to run using the **Script Canvas Upgrade** tool found in the SC Editor under **Script Canvas Editor Toolbar → Tools → Upgrade Graphs**.

![image (2)](https://user-images.githubusercontent.com/29718640/189235776-7a127347-05a6-40b2-9871-215a2dd5c577.png)

If the above workflow doesn't work, we may have to use a script noted in #11686.

In the long term, these tests should likely be moved to the GTest Framework.  There's also talk about reviving the **Script Canvas Unit Test** framework where simple node validation tests should be done.  Until one of the above solutions, keeping the SC test levels alive in AutomatedTesting and executed manually during hardening passes/changes to node behaviors should be our goto.

**Comment by hultonha** [comment]
Thanks for the context @FuzzyCarterAWS. Would running the upgrade scripts for these files be something you'd be able to look into. Myself and the Physics team would be happy to support if you run into any issues and we can help approve the PR when it's ready. Thanks!

**Comment by FuzzyCarterAWS** [comment]
@hultonha let's assign the upgrade bugs to me for next week and I'll see if I can resolve them or not with the upgrade paths I've listed. If they fail, the scripts may need to be regenerated from scratch, and may be more effort than they're worth.

**Comment by FuzzyCarterAWS** [comment]
@hultonha this no longer repros. I wonder if this was actually due to the prefab changes that came in for a bunch of test levels.

@LB-MateuszSzweda , does this still repro for you?

**Comment by FuzzyCarterAWS** [comment]
@hultonha closing this as no repro.

**Comment by hultonha** [comment]
Sounds good thanks @FuzzyCarterAWS 👍
