### ISSUE TITLE
UI Editor: UI Canvas on Mesh workflows are non-functional when Terrain level components are present in a level

### ISSUE THREAD

**Issue by jckand-amzn** [o3de/o3de#11749]
**Describe the bug**
UI Canvas on Mesh workflows are non-functional when Terrain level components are present in a level.

**Assets required**
User must create a source .attimage file locally to use as a render target as described in https://www.o3de.org/docs/user-guide/interactivity/user-interface/canvases/canvas-properties/#attachment-image-assets

**Steps to reproduce**
1. Launch the Editor, and create a new or existing level.
2. Open the UI Editor, and create a simple canvas to render to a mesh.
3. With no UI elements selected, set the canvas to Render to Texture, and assign the source .attimage as the Render Target, and then save the canvas.
4. Leave the UI Editor, and create a new entity in the level with a Mesh component (with any valid mesh assigned), Material component, and UI Canvas Asset Ref with the saved canvas assigned and set to Load Automatically.
5. Edit the Mesh's Material Instance, and set the attimage as the Base Color texture.
6. Select the Level entity, and add the Terrain World and Terrain World Renderer components.
7. Observe the Mesh in the world both in/out of Game Mode.

**Expected behavior**
Canvas draws on the mesh in the world.

**Actual behavior**
Blank material draws on the mesh in the world. This persists even if the Terrain World and Terrain World Renderer components are removed from the level until the Editor is restarted.

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/82226555/188214424-38f200e9-e47d-4c80-abc2-4cdf7784821b.png)
![image](https://user-images.githubusercontent.com/82226555/188214464-c3003f74-9668-42cc-a3c6-df7febd777cb.png)

**Found in Branch**
stabilization/2210@ d3760da0ab375a21d67a3be5ecefbedad2440d27

**Desktop/Device:**
 - Device: PC
 - OS: Windows 10 21H1
 - CPU: Ryzen 5950x
 - GPU: Nvidia 2070
 - Memory: 64GB

**Comment by AMZN-daimini** [comment]
This seems like a conflict between the way Terrain and UI Editor use Atom, so looping sig-graphics-audio in for triage.

**Comment by jckand-amzn** [comment]
@mcphedar , can we have someone take a look at this for the stabilization release.

**Comment by AMZN-Dk** [comment]
@galibzon There is no priority set on this ticket, are we still tracking this for fixing for the upcoming release 2210?

**Comment by tonybalandiuk** [comment]
@invertednormal is this being worked on? Is it targeted for the upcoming release?

**Comment by invertednormal** [comment]
@tonybalandiuk I'm looking at this bug today.

**Comment by invertednormal** [comment]
I've spent several hours looking into this today, and I've mostly ruled out terrain having anything to do with the problem. It's likely some deeper bug in how the pipeline or pass system handles things, or possibly how a specific feature processor responds to pipeline changes.

As part of my testing, I disabled the internals of the terrain feature processor so that it doesn't actually do anything, and the bug still happens. So the very act of adding and activating any feature processor seems to cause this behavior. When a feature processor is added, it triggers a pipeline change. This causes `ApplyRenderPipelineChange()` to be called on every feature processor, so any feature processor that does something when that function is called could be to blame.

**Comment by tonybalandiuk** [comment]
Can someone assign a label for the priority?

**Comment by galibzon** [comment]
Reassigned to @michabr. @invertednormal investigated and seems to be a problem of LyShine. @VickyAtAZ can provide support as needed.

**Comment by galibzon** [comment]
@jckand-amzn , does this works if the terrain components are never added?

**Comment by invertednormal** [comment]
@galibzon it does work if the terrain components aren't added, but the mere act of adding any feature processor, or doing anything that could cause feature processors to have ApplyRenderPipelineChange() called on them when switching to game mode would likely break LyShine.

**Comment by invertednormal** [comment]
From my investigations today, I tried disabling `ApplyRenderPipelineChange()` from being triggered by feature processors being added or removed, and when I do that LyShine works with terrain. However, I need to assume that event was added for a reason, and it points more to LyShine not handling `ApplyRenderPipelineChange()` correctly in some way. LyShine uses `ApplyRenderPipelineChange()` to set up all of its custom passes (which is appropriate).

My primary hunch is that having `ApplyRenderPipelineChange()` called in LyShine at the same time as entering game mode is somehow interfering with rendering a canvas to an attachment image. Currently you need to enter game mode to even trigger this behavior, so something else happening while entering game mode might be messing up this operation. For instance, maybe the behavior to trigger the ui canvas render happens first, then the pipeline is blown away and `ApplyRenderPipelineChange` is called to set it up again, and the canvas never actually gets rendered. I'd guess that if LyShine can be fixed so that canvases show up on meshes immediately instead of needing to enter game mode to trigger it, it'd probably also work fine with terrain.

**Comment by jckand-amzn** [comment]
[CanvasOnMeshTest.zip](https://github.com/o3de/o3de/files/9687366/CanvasOnMeshTest.zip)

Adding an example level. This can be unzipped to AutomatedTesting/Levels and should be setup to properly display a canvas on a mesh in the level. If anything seems missing, verify the material instance Base Color texture has been updated to the .attimage in the level folder.

**Comment by tonybalandiuk** [comment]
@invertednormal submitted the fix for this.

**Comment by jckand-amzn** [comment]
Verified fix on stabilization/2210@ 38005c3cac3e266e776350e15b2db8bc56a086aa.
