### ISSUE TITLE
Instantiating and Deleting a prefab requires the user to save the level twice

### ISSUE THREAD

**Issue by srikappa-amzn** [o3de/o3de#11756]
**Describe the bug**
Instantiating and Deleting a prefab requires the user to save the level twice

**Steps to reproduce**
1. Open any level
2. Instantiate a new prefab
3. Hit Ctrl+S or file->save. Notice that the level is still marked dirty
4. Hit Ctrl+S again. Notice that it is saved now.
5. Repeat the same steps but with deleting the prefab instead of instantiating it.

**Expected behavior**
Level gets saved correctly on the first save.

**Actual behavior**
Level is still marked dirty after hitting ctrl+s for the first time.

**Found in Branch**
stabilization/2210 and development

**Comment by jckand-amzn** [comment]
If fix ends up to be too risky for stabilization, we can add a release note for this issue instead.

**Comment by forkercat** [comment]
Did some closer look. Similar to https://github.com/o3de/o3de/issues/11452 (multiple Ctrl+S for create-entity).

For instantiate-prefab workflow, I suggest putting these changes to stabilization and then merge back to development.
1. Add prefab undo cache (I verified this should be enough fix the issue)
2. Add the missing parent DOM update (this is needed as we're removing prefab undo cache and depend on DOM in template)

Note: Although we can merge (1) to stab and (2) to development, I think it would better to do it once to avoid conflict.

For delete workflow, the workflow was reworked in development (https://github.com/o3de/o3de/pull/11699). I verified the issue no longer occurs in development now. For the old workflow in stabilization, I don't think there is a temp fix we can go ahead at this time because it does not know parent entity info during deletion, which is unlike the new workflow.
1. We can either merge the new workflow to stabilization. Or
2. Keep unchanged for this release.

**Comment by forkercat** [comment]
[ Update 9/22 ]

1. For **instantiate-prefab**, verified fixed in both **development** and **stabilization**.
2. For **delete-prefab**, verified fixed in **development** after the rework commit for deletion. But that was before stab cut-off and it is a bit risky to cherry-pick it into stab at this time.
