### ISSUE TITLE
Distracting Entity Reactivation On Transform

### ISSUE THREAD

**Issue by santorac** [o3de/o3de#11841]
**Describe the bug**
It's possible to get into a state where an entity's component(s) quickly deactivate and reactivate after every time you edit it, which causes distracting refreshes both in the UI and in the viewport.

**Assets required**
Tested using the built-in AutomatedTesting project.

**Steps to reproduce**
1. Create a new level.
2. Select the shaderball and click "Add Material Component"
3. Edit the "shaderball_01" material instance, to change the color to green.
4. Duplicate the shaderball entity (for some reason this will not occur with the original entity, you have to make a duplicate something).
5. Change the color of the duplicate shaderball to be red (just for clarity).
6. Move the original shaderball. Nothing special will happen.
7. Move the duplicate shaderball. It will flicker to white for a moment and then back to red. The Entity Inspector will turn gray/disabled for a moment. The Entity Outliner will appear empty for a moment.

**Expected behavior**
The entity should stay activated when moved, and should not flicker.

**Actual behavior**
The entity appears to deactivate and activate again. And it renders for one frame with incorrect material appearance before applying material property overrides.

**Screenshots/Video**
https://user-images.githubusercontent.com/55155825/189246714-da869dcd-0c5f-444b-9755-377a990e7377.mp4

**Found in Branch**
stabilization/2210

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version: 10
 - CPU: AMD Ryzen Threadripper 3970X 32-Core Processor    3.69 GHz
 - GPU: NVIDIA RTX 3070 Ti
 - Memory: 64 GB

**Additional context**

**Comment by lmbr-pip** [comment]
Not sure if this is a graphics issue or a viewport issue, guessing at sig/graphics but please route to SIG/content if viewport.

**Comment by galibzon** [comment]
@gadams3 Is this a Material component problem or a Component Systems problem?

**Comment by gadams3** [comment]
@galibzon @lmbr-pip @monroegm @lsemp3d I believe this has nothing to do with graphics specifically. Changes to prefabs and other types of edits deactivate and reactivate entities. When entities are created, destroyed, deactivated, reactivated they're going to trigger notifications that invalidate and refresh inspectors and the outliner. Sometimes this is unavoidable if reflected pointers or other data is invalidated. Ideally, components will be set up so that they can handle changes without deactivating or reactivating but that will require bulletproofing all of the components and updating editor systems to not forcibly deactivate and reactivate them. If that's not a practical option, perhaps some investigation can be done into minimizing the flicker or preventing UI updates while these things are occurring.
