### ISSUE TITLE
Periodic Failure - development - Windows [benchmark_test_profile]/benchmark_test_profile_results

### ISSUE THREAD

**Issue by shirangj** [o3de/o3de#11937]
### Identified problems:
* **Windows [benchmark_test_profile] - benchmark_test_profile_results**
  * **Log URL**: https://jenkins.build.o3de.org/blue/rest/organizations/jenkins/pipelines/O3DE_periodic-incremental-daily/pipelines/development/runs/99/nodes/1641//log

**Comment by lmbr-pip** [comment]
Closing issue (after consult with SIG/testing). SIG/build automated issue without sufficient information to triage. Expectation is that issue is stale and has probably been replaced with more specific issue.

AR issue creation system has since been improved to get triagable issues that are specific, descriptive and assignable.
