### ISSUE TITLE
Periodic Failure - development - Linux [debug]/debug

### ISSUE THREAD

**Issue by shirangj** [o3de/o3de#11943]
### Identified problems:
* **Linux [debug] - debug**
  * **Log URL**: https://jenkins.build.o3de.org/blue/rest/organizations/jenkins/pipelines/O3DE_periodic-incremental-daily/pipelines/development/runs/99/nodes/727//log
  * **Ninja Build Compilation Failure**
    [2022-09-13T06:32:00.503Z] ninja: build stopped: subcommand failed.

**Comment by spham-amzn** [comment]
This error will be resolved with https://github.com/o3de/o3de/pull/11909

**Comment by lmbr-pip** [comment]
Closing issue (after consult with SIG/testing). SIG/build automated issue without sufficient information to triage. Expectation is that issue is stale and has probably been replaced with more specific issue.

AR issue creation system has since been improved to get triagable issues that are specific, descriptive and assignable.
