### ISSUE TITLE
Feature Request: Draw Order for Opaque Meshes.

### ISSUE THREAD

**Issue by ParasiteSt** [o3de/o3de#12025]
**Is your feature request related to a problem? Please describe.**
If you are trying to create a first person project you will realize that certain meshes that are suppose to always be in your view can clip with meshes in the scene, this has a few solutions, but the best one that would be the most performant is if you would be able to use the sort key on the mesh component to assign the draw order of opaque materials, not just transparent ones.

**Describe the solution you'd like**
The best solution would be to allow the Opaque pass to utilize the Sort Key from the mesh component if it is possible to set what mesh/materials get drawn in what order before depth.

**Describe alternatives you've considered**
An alternative is another toggle in the material itself to draw on top of everything else, which would also be a viable option, but I am not sure how two materials with this toggled on would react together.

**Additional context**
I was looking at the .pass files and see that the TransparentParent.pass has the drawlistsorttype,
![image](https://user-images.githubusercontent.com/100494538/190538826-0ab6c478-26bf-4429-aacf-35b21385e03b.png)

But the OpaqueParent.pass does not,
![image](https://user-images.githubusercontent.com/100494538/190538872-6a71da2f-4b0e-42bf-92ec-f71cf8a19e91.png)

 I tried adding it in, but it was not an easy solution, and if this was to become a feature more would need to be changed.

**Comment by ParasiteSt** [comment]
This is all hypothetical, I have not worked with shaders before, and went purely off of what I could find different between the two passes and shaders. If this is not a possible solution I would love to hear how to get the same end results with another solution in o3de, any help online is based off of other engines, nothing of use for o3de.

**Comment by AMZN-Gene** [comment]
Is it only draw order? Is a different camera field-of-view required too in order to get good looking FPS hands?

**Comment by amzn-tommy** [comment]
Draw order isn't quite enough here. You can draw the (let's assume) gun/hands in any order. Whether it comes first or second, if a wall is also drawn that covers the same pixel, but that wall is closer to the camera than the barrel of the gun, the gun is always going to clip because a depth test will determine that the wall is closer to the camera, and thus the pixels from the wall will win out. Opaque objects use the default DrawListSortType, which is KeyThenDepth. So they are already ordered based on the key first.

There are many ways to approach this, and I'm sure someone who has worked on an FPS can make better suggestions for what works in practice than mine. The simplest thing would be to make a new material type that uses the StandardPbr .azsl files, but has its own .shader file that ignores depth (for the forward pass, but not the shadowmap pass if you want the gun to receive shadows), and then use the Sort Key to draw it last. Or you could have a separate pass for FPS objects with a drawTag used by the material type to force the gun/hands into that pass, which would give you more control. You could also have a separate camera (which would also let you use a different filed of view), which you composite onto the main render using a pass. Or you could have a game-logic based solution that uses a collider to animate the gun and keep it out of the walls. You also have to deal with other things like should particles render on top of or behind the gun? Are there specific particle effects that can occlude the gun, while others can't? What about PostFX?

Since that's more of a project-specific solution, I don't think it belongs in the main O3DE repo, at least not at this stage. But I do think it would make for a nice tutorial that demonstrates how to work with the depth functions in the .shader files and/or the pass system. Then people can pull that into their projects if they want to get up and running quicker.

**Comment by ParasiteSt** [comment]
> But I do think it would make for a nice tutorial that demonstrates how to work with the depth functions in the .shader files and/or the pass system. Then people can pull that into their projects if they want to get up and running quicker.

Even if the actual files are not available, having a tutorial others could follow would allow them to create the file while learning this part of the engine more. Tutorials are lacking right now in a lot of areas of the engine.

**Comment by ParasiteSt** [comment]
> 



> This is what we used on FPS I've worked on in the past. The engine assign a bit-flag to all entities, and the camera component allowed you to select what entity flags it would render.

I heard a lot about this way of doing it, and have done this in the past in Unity, the upside of this way is it would fit nicely in the main o3de repo as a feature, the downside is this sounds like a lot more work to get a working example.

**Comment by ParasiteSt** [comment]
@AMZN-Gene I added a new feature request about Bitflags and camera support, since you definitely have more expertise in this area if you would like to add any notes onto the post here is a link to it. 
https://github.com/o3de/o3de/issues/12834
I honestly think this would be a better way of going about rendering for FPS games, and all the other uses of compositing camera views onto each other, so I am going to close this FR as its really in my opinion a bad way of going about such a feature.
