### ISSUE TITLE
Bug - Prefabs will not report thier world translations in script canvas, when detatched enity will report correctly.

### ISSUE THREAD

**Issue by shawstar** [o3de/o3de#12649]
**Describe the bug**
Prefabs will not report thier world translations in script canvas, when detatched enity will report correctly.

**Steps to reproduce**
1. Go to script canvas and create script as shown in screen shots
2. Click on Play
3.Test a detached Entity with same script.
4. see results

**Expected behavior**
Here is a version of an Entity with no prefab, you can see in the Console a correct translation is reported:
![Non_Prefab_V](https://user-images.githubusercontent.com/87207603/196245163-0894858e-5b9d-432b-bd31-d9b89d31b801.png)

**Actual behavior**
Here is a version using a prefab, notice we do not get a correct translation, but just 0,0,0 vector3
![Prefab_V](https://user-images.githubusercontent.com/87207603/196245439-a2fc6712-3bdf-4c04-b8fc-8d6d8667d738.png)

**Found in Branch**
Nightly 10-17-2022

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 11
 - CPU Intel I9-9900k
 - GPU NVidia RTX 2080tu
 - Memory [e.g. 16GB]

**Additional context**

**Comment by michabr** [comment]
This is because the entity that we're trying to get the transform of may not be activated yet. OnGraphStart is called when the entity that the graph is on is activated, and that may be before or after other entities in the level. Adding an On Entity Activated node to guarantee entity activation before manipulating the entity will fix this issue:

![OnEntityActivatedNode](https://user-images.githubusercontent.com/82236305/196568603-a28a79f2-26c9-4fea-afb2-027953993f4e.jpg)
