### ISSUE TITLE
21 - Create a toggle switch to go back and forth between 1 column and 2 column view

### ISSUE THREAD

**Issue by lsemp3d** [o3de/o3de#12860]
**User Story**

As a user I  need a button in the header of the Asset Browser that will allow me to swap between different view. 2 column view and single column view. This ticket is not about creating the view but just adding the switch between the two views. This is a similar functionality as what is provided in windows explorer in the bottom right corner.

![image](https://user-images.githubusercontent.com/58790905/198412171-78837d61-11e5-4e4e-9380-06531d11bb92.png)

**Comment by MiKom** [comment]
The toggle for the 1-column view (what we call the "tree view") is already there. What's missing is the change of the behavior of the leftmost tree view. In a single-column view it should show both directories and files and in two-column view it should show only directories because in this case it becomes a mere directory browser.

I thus suggest to rename this task to: "Implement directory-only state for the AB treeview when in two-column mode"

**Comment by rainbj** [comment]
@MiKom the image above is missing one additional view

1 column = tree view
2 columns = table view
2 columns = thumbnail view

![Image](https://user-images.githubusercontent.com/82551958/202789595-f9b2d7d1-402b-4ef6-b3b9-3406487aed28.png)

**Comment by rainbj** [comment]
examples - https://www.figma.com/file/TfXXZD1xjlw67MMeRYEbi0/Asset-Browser-Design-Document?node-id=970%3A44261&t=aYqyd3JaMo6qOzJ4-1

**Comment by MiKom** [comment]
@rainbj It's already implemented like that behind the `ed_useWIPAssetBrowserDesign ` cvar:


https://user-images.githubusercontent.com/104767/203134957-e28b44c4-1e68-4e86-841a-e22bb256656a.mp4

(please don't mind the wip breadcrumbs and files being available in the tree in single-column view, these will be tracked in [#13236](https://github.com/o3de/o3de/issues/13236) and [#13309](https://github.com/o3de/o3de/issues/13309) respectively).

**Comment by rainbj** [comment]
@yuyihsu
