### ISSUE TITLE
Wwise setup does not work on installer projects

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#12962]
**Describe the bug**
Wwise setup does not work with the installer projects. Despite included Wwise Environment variables and manually added LY_WWISE_INSTALL_PATH argument the project configured on the Pre-built SDK does not return the "Using Wwise SDK..." line. As a result, a Wwise project setup that works without issues on GitHub projects, does not work on installer (Audio Controls Editor remains blank even after Save All/Reload/Refresh Audio System actions).

**Prerequisites**
* O3DE installer downloaded from: https://o3debinaries.org/download/windows.html or https://o3debinaries.org/development/Latest/Windows/o3de_installer.exe and installed.
* Project built on the O3DE installer - Default Template with Wwise Audio Engine Gem added.
* Wwise project set up on the project with a soundbank, audio file, game parameter and an event added.

**Steps to reproduce**
1. Launch the Editor.
2. Go to Tools > Other > Audio Controls Editor.
3. Attempt to add Wwise project items to ATL Controls.

**Expected behavior**
Wwise can be set up in Editor.

**Actual behavior**
Audio Controls Editor is blank.

**Screenshots/Video**
Windows Environment Variables:
![WwiseEnvrionmentVariables](https://user-images.githubusercontent.com/86952082/199437193-f1c43b60-09f0-42ec-ae48-a7e49ad35693.png)

CMake project configuration with LY_WWISE_INSTALL_PATH argument added manually:
![WwiseProjectCMake](https://user-images.githubusercontent.com/86952082/199437196-fe092e3c-a933-4326-a66f-90535575d7be.png)

https://user-images.githubusercontent.com/86952082/199437199-9c195798-95ed-4315-9be5-7ab07010650f.mp4

**Found in Branch**
O3DE Nightly Development Build (Downloaded 11/2/2022 - https://o3debinaries.org/development/Latest/Windows/o3de_installer.exe) 
O3DE v22.10.0 Release installer

**Desktop**
 - Device: PC
 - OS: Windows
 - Version 11
 - CPU AMD Ryzen 5 3600
 - GPU NVIDIA GeForce RTX 2060 SUPER
 - Memory 16GB

**Comment by LB-ArturZieba** [comment]
I have verified this using the installer ([o3debinaries.org/download/windows.html](http://o3debinaries.org/download/windows.html) > Download v22.10.0 Release) and O3DE Development (6d321b7) clone and Wwise can be successfully set up using these steps.
 However, this method should either be mentioned in the documentation (https://www.o3de.org/docs/user-guide/gems/reference/audio/wwise/audio-engine-wwise/) and/or the user should be prompted about it in the Project Manager/Editor itself.

Ideally, the default Wwise Audio Engine Gem included with the Installer should work without the need to download O3DE source separately, to make the process more user-friendly.

**Comment by amzn-phist** [comment]
Docs should be added, for sure.  I will file a GHI for that.

While I agree that it should be more user friendly without having to download a separate piece, we are somewhat stuck there.  The installer does not contain pre-built binaries for `AudioEngineWwise` because it links to third-party libraries that we don't own, control, or distribute.  So the only recourse is to build it from source as if it were an external Gem.

Maybe it's possible to modify the installer package to include the `AudioEngineWwise` Gem as a source distribution, but the more likely long term possibility is that this Gem would be removed from the core `o3de` repo and moved to a satellite repo like [o3de-extras](https://github.com/o3de/o3de-extras).  If that's the case then this method of configuration would be the "standard" way to enable satellite Gems against an installed engine.  That is, register the Gems as external, enable them to your project, and build those external Gems from source when you build your project.

**Comment by LB-ArturZieba** [comment]
Thanks for the explanation, I think that this issue can be closed, unless it is still required open for tracking or anything else.

**Comment by amzn-phist** [comment]
I've filed the docs ticket and will close this, thank you.

**Comment by AMZN-Gene** [comment]
Im unable to get sound working since the AudioEngineWwise gem was moved to 3rdParty.
The gem is registered, and I have LY_WWISE_INSTALL_PATH set
![image](https://github.com/user-attachments/assets/131d34cf-5e6e-479a-a620-63796953cf97)
