### ISSUE TITLE
Bug Report: Script Canvas Increment/Decrement Visible Counter Bug

### ISSUE THREAD

**Issue by ParasiteSt** [o3de/o3de#13107]
**Describe the bug**
If you Increment the visible counter twice, and try to decrement the visible counter it is locked up and does not decrement it.

**Steps to reproduce**
1. Open Script canvas and create a new graph.
2. Add these nodes : On Graph Start --> Time Delay --> Repeater (2 Repetitions) [Action Pin]--> Increment Visible Counter 
Repeater [Complete Pin] --> Time Delay --> Decrement Visible Counter.
3. See error

**Expected behavior**
When you Decrement the visible counter the cursor should always become invisible, even after calling increment multiple times.

**Actual behavior**
Calling Increment visible counter multiple times without decrementing it will result in decrementing the visible counter to do nothing.

**Screenshots/Video**
Screenshot of test graph that shows error on my build
![image](https://user-images.githubusercontent.com/100494538/201041505-4503d0b4-e328-4555-b12f-4ef9d2dd0421.png)

**Found in Branch**
Development [621a3df]

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 11
 
**Additional context**
This goes both ways, if you Decrement the visible counter twice (or more times) trying to call Increment Visible Counter will result in no changes to be done.

**Comment by AMZN-daimini** [comment]
> Expected behavior
When you Decrement the visible counter the cursor should always become invisible, even after calling increment multiple times.

To be fair, I'm not sure this is correct. The whole point of a `reference counter` would be to keep track of how many times it's called; if different places incremented the counter, and then only one of them decremented it (to signal that they don't need the pointer to be visible anymore), hiding the cursor would result in incorrect behavior (since other systems still need the pointer to be visible).

I wonder if it would mostly be a matter of clarifying the behavior?

**Comment by ParasiteSt** [comment]
@AMZN-daimini The behavior is well informed, I was just told a long while back that these two nodes are meant to toggle the cursor visible and invisible, after talking to Sempe on discord I am going to close this Bug Report as it is not an issue, since like you where saying if I increment twice I should have to decrement twice to set it invisible otherwise I would still have one graph wanting it incremented.
