### ISSUE TITLE
Textured transparent materials become invisible if viewed at certain angles

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#13363]
**Describe the bug**
If a mesh has a transparent textured material and is viewed with another such entity in the background, it can stop being rendered. It should be noted that regular (non-textured) transparent materials do not show this behavior.

Please refer to the attached video for context.

**Steps to reproduce**
1. Go to Tools > Material Editor.
2. Go to File > New Material Document... and click OK in the pop up (do not change the default settings).
3. In the Base Color section assign an image to the Texture property (for example preview.png which should be available in a new project's folder).
4. In the Opacity section set the Opacity Mode to a visible transparent option (for example TintedTransparent or Blended).
5. Save the material.
6. Create a new level.
7. Select the Atom Default Environment > Ground entity and assign the material saved in step 6 to the Default Material property in the Material component.
8. Select the Atom Default Environment > Shader Ball entity, add a Material component to it and assign the material saved in step 6 to the Default Material property in the Material component.
9. Fly around the Shader Ball/Ground entities, so that both are in view and the camera view goes through both of them at once.

**Expected behavior**
Both entities are consistently fully rendered.

**Actual behavior**
At certain angles the Shader Ball can become invisible, wherever its view crosses with the Ground.

**Video**

https://user-images.githubusercontent.com/86952082/203555529-e225e445-9d7b-424b-bb90-78a6d964f356.mp4

**Found in Branch**
Development (7cb2c3f)

**Desktop**
 - Device: PC
 - OS: Linux
 - Version: Ubuntu 20.04.3 LTS
 - CPU AMD Ryzen 5 3600
 - GPU NVIDIA GeForce RTX 2060 SUPER
 - Memory 16GB

**Comment by invertednormal** [comment]
So, transparency is hard. O3de is seeing two transparent objects, and it's drawing them back-to-front in the hopes that everything will look ok. It uses the center point to determine location, and the ground plane's center point is very close to the shader ball. Depending on the location of the main camera and its orientation, the order will swap at different points in time which will not be correct at a per-pixel level.

What's needed for a situation like this is support for order independent transparency which O3de doesn't currently have. Even with support, that's probably something you'd want to specifically turn on because of the costs involved - not every project needs it, and there's often workarounds to avoid transparency sorting issues from coming up.

One workaround you can use for now, is the mesh component has a sort key on it. You can use this to override the rendering order and force the shader ball to render on top of the ground plane.

**Comment by LB-ArturZieba** [comment]
Thanks for the explanation, the workaround you have described with the Mesh Sort Key prevents this from happening (I have changed Shader Ball Sort Key property from 0 to 1). Verified on the Development (bbf6981) build. Feel free to close this issue if it is not needed for further tracking of this behavior.
