### ISSUE TITLE
Material Assignments are not cleared if the material instance has been edited

### ISSUE THREAD

**Issue by amzn-tommy** [o3de/o3de#13685]
**Describe the bug**
![MaterialsDontClearAfterMakingMaterialInstanceOverrides](https://user-images.githubusercontent.com/82672795/207465734-a30d116d-4424-460b-bdbb-b5b3ff568ae2.PNG)

In the above screenshot, the expected behavior would be that the entire sponza model uses the teal ..._joints_mat, because that is the default material and there are not material overrides.

**Assets required**
Sponza from AutomatedTesting

**Steps to reproduce**
1. Open Graphics/Sponza level from the AutomatedTesting project in the editor
2. Inspect the GEO_Sponza entity in the entity editor. Initially, the material component shows an override for each material slot
3. Select the material icon dropdown next to one of the material slots, and choose 'Open Material Instance Editor'
4. Make a change to the base color and save
5. Assign a material to the default material slot
6. One-by-one, clear the material overrides using the 'x' button next to the name of the material assignment
Note: can't remember if I did 5 or 6 first, but either order should have the same end results.

**Expected behavior**
All the sponza meshes start using the material assigned to the default material slot

**Actual behavior**
The material that had a property modified in the material instance editor does not get overridden by the default material.

**Screenshots/Video**

**Found in Branch**
development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
c57ceb986b58cf070e6ff231978466c1450bd69e

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version: 10
 - CPU: Intel I9-10900X
 - GPU: NVidia GeForce RTX 2080 SUPER
 - Memory: 64GB

**Additional context**
There is a workaround - using the material preview drop-down next to the material slot, choose 'Clear material and properties', and then the default material will start being used. I also tried 'Clear Material Instance Overrides', which did not fix the issue.

**Comment by gadams3** [comment]
I tested this in different conditions. Using the sponza level can confuse the issue because it has material overrides in place that look very similar to the materials that come with the FBX by default. This makes it harder to tell if the material overrides have been cleared or not. Clicking the X button in the asset property widget does correctly clear the material asset, if overridden. Clearing the asset does not clear the property overrides, which will still be applied if the assigned material changes. Properties can be cleared from the context menu or the pop up menu from the preview.

What's happening here is that slot has custom properties overridden but not a custom material asset. In that case, the material component applies the property overrides on top of the default material for that slot and does not fall back to the global default material. This behavior was done by design, so that material properties could be customized on an entity, out-of-the-box, without generating the source materials from the product model. We could have an option to specify if we want to use the default material for that slot or the global default.

There are a few problems with the current workflow:
The overloaded use of the word “default” also adds to the confusion. Should have called the global default at the top of the component “fallback” or something like that.
The material component needs additional indicators to inform the user that a slot has property overrides.
Context menu options are documented but not very well advertised as being available on each component.

Another possible solution is to decommission the instance editor in favor of using the material editor, with automatic saving enabled or a remote connection, and employing child materials. This would eliminate the need to add indicators to the material component UI, issues tracking property overrides, the need to serialize material properties with the component, and the redundancy of the material instance editor. Properties could still be overridden from script though

.
