### ISSUE TITLE
On-Demand Reflection isn't generating unique names for AZ::Event<enum>

### ISSUE THREAD

**Issue by mbalfour-amzn** [o3de/o3de#14141]
**Describe the bug**
The RTTI type id generated for AZ::Event<enum> and AZ::Event<> are identical.

**Steps to reproduce**
1. Add the following code to Code\Framework\AzCore\Tests\EventTests.cpp after line 17:
```
    AZ_ENUM_CLASS(TestEnum, Test1, Test2);

    TEST_F(EventTests, DifferentEventHaveDifferentTypeIds)
    {
        auto enumEventId = azrtti_typeid<AZ::Event<TestEnum>>();
        auto enumAndFloatEventId = azrtti_typeid<AZ::Event<TestEnum, float>>();
        auto floatEventId = azrtti_typeid<AZ::Event<float>>();
        auto emptyEventId = azrtti_typeid<AZ::Event<>>();

        EXPECT_NE(floatEventId, emptyEventId);
        EXPECT_NE(enumAndFloatEventId, floatEventId);
        EXPECT_NE(enumAndFloatEventId, emptyEventId);
        EXPECT_NE(enumEventId, enumAndFloatEventId);
        EXPECT_NE(enumEventId, floatEventId);
        EXPECT_NE(enumEventId, emptyEventId);
    }
```

2. Build and run AzCore.Tests. (Use --gtest_filter=EventTests* to get to the result more quickly)

**Expected behavior**
The test succeeds, because each of the types should be unique.

**Actual behavior**
The test fails when comparing enumEventId and emptyEventId.

**Found in Branch**
development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
3c10e112fb4e542100b7c19f8a1c6e33ea6319df

**Comment by lumberyard-employee-dm** [comment]
@mbalfour-amzn 
This is expected due to Enum Types without `AZ_TYPE_INFO_SPECIALIZE` collapsing to use an AZ::TypeInfo UUID value of all 0s.
Furthermore because AzTypeInfo isn't specialized for those enum types, the generic name of "<enum>" is used.

That can be seen in [TypeInfo.h](https://github.com/o3de/o3de/blob/development/Code/Framework/AzCore/AzCore/RTTI/TypeInfo.h#L519-L539)

The solution to this issue is use `AZ_TYPE_INFO_SPECIALIZE` macro to associate a guide with the enum type
```c++
AZ_TYPE_INFO_SPECIALIZE(TestEnum, "{<SomeGuid>}")
```

**Comment by mbalfour-amzn** [comment]
Ah, thanks! I'll put up a PR to add comments next to the AZ_ENUM* macros to make it more clear that they need this secondary step if the enum needs a unique type ID. I mistakenly thought the macros were intended to take care of the specialization under the covers.
