### ISSUE TITLE
Asset Browser: Duplicate/Rename hotkey shortcuts do not function in Thumbnail View

### ISSUE THREAD

**Issue by jckand-amzn** [o3de/o3de#14396]
**Describe the bug**
Duplicate/Rename hotkey shortcuts do not function in Thumbnail View

**Assets required**
[!Important!] Please provide sample assets needed to reproduce the issue, either as an [attachment](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files) or as a link to a public asset in Github.

**Steps to reproduce**
1. Launch the Editor and enable WIP Asset Browser features via the Console:
```
ed_useWIPAssetBrowserDesign true
```
2. Open the Asset Browser, and switch to Thumbnail View if necessary.
3. Select any asset in the Thumbnail View pane.
4. CTRL-D to Duplicate the asset.
5. Press F2 to Rename the asset.

**Expected behavior**
Asset can be duplicated/renamed via hotkey.

**Actual behavior**
Nothing happens.

**Found in Branch**
development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
c8d69fb61c196601651391f4e22d1408971052d8

**Comment by cgalvan** [comment]
Currently the delete, rename, and duplicate actions are only registered on the tree view itself, not the thumbnail view. We should consolidate this functionality so that it operates from the asset browser itself, since the views all share a selection model.

This will be easier to do once the new action manager is enabled by default.

**Comment by jckand-amzn** [comment]
Verified fix on development@ 59049d45d971da6cac7ccaff3b8a738902259f6f.
