### ISSUE TITLE
Atom azshadervariant files aren't ending up in asset bundles

### ISSUE THREAD

**Issue by mbalfour-amzn** [o3de/o3de#14439]
**Describe the bug**
When trying to create asset bundles, only the *_0.azshadervariant files are ending up in asset bundles, not *_1 or *_2.

**Steps to reproduce**
1. Build the AssetBundler.
2. Run the AssetBundler.
3. At the bottom right of the Seeds panel, check "Default Seed Lists".
4. Press "Generate Asset Lists".
5. Save the asset list somewhere.
6. Go to the Asset Lists tab and click on the generated asset list.
7. Look for azshadervariant files.

**Expected behavior**
All of the azshadervariant files should appear there.

**Actual behavior**
Only the _0 variants appear.

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/82224783/217309214-9ffb6be8-dafd-47c3-bbeb-b328fa68d2af.png)

**Found in Branch**
development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
d36b860305d4a501561369c914bd81ef45d9a65a

**Desktop/Device (please complete the following information):**
Windows

**Comment by galibzon** [comment]
The reason that only `*_0.azshadervariant` show up is because they are the only ShaderVariantAsset that are referenced directly by ShaderAssets (`*.azshader`), In turn, PassAsset & MaterialAsset have direct reference to ShaderAssets, and so on up the chain.  
  
`*_[1+].azshadervariant` and `*.azshadervarianttreeasset` are optional and built asynchronously and independently from `*.azshader`. In fact, they have a reverse dependency on ShaderAssets.  This why they are not included by default when using the AssetBundler.  
  
**Solution**:  
 Leverage the concept of "Default Dependencies" as described here: [Default dependencies for O3DE projects](https://www.o3de.org/docs/user-guide/packaging/asset-bundler/default-dependencies/).  
We can use the ShaderManagementConsole to automatically generate/modify these files:  

- Gems\gem_name\Assets\<gem_name>_Dependencies.xml.
- <project_name>\<project_name>_Dependencies.xml

**Comment by galibzon** [comment]
I just had a long conversation with @amzn-mike and figure out a work around the MPS can use:
Create the file `MultiplayerSample/MultiplayerSample_Dependencies.xml` with the following content:  
```xml
<EngineDependencies versionnumber="1.0.0">
    <Dependency path="*.azshadervariant*" optional="false" /> <!-- The wildcard includes azshadervarianttree assets too -->
</EngineDependencies>
```
Remark: The file `MultiplayerSample/MultiplayerSample_Dependencies.xml`, doesn't exist, so it needs to be created.  
  
Ideally the Atom Gem can provide a seed file so shadervariants are included by default in game bundles, but it seems that feature is broken and will follow up with another GHI and assign to @AMZN-stankowi to review.
