### ISSUE TITLE
Asset Browser: 'M' Key Opens Material Editor Instead of Jumping to "M" Folders

### ISSUE THREAD

**Issue by AMZN-Gene** [o3de/o3de#14660]
Typing while in the Asset Browser is used to the quickly find folders. For example, pressing "C" while in the Gem folder will jump to the Camera gem. I went to type 'M' to jump to the Multiplayer folder b instead the material editor opens. This is expected if you're not using the Asset Browser

**Steps to reproduce**
1. Select any sub folder in the Gem folder in the Asset Browser
![image](https://user-images.githubusercontent.com/32776221/219921797-4571c424-3a9d-4b31-9f40-a235cae436c3.png)

3. Press 'C' and notice you jump to the Camera folder
![image](https://user-images.githubusercontent.com/32776221/219921812-65a57a18-7a68-49a9-8e9d-6cef4237ae66.png)

5. Press 'M' to jump to the Multiplayer folder 

**Expected behavior**
Multiplayer gem folder is selected

**Actual behavior**
Material Editor is opened 

**Found in Branch**
Development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
February 18 2023

**Comment by djos06** [comment]
Hi AMZN-Gene,

I saw it is the same problem if you press the T key, it opens the Track view.
Why could not re-affect the M and T shorcuts to ctrl+M and ctrl + T.
I think it would be a nicer solution because it will allows us to open the Material Editor and the Track view even if we are in the asset browser and it will correct this bug btw.
if we disable the availability to open Material editor and Track view when you are on the Asset Browser, it will be hard to understand, for the user, why these windows don't open when you try to open it...

What do you think ?

Nicolas Castillejos

**Comment by djos06** [comment]
> Hi AMZN-Gene,
> 
> 
> 
> I saw it is the same problem if you press the T key, it opens the Track view.
> 
> Why could not re-affect the M and T shorcuts to ctrl+M and ctrl + T.
> 
> I think it would be a nicer solution because it will allows us to open the Material Editor and the Track view even if we are in the asset browser and it will correct this bug btw.
> 
> if we disable the availability to open Material editor and Track view when you are on the Asset Browser, it will be hard to understand, for the user, why these windows don't open when you try to open it...
> 
> 
> 
> What do you think ?
> 
> 
> 
> Nicolas Castillejos

In Fact, this problem is more general, I have tested it and it does not work for many letters. Even with modifying the M shortcut to Ctrl+ M it does not Launchpad the Material editor but it does not go to M lettre in the list...
