### ISSUE TITLE
Linux: ALT key remains pressed after alt-tabbing which changes viewport and camera controls

### ISSUE THREAD

**Issue by LB-KatarzynaDylska** [o3de/o3de#14768]
**Describe the bug**
After alt-tabbing away from the Editor and back, viewport controls behave as if the ALT key is constantly held down. This continues until ALT is pressed and released again. Additionally, if ALT is pressed while the camera is being moved, the camera will stop. If it's moved in a different direction, it will start moving on its own in the direction that was chosen before. This continues until the appropriate directional button is pressed again.
This issue only occurs on Linux.
This issue might be related to https://github.com/o3de/o3de/issues/11969.

**Steps to reproduce**
1. Open any level in the Editor.
2. Alt-tab out of the Editor.
3. Alt-tab back into the Editor.
4. Try to hold left or right mouse button and drag in the viewport.
5. Press ALT.
6. Try to hold left or right mouse button and drag in the viewport.
7. Repeat steps 1-3.
8. Start moving the camera with one of the WASD keys (eg. A).
9. Press ALT.
10. Click a different directional key (eg. D).

**Expected behavior**
Viewport and camera controls work properly after alt-tabbing.

**Actual behavior**
Alt-tabbing changes the behavior of the viewport and camera controls.

**Screenshots/Video**

https://user-images.githubusercontent.com/99388484/220880334-a4c187a3-983a-4ca1-819a-97bf8c30beda.mp4

**Found in Branch**
Development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
https://github.com/o3de/o3de/commit/0dcc79054d5eb1fa71ebe609348e2571bb9b13cc

**Desktop/Device:**
 - Device: PC
 - OS: Ubuntu
 - Version: 20.04.4 LTS
 - CPU: AMD Ryzen 5 3600X
 - GPU: AMD Radeon RX 5700 XT
 - Memory: 16GB

**Comment by nick-l-o3de** [comment]
From what I can tell here debugging (ongoing) the `Code/Framework/AzToolsFramework/AzToolsFramework/Input/QtEventToAzInputMapper.cpp` does indeed get told that the application state changed, and does indeed call `ClearInputChannels`but by the time it does so, the input channel for the alt key is not active, and does not thus update its state or notify.

However, the camera side of things, never got a InputChannelUpdated for it going to "ended" so it thinks alt is still held.  basically, something is moving the input channel state to idle but without going thru QtEventToAzInputMapper when focus is lost or gained.

**Comment by nick-l-o3de** [comment]
I think I figured it out and should have a PR for it soon.  Looks like whats going on here is that the camera is querying the modifier keys on the keyboard input channels, but the modifier keys on those channels are NOT resetting when they should because ClearInputChannels in the QtEventToAzInputMapper is calling UpdateState(false) on the channel.  UpdateState is not virtual, and the keyboard device only updates its modifier key states if you call ProcessRawInputEvent() on it, also non virtual.  So a special case has to be made here to cast it into an InputChannelDigitalWithSharedModifierKeyStates and call ProcessRawInputEvent(false), which will itself update the modifier states AND call UpdateState.
