### ISSUE TITLE
Linux: QtForPython is generating a Trace::Error for the MaterialCanvas_Atom_BasicTests automated test causing a hard lock and test failure.

### ISSUE THREAD

**Issue by jromnoa** [o3de/o3de#14813]
**Describe the bug**
After a thorough investigation in https://github.com/o3de/o3de/issues/14565 the root cause has been determined to be a hard lock. The cause of the hard lock isn't obvious and no useful logs appear for it (it times out from the test code) but there is a `Trace::Error` generated that might be the culprit.

**Assets required**
All AutomatedTesting assets processed with AssetProcessor.

**Steps to reproduce**
1. Have O3DE built for the AutomatedTesting project with all assets processed ahead of time.
2. Open the TestSuite_Main_Null_Render_MaterialCanvas_01.py test file and comment out the pytest.mark.skipif code so that you can run the test without it getting skipped:
```
# Comment this out:
# @pytest.mark.skipif(LINUX, reason="https://github.com/o3de/o3de/issues/14565")
```
3. Launch the MaterialCanvas null render basic automated tests in the main suite on Linux:
```
/home/new_user/git/o3de/python/python.sh -m pytest -vv -s --build-directory="/home/new_user/git/o3de/build/linux/bin/profile" /home/new_user/git/o3de/AutomatedTesting/Gem/PythonTests/Atom/TestSuite_Main_Null_Render_MaterialCanvas_01.py -k MaterialCanvas_Atom_BasicTests
```
4. Result: The test can fail from a time out on Linux (doesn't occur on Windows). There is no logging for the hard lock -> timeout but there is a visible `Trace:Error` in the log output post failure (with every test step also succeeding in the log). Full log attached to ticket.
5. I also tried running this to sort the issue out, but it didn't resolve it:
```
~/git/o3de/python$ ./get_python.sh 
```

**Expected behavior**
MaterialCanvas_Atom_BasicTests passes on Linux.

**Actual behavior**
MaterialCanvas_Atom_BasicTests fails on Linux due to a time out from a hardlock. Root cause of hard lock not clear, but it may be due to this error. Doesn't occur on Windows.

**Screenshots/Video**
None but log attached: [LinuxMaterialCanvasFailure.txt](https://github.com/o3de/o3de/files/10829073/LinuxMaterialCanvasFailure.txt) 

**Found in Branch**
Name of or link to the branch where the issue occurs.

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
development branch @ 71162fde882549daf9b21f68b42dd8a8c0982467

**Desktop/Device (please complete the following information):**
 - Device: Personal g4dn.2xlarge ec2 instance.
 - OS: Linux
 - Version: Ubuntu 20.04.5 LTS
 - CPU: Intel® Xeon(R) Platinum 8259CL CPU @ 2.50GHz × 8 
 - GPU: NVIDIA Corporation TU104GL [Tesla T4]
 - Memory: 31 GB

**Additional context**
We couldn't get a log for the hard lock in https://github.com/o3de/o3de/issues/14565 and this `Trace::Error` is our first guess as to what is causing it.

**Comment by RoddieKieley** [comment]
Looking at the actual log message containing the error in #14565 it indicates the following:

> Unable to load python library libpython3.10.so for Pyside2: libpython3.10.so: cannot open shared object file: No such file or directory

In particular that indicates that it is looking for a Python v3.10 shared object to use for Pyside2 and can't find it. Looking at the above o/s version

> Ubuntu 20.04.5 LTS

We see that the original python version included for 20.04 was 3.8.2 based. As it's an LTS it's unlikely that's been updated, and the [release notes](https://wiki.ubuntu.com/FocalFossa/ReleaseNotes) don't mention anything. However one of the linked python issues in the [20.04.5 change summary](https://wiki.ubuntu.com/FocalFossa/ReleaseNotes/ChangeSummary/20.04.5), [Bug #1873923](https://bugs.launchpad.net/ubuntu/+source/freeradius/+bug/1873923) may indicate a place to start looking.

In comment [#9](https://bugs.launchpad.net/ubuntu/+source/freeradius/+bug/1873923/comments/9) particular it talks about how the version compare is done, and incorrectly so, to see 3.10 as 3.1 and thus less than 3.8. It could be that 3.10 is chosen incorrectly instead of the 3.8 that should be available on 20.04.5.

Either way it requires further investigation to say for sure.

**Comment by byrcolin** [comment]
@spham-amzn Any progress on this?

**Comment by nick-l-o3de** [comment]
I looked at what was going on here, and it looks like a new version of our embedded python was published with the binary name being `libpython3.10.so.1.0`
However, the code is hardcoded to try to open just `libpython3.10.so` instead.  
See https://github.com/o3de/o3de/blob/333c70597628e06e6f2d994700b90637287d4c80/Gems/QtForPython/Code/Source/Platform/Linux/InitializeEmbeddedPyside2.h#L15
I'll post a PR that fixes this file...

**Comment by nick-l-o3de** [comment]
Can someone independently verify that this is fixed now?  It is for me on ubuntu 22.x
