### ISSUE TITLE
Source Material Uses: standardpbr_generated.materialtype

### ISSUE THREAD

**Issue by HogJonny-AMZN** [o3de/o3de#14847]
**Describe the bug**
If you use the Material Component 'Generate/Manage Source Materials', to convert default DCC materials (.azmaterial) into editable source materials (.material), the json data will contain 

`materialType": "@projectroot@/Cache/Intermediate Assets/materials/types/standardpbr_generated.materialtype`

**Steps to reproduce**
1. Create an Entity with a Mesh Component and load a FBX model
2. Click on 'Generate/Manage Source Materials ...'
3. Use the default settings, which will create new materials by converting the default DCC material to editable source materials.

**Expected behavior**
Should be similar results to creating a new material from scratch:
"materialType": `"@gemroot:Atom_Feature_Common@/Assets/Materials/Types/StandardPBR.materialtype"`

**Actual behavior**
The material json data use:
`"materialType": "@projectroot@/Cache/Intermediate Assets/materials/types/standardpbr_generated.materialtype"`

**Screenshots/Video**
If applicable, add screenshots and/or a video to help explain your problem.

**Found in Branch**
development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
96822a9174f91ac075ad762f2ae83180dc0e910e

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Win 11
 - CPU threadripper
 - GPU 3070 Ti
 - Memory 65 GB

**Comment by galibzon** [comment]
@gadams3

**Comment by gadams3** [comment]
@AMZN-stankowi @amzn-mike Hello! I'm not quite sure what to do about this one. This “generates source materials” feature is working backwards, creating editable material source files from model builder generated product assets and telling them to reference the source files for the material type and parent material. In this case, the source file is resolving to the Intermediate instead of the original, which makes complete sense. However, ideally, there should be a way to resolve the original source file.
