### ISSUE TITLE
Material Created With MaterialCanvas Fails To Render Properly In Editor Viewport

### ISSUE THREAD

**Issue by galibzon** [o3de/o3de#15569]
**Describe the bug**
A material created with MC is failing to render properly in the Editor viewport. Interestingly, It loads properly in the MaterialEditor.

 
**Assets required**
This level contains the material. Unzip it under the "Levels" folder of AutomatedTesting project.  
[MaterialHotReloadTest.zip](https://github.com/o3de/o3de/files/11160317/MaterialHotReloadTest.zip)

**Steps to reproduce**
2. Click on '...'
3. Select attached asset '...'
4. Scroll down to '...'
5. See error

**Expected behavior**
This is how the "Ground" plane should look in the Editor viewport:  
![image](https://user-images.githubusercontent.com/66021303/230123413-d927344d-1851-403c-90ce-eafc3ead8e6c.png)

**Actual behavior**
Here is the material applied to the `Ground` plane, but not rendering properly:
![image](https://user-images.githubusercontent.com/66021303/230122827-ca082c00-c246-41e8-8a8c-48bba8711e85.png)

**Screenshots/Video**
Here is the same material loaded in the Material Editor:  
![image](https://user-images.githubusercontent.com/66021303/230123095-7b96ff46-30c9-4605-a551-cc767ae30ebd.png)

**Found in Branch**
`development`:  
commit 3a1423a5cecf928aa256acf1c1f9bdf7ea99814c (HEAD -> development, upstream/development)
Author: galibzon <66021303+galibzon@users.noreply.github.com>
Date:   Wed Apr 5 09:32:30 2023 -0500  

**Desktop/Device (please complete the following information):**
 - Device: PC 
 - OS: Windows
 - Version 10
 - CPU AMD Ryzen Threadripper 3970X 32-Core Processor    3.70 GHz
 - GPU NVidia RTX 3070
 - Memory 128GB
 - 2TB SSD NVMe PCIe4.0 Seagate FireCuda 520 SSD ZP2000GM30002

**Additional context**

**Comment by gadams3** [comment]
After reviewing the issue with the reporter, this is not an issue with material canvas or materials working in the main editor. The materials were working correctly but there were material properties assigned on the material component that overrode properties on the generated materials, making it look as if the materials weren't being updated. The correct fix for this issue is to update the material component to display an indicator on material slots with property overrides. The better fix would be to deprecate the material instance editor and the ability to override properties in the material component. Instead, the user would still be able to override or assign materials and create and edit child materials using the material editor, with trackable assets containing any overrides.
