### ISSUE TITLE
[Bug Report] Asset Browser cannot delete asset

### ISSUE THREAD

**Issue by chanmosq** [o3de/o3de#15671]
**Describe the bug**
I'm unable to delete an asset using the Asset Browser. Specifically, I tried to delete a material and a folder of textures.

**Assets required**
Any assets

**Steps to reproduce**
1. Go to **Asset Browser**
2. Locate an asset and delete it by doing either one of the following:
    - Right-click on an asset to open the context menu and click **Delete asset**
    - Click on an asset and press **Del** key

**Expected behavior**
The asset deletes.

**Actual behavior**
The asset does not delete. As a workaround, I deleted the asset from the file explorer.

**Screenshots/Video**

https://user-images.githubusercontent.com/75444793/231247156-73430cca-7112-4e64-ba47-222d1fc3b9db.mp4

**Found in Branch**
branch: `development`

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
latest commit: `4244bc287a7418c49f4eba569a245b40b9aeda28`

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU [e.g. Intel I9-9900k , Ryzen 5900x, ]
 - GPU [AMD 6800 XT, NVidia RTX 3090]
 - Memory [e.g. 16GB]

**Additional context**

**Comment by guillaumevpayet** [comment]
I have the same issue in 2305.1 on Windows 11.

**Comment by nick-l-o3de** [comment]
This also occurs on linux.

**Comment by lsemp3d** [comment]
So far I have not been able to reproduce this on **Windows** trying to delete textures or materials

https://github.com/o3de/o3de/assets/58790905/1479efad-2af9-408c-b43f-5881a86272a8

**Comment by nick-l-o3de** [comment]
I can repro this with latest on linux. 

What appears to be happening is that the editor sends a request to AssetProcessor to actually perform the operation (move, delete, etc) and it spews perforce errors under default configuration.  I'll see if I can debug.

**Comment by nick-l-o3de** [comment]
OK, can confirm, what's going on here is that AP thinks that P4 is enabled, but its configuration is invalid.  It looks like the source control component only goes into 'offline mode' (like in the editor) if explicitly requested to do so, otherwise, tries hammering at the p4 interface even when credentials or configuration is empty/invalid.

This causes it to return a failure for the call to look up the files, rather than fall thru to the local file system implementation when the configuration is invalid. 

The problem is, the invalid configuration is going to be the case for pretty much everything and everyone who uses the engine normally by default and does not go and intentionally set up perforce.   I think that the best way to handle this would be to either see why the editor knows its in offline mode and replicate that in AP startup, or, see if there's a way to make it automatically be in offline mode UNTIL such a time that the user actually configures it.

**Comment by nick-l-o3de** [comment]
I think I have a solution here to suggest
* If p4 executable is not found at all, show a message and then work _offline_
* if p4 executable is found but not configured at all, so for example, no P4PORT is set, show a message, then work offline
In all other cases, default behavior is to work online and notify about invalid configuration.

The difference between working offline, and online, is that when offline, it won't even try, and passes thru to the local file system.
When online, it will never pass thru to the underlying local file system, even in invalid configuration, instead, it returns errors about invalid configuration.

**Comment by nick-l-o3de** [comment]
OK, I think I have a PR about to be ready to handle this.  What I found was actually a couple of problems, which I will address in a PR
1. AP looks in an old registry (yes, literal windows registry) setting for whether source control is active, and assumes true as the default.  The editor saves it into a regset file under a different key, and has it false by default.
2. No feedback is given when the editor makes a request to delete/move/rename a file and AP cannot do it due to source control
3. The wrong feedback is given when source control has been turned on by the user but the p4 executable is not found, it says the P4PORT is not set.
