### ISSUE TITLE
DPE Inspector: Asset assignment property in components cannot be modified

### ISSUE THREAD

**Issue by michleza** [o3de/o3de#15743]
It appears that most components with an asset property cannot assign or modify it

Repro:
1 - Launch into Editor
2 - Enable the console variable `ed_enableDPE`
3 - Open a new level
4 - Add a new entity to the scene
5 - Add a component to the entity that has an asset/file property such as Mesh or Input
6 - Attempt to change the asset property of the component

Expected behavior:
You can assign a source file to the property

Actual behavior:
The component is missing controls to modify the property

![Image](https://user-images.githubusercontent.com/98843754/232844609-f1120b87-19de-4cb9-b183-231662bd4cd3.png)

**Comment by forkercat** [comment]
The asset reference does not show up for the reflected `AZ::Data::Asset<AssetData>` instance.
- For Lua component, it is [AZ::Data::Asset\<AZ::ScriptAsset> m_scriptAsset](https://sourcegraph.com/github.com/o3de/o3de/-/blob/Code/Framework/AzToolsFramework/AzToolsFramework/ToolsComponents/ScriptEditorComponent.h?L108)
- For mesh component, it is [AZ::Data::Asset\<RPI::ModelAsset> m_modelAsset](https://sourcegraph.com/github.com/o3de/o3de/-/blob/Gems/AtomLyIntegration/CommonFeatures/Code/Source/Mesh/MeshComponentController.h?L46)

The property handlers that handle the asset ref type are defined in [PropertyAssetCtrl.hxx](https://sourcegraph.com/github.com/o3de/o3de/-/blob/Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyAssetCtrl.hxx).

**Why it does not show up in DPE inspector?**

In [DPE code](https://sourcegraph.com/github.com/o3de/o3de/-/blob/Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/DocumentPropertyEditor.cpp?L599) when the view tries to retrieve the handler from `PropertyEditorToolsSystem`, it doesn't match, thus returning an invalid handler id.

Specifically, in [PropertyEditorToolsSystem::GetPropertyHandlerForNode](https://sourcegraph.com/github.com/o3de/o3de/-/blob/Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/PropertyEditorToolsSystem.cpp?L33:77-33:102), it gets the correct handler list. However, the callback `handler->m_shouldHandleNode(node)` is returning false. See [here](https://sourcegraph.com/github.com/o3de/o3de/-/blob/Code/Framework/AzToolsFramework/AzToolsFramework/UI/DocumentPropertyEditor/PropertyEditorToolsSystemInterface.h?L74) where the callback is configured.

The callback would invoke [ShouldHandleNode()](https://sourcegraph.com/github.com/o3de/o3de@73ea5cae2d6f8ca2243e786ac8c0f5414af579c1/-/blob/Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyEditorAPI_Internals.h?L345:21-345:37) that is defined in `PropertyEditorAPI_Internals.h`. In the last line, it calls:

```cpp
return rpeHandler.HandlesType(typeId);  // in this case, typeId is 'Asset'
```

which then invokes the [TypedPropertyHandler_Internal::HandlesType()](https://sourcegraph.com/github.com/o3de/o3de@73ea5cae2d6f8ca2243e786ac8c0f5414af579c1/-/blob/Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyEditorAPI_Internals.h?L550) defined in the same file:

```cpp
virtual bool HandlesType(const AZ::Uuid& id) const override
{
    return GetHandledType() == id;  // id is 'Asset'
}

virtual AZ::TypeId GetHandledType() const override
{
    return AZ::SerializeTypeInfo<PropertyType>::GetUuid();
}
```

Two type ids are different. See the below callstack for more details. The `PropertyType` here is [CReflectedVarGenericProperty](https://sourcegraph.com/github.com/o3de/o3de/-/blob/Code/Editor/Controls/ReflectedPropertyControl/ReflectedVar.h?L348).

![image](https://user-images.githubusercontent.com/11157226/236353086-7f78ea01-f0e5-4f66-afe4-16bdf5443f1a.png)

It is still unclear that why it works for other property types. Maybe it is because for those cases, this [HandlesType()] version is used instead, which always returns true.

**What else I found?**

1. Currently, for the asset instance, it is reflected as `AZ::Edit::UIHandlers::Default` or `0`. Then in 'GetPropertyHandlerForNode()' it would look for the handler in the default list. I tried defining `AZ::Edit::UIHandlers::Asset` and using this instead. Then it doesn't look up from the default list (since the type is specified), but it doesn't resolve the problem.
2. I verified that asset handler registration process is good. It happens in [PropertyManagerComponent::CreateBuiltInHandlers](https://sourcegraph.com/github.com/o3de/o3de/-/blob/Code/Framework/AzToolsFramework/AzToolsFramework/UI/PropertyEditor/PropertyManagerComponent.cpp?L219).
![image](https://user-images.githubusercontent.com/11157226/236354400-486dc3d1-ef8a-4a3f-a765-21501ffefd68.png)
