### ISSUE TITLE
Material Canvas: Changing Model Asset in the Viewport Settings does not update it in the Viewport dropdown

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#15908]
**Describe the bug**
In Material Canvas, if a Viewport *Model Asset* is changed via the *Viewport Settings*, the dropdown in the Viewport with models to select won't be updated. Reverse works as expected - if a *Model Asset* is changed via the Viewport dropdown it will be reflected in the *Viewport Settings*.

This issue occurs on both Windows and Linux.

**Steps to reproduce**
1. Go to *Tools* > *Material Canvas*.
2. In *Material Canvas* go to *Tools* > *Viewport Settings*.
3. Change the *Model Settings* > *Model Asset* to a different .fbx (for example *BeveledCone*).

**Expected behavior**
Dropdown in the *Viewport* updates to the chosen asset.

**Actual behavior**
Dropdown in the *Viewport* does not update, previous model name is still displayed (Shader Ball by default).

**Video**

https://github.com/o3de/o3de/assets/86952082/624aad7f-c5e2-4031-9a58-8f9843024eb2

**Found in Branch**
Development (5a77589)

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
5a7758979551d72f879dc41a152bb86f57d16427

**Desktop**
 - Device: PC
 - OS: Windows
 - Version 11
 - CPU AMD Ryzen 5 3600
 - GPU NVIDIA GeForce RTX 2060 SUPER
 - Memory 16GB

**Comment by gadams3** [comment]
This is working correctly according to the current implementation. Lighting and model presets are their own files. Model preset files reference model assets, with future potential for other settings like offset, scaling, orientation. The name of the model preset is independent of the model it references. Changing the model asset will not change the name of the preset or what appears in the drop down. Multiple presets can point to the same model, which would mainly be useful after the other model preset settings are added. New model presets can be created with unique names from the viewport settings panel.

This may be a case for the viewport settings panel to be updated to display the name of the active model and lighting presets. We could also split viewport settings into its own tool comma a lighting preset editor, since it is shared by multiple applications.

**Comment by LB-ArturZieba** [comment]
Confirming the issue has been closed.
