### ISSUE TITLE
Materials in Quaternius models aren't being applied to the meshes

### ISSUE THREAD

**Issue by jayrulez** [o3de/o3de#15903]
**Describe the bug**
Materials in the Quaternius models don't seem to import properly or aren't being applied to the meshes.

**Assets required**
[Platformer Game Kit - Dec 2021-20230508T024200Z-001.zip](https://github.com/o3de/o3de/files/11424443/Platformer.Game.Kit.-.Dec.2021-20230508T024200Z-001.zip)

**Steps to reproduce**
1. Extract the models to the assets folder
2. Drag a FBX file to the editor viewport
3. Generate the source materials from the Material component

**Expected behavior**
The materials are applied to the mesh

**Actual behavior**
The material aren't applied and a grey mesh is displayed

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/78807/236914829-90e3ff6c-da60-4cd0-a3a5-084056558a84.png)

**Found in Branch**
development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
42a9733b187a5c72616e450a506e91a08d18829b

Desktop/Device (please complete the following information):

Device: Laptop
OS: Windows
Version 11
CPU Intel i7
GPU NVidia RTX 3060
Memory 16 GB

**Comment by gadams3** [comment]
Hello! I downloaded and unzipped the provided content into an existing project. All of the assets processed correctly except for gltf files. I dragged the character model into an existing level. It did appear white and untextured as shown in the screenshots. The material component showed that the model did come with several materials. I was able to generate source materials and open them in the material editor. The problem is that the model does not contain uv coordinates or tangents. I used the FBX settings to add modifiers that generated both and the model appeared correctly with all of the materials applied automatically.
