### ISSUE TITLE
As a gem developer I want a way for O3DE to automatically add my gem dependency targets to RUNTIME_DEPENDENCIES

### ISSUE THREAD

**Issue by AMZN-alexpete** [o3de/o3de#15915]
**Is your feature request related to a problem? Please describe.**
When creating a gem that depends on another gem you need to modify your `gem.json` to include that dependency in the `dependencies` list, but you also need to add `BUILD_DEPENDENCIES` and `RUNTIME_DEPENDENCIES` in your `CMakelists.txt`

If O3DE's cmake provided a function that would automatically added the immediate dependency's targets as `RUNTIME_DEPENDENCIES` it would help developers who forget this step and then wonder why everything is compiling OK, and yet the game or tool crashes because they forgot to add the `RUNTIME_DEPENDENCIES` entry.

**Describe the solution you'd like**
1. a function exists like `o3de_auto_load_dependency_variants(GEM_NAME ${gem_name} VARIANTS Clients Servers Unified Tools Builders)`
2. The above function call is added to DefaultGem template with inline comments documenting what it does and to remove it if the user wants more control over how runtime loading happens.

**Describe alternatives you've considered**
1. better documentation and error checking in cmake or c++
2. better error messages if possible to help developers track down the root cause

**Additional context**
This issue motivated this request: https://github.com/o3de/o3de/issues/15829

**Comment by lumberyard-employee-dm** [comment]
There is some danger with automatically adding load dependencies for a particular gem variant is can causes issues with multiple modules of the from the same gem package.

For example having this functionality supported can cause the AssetProcessor to load multiple gem modules from the same gem.
Examining the LyShine gem, it has both a real LyShine.Tools and a LyShine.Builders CMake target that uses the same cmake file lists
Here is `LyShine.Tools` [cmake file list](https://github.com/o3de/o3de/blob/development/Gems/LyShine/Code/CMakeLists.txt#L112)
Here is `LyShine.Builders` [cmake file list](https://github.com/o3de/o3de/blob/development/Gems/LyShine/Code/CMakeLists.txt#L171)

Both of those modules .dll files cannot load at the same time, as that would cause the Component descriptors within that gem to be registered twice which would cause asserts, but probably would still work.
However what will not work is that it will try to create two copies of the same [LyShineSystemComponent](https://github.com/o3de/o3de/blob/development/Gems/LyShine/Code/Source/LyShineSystemComponent.cpp#L107-L116) which is incompatible with itself.

Both of these modules could be loaded by accident, if a new Gem author specifies an alias from their `.Builders` which depends on the LyShine.Tools target indirectly.

For example if there is a custom gem with the following gem.json and CMakeLists.txt
### gem.json
```json
{
    "gem_name": "MyCustomGem",
    "dependencies": [ "LyShine" ]
}
```

### CMakeLists.txt
```cmake
ly_add_target(
    NAME MyCustomGem.Editor GEM_MODULE
    ...
    BUILD_DEPENDENCIES
        Gem::LyTools.Static
)

ly_create_alias(MyCustomGem.Tools NAMESPACE Gem TARGETS Gem::MyCustomGem.Editor Gem::LyShine.Tools)
ly_create_alias(MyCustomGem.Builders NAMESPACE Gem TARGETS Gem::MyCustomGem.Tools)
```

In the above case the Gem author specifies the `MyCustomGem.Tools` alias has a load time dependency on the `LyShine.Tools` module.
For the Asset processing of their Gem content, the author just re-uses the their `MyCustomGem.Tools` alias by pointing their `MyCustomGem.Builders` alias to it.

Now because the AssetProcessor is set to load `.Builders` alias via [ly_set_gem_variant_to_load](https://github.com/o3de/o3de/blob/development/Code/Tools/AssetProcessor/CMakeLists.txt#L85) it would also attempt to load the `LyShine.Builders.dll` due to the new load dependency checking logic to examine the list of "dependencies" field for a gem and append the gem variant to that dependency. Therefore a load dependency of "LyShine.Builders `module would be added as well.

That would then cause an issue when launching the AssetProcessor

**Comment by AMZN-alexpete** [comment]
> There is some danger with automatically adding load dependencies for a particular gem variant is can causes issues with multiple modules of the from the same gem package.

I agree, automatically adding variants can get us into trouble quick for some existing gems and future gems where developers don't want  this behavior.

What if we make the behavior opt-in, e.g. we add this support by way of a cmake variable or function that we call from the default gem code template, but would not be applied to any existing gems that don't opt in?

**Comment by AMZN-alexpete** [comment]
As discussed, this would be better as an opt-in feature and we can enable it in default code gems so users who are not making complex gem dependencies can benefit from.

Amended request looks like:
1. `o3de_auto_load_dependency_variants(GEM_NAME ${gem_name} VARIANTS Clients Servers Unified Tools Builders)`
2. The above function call is added to DefaultGem template with inline comments documenting what it does and to remove it if the user wants more control over how runtime loading happens.
