### ISSUE TITLE
Installation debian package does not work for ubuntu 22.04

### ISSUE THREAD

**Issue by spham-amzn** [o3de/o3de#15960]
**Describe the bug**
The nightly development Linux debian installer will not install due to the fact that it was built on Ubuntu 20.04, which uses OpenSSL 1.1.1.x for its system OpenSSL library, while Ubuntu 22.04 (and forward) uses OpenSSL 3.x. This issue is not only an issue with Ubuntu, but with other Linux distros depending on the major version of OpenSSL is installed at that system level (generally, they should not have a side-by-side installation of both). 

**Steps to reproduce**
1. Go to https://o3debinaries.org/development/Latest/Linux/O3DE_latest.deb
2. Download to your local Ubuntu 22.04 host
3. Install the package with `dpkg -i` '
4. Launch o3de

**Expected behavior**
The project manager launches successfully

**Actual behavior**
An error is reported indicating missing openssl 
```
/o3de: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
```

**Found in Branch**
Development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
https://github.com/o3de/o3de/commit/1db85409ed279b16fc0bc068bce428a2e7e960a0

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Linux
 - Version Ubuntu 22.04
 - CPU : N/A
 - GPU : N/A
 - Memory : 16 GB

**Comment by julekbr** [comment]
In the release notes from version 2111.2 they're saying they build only on Ubuntu 20 LTS and that other Linux versions might not be supported. Dunno if this info is still up to date, because in the notes of later releases I didn't find any info. I think probably you will either have to use Ubuntu 20 or build it on your own. I built it for Ubuntu 22 but there are problems when trying to open Projects over the Project Manager.

**Comment by lmbr-pip** [comment]
Believe SIG/build owns installer. Please coordinate with SIG/release if a patch is needed.
