### ISSUE TITLE
macOS: Building Development branch build fails due to CompileC Atom_RHI_Metal.Private.Static command

### ISSUE THREAD

**Issue by LB-MateuszSzweda** [o3de/o3de#16121]
**Describe the bug**
CMake fails to build Development branch build on MacBook Pro 2020 and MacBook Air 2020 macOS machines due to the following error:

```
** BUILD FAILED **

The following build commands failed:
	CompileC /Users/macpro/o3de/osx_build/build/Atom_RHI_Metal.Private.Static.build/profile/Objects-normal/x86_64/unity_5_cxx.o /Users/macpro/o3de/osx_build/External/Metal-3b39b0da/Code/CMakeFiles/Atom_RHI_Metal.Private.Static.dir/Unity/unity_5_cxx.cxx normal x86_64 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'Atom_RHI_Metal.Private.Static' from project 'O3DE')
(1 failure)
Elapsed time: 589 s. (time), 0.038932 s. (clock)
```

Please note that this error occurs regardless of selected project and build target.

For further information please refer to the attached screenshot and build log.

**Steps to reproduce**
1. Obtain the Development branch build via GitHub.
2. Create a new or move your preexisting 3rdParty folder containing CMake into the o3de folder.
3. Obtain python packages with the _get_python.sh_ script located in the _o3de/python_ directory.
4. Create the _osx_build_ folder under the o3de location.
5. Set the following temporary environment variables in the Terminal:
```
export PATH=$PATH:/Users/<home_folder_name>/o3de/3rdParty/CMake/CMake.app/Contents/bin
export LY_3RDPARTY_PATH=/Users/<home_folder_name>/o3de/3rdParty
export LY_PACKAGE_SERVER_URLS=https://d2c171ws20a1rv.cloudfront.net
```
6. Configure and generate the Xcode solution with the following command:
`cmake .. -G "Xcode" -DLY_3RDPARTY_PATH=$LY_3RDPARTY_PATH -DLY_UNITY_BUILD=1`

7. Build Mac binaries with the following command:
`cmake -E time cmake --build . --target Editor --config profile`

**Expected behavior**
Building process finishes successfully without errors.

**Actual behavior**
Building fails.

**Screenshots/Video**

<img width="657" alt="Failed AtomRHIMetalPrivateStatic build" src="https://github.com/o3de/o3de/assets/86953456/71895d74-cd6b-4abf-a381-74e903c5dafb">

**Found in Branch**
Development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
6b9331f

**Desktop/Device (please complete the following information):**
- Device: Mac
- OS: macOS
- Version: Ventura 13.0.1
- CPU: M1
- GPU: M1
- Memory: 16GB

**Additional context**

[macOS build log.txt](https://github.com/o3de/o3de/files/11675009/macOS.build.log.txt)

**Comment by GrzesiekO** [comment]
I get exactly the same error with 2305.1 branch.
Editor builds OK. Each project build ends with:
CompileC /Users/macpro/o3de/osx_build/build/Atom_RHI_Metal.Private.Static.build/profile/Objects-normal/x86_64/unity_5_cxx.o /Users/macpro/o3de/osx_build/External/Metal-3b39b0da/Code/CMakeFiles/Atom_RHI_Metal.Private.Static.dir/Unity/unity_5_cxx.cxx normal x86_64 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'Atom_RHI_Metal.Private.Static' from project 'O3DE')

Starting editor without build ends with Asset Processor starting and Editor exiting with segmentation fault:
Process:               Editor [28473]
Path:                  /Users/USER/*/Editor.app/Contents/MacOS/Editor
Identifier:            org.O3DE.Editor
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        o3de [27581]
Responsible:           o3de [27581]
User ID:               1258988814

Date/Time:             2023-10-03 09:13:25.7565 +0200
OS Version:            macOS 13.6 (22G120)
Report Version:        12
Bridge OS Version:     8.0 (21P365)
Anonymous UUID:        F34E6839-5ADC-F7B6-C86F-E95B4ABCFF6B

Sleep/Wake UUID:       1D98DE59-A4EF-4EDC-A2D2-54E7CAA4B81D

Time Awake Since Boot: 4400 seconds
Time Since Wake:       541 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000
Exception Codes:       0x0000000000000001, 0x0000000000000000

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [28473]

**Comment by AMZN-alexpete** [comment]
Possibly related PR https://github.com/o3de/o3de/pull/16849
I was able to launch the stabilization mac editor, but was running from XCode and had the fix above applied which corrects an error with the path to the editor plugins

**Comment by byrcolin** [comment]
no repro, dev builds
