### ISSUE TITLE
DPE Inspector: Image Gradient component's basic functionalities are broken

### ISSUE THREAD

**Issue by LB-KacperKapusta** [o3de/o3de#16242]
**Describe the bug**
If `ed_enableDPE` is enabled, the following issues can be observed within the Image Gradient component:
- "Image Asset" field is not displayed properly and cannot be modified (therefore using "Create New image..." seems not to work as expected)
- "Edit" button is missing from the component even with the asset created/assigned (note that Paint Brush Settings can be now only accessed from the Viewport UI)
- Preview image is not working (preview is always displayed black)

It should be noted that this does not occur on RPE.

Please refer to the attached video for more information.

**Steps to reproduce**
1. Execute the `ed_enableDPE=true` command in the Console.
2. Create a new entity.
3. Add the Image Gradient and the required components to the entity.
4. Use "Create New Image..." option and press "Next".

**Expected behavior**
Image Asset field is updated with the newly created asset and can be modified. "Edit" button appears. Preview is functional.

**Actual behavior**
Image Asset field is not available. "Edit" button does not appear. Preview is not functional.

**Screenshots/Video**

https://github.com/o3de/o3de/assets/86953659/866b268f-821f-4e42-86a2-b2a9746953ad

**Found in Branch**
Development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
https://github.com/o3de/o3de/commit/8e12e7cce641097e0004672bc8b194c1a4900144

**Desktop/Device**
- Device: PC
- OS: Windows
- Version: 11 Pro
- CPU: CPU: Intel Core i7-11700F
- GPU: NVIDIA GeForce RTX 3070
- Memory: 32GB

**Comment by cgalvan** [comment]
Parts 2 and 3 of this issue have been fixed by @AMZN-daimini changes (fixed missing component mode Edit button and resolved instance issue with UIElements that in this case was causing the gradient entity attribute to return the wrong EntityId, so the gradient preview was always showing empty because it was pointing to the wrong EntityId).

The first issue is a separate problem in that we aren't looking at the `Handler` attribute for the handler name on regular data elements, so will need to add logic to handle this case.

**Comment by LB-KacperKapusta** [comment]
Issue verified as fixed in Development (https://github.com/o3de/o3de/commit/e4ed83450be8c899e563e0f4ae87c485c10bff36).
