### ISSUE TITLE
Slice save failure: path case issue

### ISSUE THREAD

**Issue by anon-oss** [o3de/o3de#16309]
**Describe the bug**
UI Slice fails to be saved to disk

**Assets required**
Make a fresh project.

**Steps to reproduce**
1. Go to UI editor and add some ui elements
2. Right click  and select 'make new slice from selection'.
3. Try saving the new ui slice to somewhere in the project folder like asset or UI/Slice

**Expected behavior**
Save the slice from the slice to the selected location

**Actual behavior**
file io tries to save the tempslice to a location which does not exist and thus fails to copy it to the final path. 

**Screenshots/Video**

![slice_save_path_error](https://github.com/o3de/o3de/assets/83772057/3bf4caca-e261-41bf-8c2c-811ba97d711e)

**Found in Branch**
development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
bc68edce8a41a6bcec09461e5255ff6ebf45ea13

**Desktop/Device (please complete the following information):**
 - Device: [PC] 
 - OS: [Linux]
 - Version [fedora 38]
 - CPU [Ryzen 1800x ]
 - GPU [NVidia RTX 3060]
 - Memory [e.g. 32 GB]

**Additional context**
The filepath get converted to lower case letter as seen in the screenshot

**Comment by drakeredwind01** [comment]
could possibly be a build issue (incorrect download location).

**Comment by anon-oss** [comment]
@drakeredwind01

My requested: saved to /media/Projects/GamesName/UI/Slices
Engine: tries to save the tempslice to /media/projects/gamesname/user/ui/slices

Failure: Trying to save to non existing location before copying back to the actual project folder.

Issue: the path gets invalid as the engine is converting the upper case letters to lower.

possible fix in pull request #16310

**Comment by drakeredwind01** [comment]
I'm not sure the upper/lower case is the problem as O3DE wishes to also save it to ".../user/...".
I admit I don't have in-depth knowledge of O3DE but it might allow the all lowercase file path because you have a project set to have multiple users (perhaps changed at some point after initial creation, perhaps not). I'm not 100% sure that the slice will fix this issue.
is there any reason you can think of for the engine to add the file path ".../user/..." to your project?

| wants | paths |
| - | - |
| user requested | /media/Projects/GamesName/UI/Slices |
| O3DE | /media/projects/gamesname/user/ui/slices |

**Comment by anon-oss** [comment]
@drakeredwind01 Thanks a lot for your support and feedbacks! 
This bug is not happening in the development branch with #16310 and so I think I should close it.
