### ISSUE TITLE
Bug Report - Assets outside the project folder are hidden by default, Hide engine folders hides more than engine folders and is on by default

### ISSUE THREAD

**Issue by AMZN-alexpete** [o3de/o3de#16370]
**Describe the bug**
Asset browser hides all folders except the project folder by default AND `Hide engine folders` filter is on by default which is hiding all folders outside the project, which it shouldn't and was supposedly fixed in https://github.com/o3de/o3de/pull/15769/files#top
Related Issue https://github.com/o3de/o3de/issues/15765

The current method for saying what assets to hide by default is too aggressive because it assumes the O3DE Gems and Assets folder do not have commonly used assets for users.  Examples:
1.  All the Atom default materials, skies textures, every sample gem that comes with the engine, all the LyShine examples, scripts, script libraries - all of this is excluded if we ignore the Gems folder inside O3DE.
1. Assets/Editor contains default font, default level prefab
1. Assets/Engine contains default config files, default cube map (unused?), additional fonts, utility Lua scripts, misc default textures and moon texture (old/unused?)
1. Registry contains numerous settings files - we don't currently have an editor for these, but technically these files are combined and shipped with your game, should you be able to find them in the Asset Browser? maybe?

I don't think it ever makes sense to hide the engine Gem's asset folders and I think we should do an asset clean up and move stuff to the correct folders before hiding the remaining "engine" folders that are processed by the AP and contain assets that might be shipped with your game. 

**Steps to reproduce**
1. Open the Editor with the AutomatedTesting project
2. Look at the Asset Browser
3. Toggle the "Hide engine folders" filter on and off

**Expected behavior**
All the available assets INCLUDING the engine assets are visible by default.  
Toggling the "Hide engine folders" only shows/hides the assets in `o3de/Assets/Engine`

**Actual behavior**
Assets from all Gems and the engine are hidden by default because "Hide engine folders" is on by default
Pressing the "Hide engine folders" toggle shows/hides every folder outside the project, not just the engine assets.
Why would you want to not show Gem assets????  Gems are one of the main ways we share assets between projects, we should make it very difficult to accidently hide them!

**Found in Branch**
Dev

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
1b4595b7c20ac1c00ce21ba51c3f1c4e0c9f515f

**Comment by rainbj** [comment]
Please remember this checkmark is a global value (specifically for your project) and looking inside Gems is a secondary use case. Not a primary use case for most customers. I do not agree we should have this off by default. I would say that we could make an exception to the rules here about Gems specifically, so all customers don't have to be overwhelmed by non-useful data in their project.

Instead of adjusting the global toggle and forcing everyone to view non-critical assets.  I would prefer to get more specific about exclusion logic  from this rule and add those items to the filter. IF we think Gem content should show all content inside them. I would be ok with this logic. But please note that users have reported that there" is a lot of junk inside  O3DE that I don't know what I'm suppose to do with". I want to make sure we are finding the middle ground here. Between too much and not enough.

**Comment by rainbj** [comment]
@dtamkin1 Let's chat before finalizing the logic we will be adding here. Thanks
