### ISSUE TITLE
Unable to build on Manjaro Linux due to hard dependency on PkgConfig

### ISSUE THREAD

**Issue by VinnyVicious** [o3de/o3de#16760]
**Describe the bug**
Unable to build on Manjaro Linux due to hard dependency on PkgConfig.

```bash
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
```

Ideally, the build should not depend on PkgConfig, but check for dependencies in the environment, not on packages.

**Comment by drakeredwind01** [comment]
suggest removing `needs-triage` `needs-sig` and adding `triage/accepted`, and `sig-network`.
maybe `sig-build', and 'sig-platform`?

**Comment by lumberyard-employee-dm** [comment]
This is a good first issue to address.
The `FindPackageHandleStandardArgs` module is used by the [Findo3de.cmake](https://github.com/o3de/o3de/blob/development/cmake/Findo3de.cmake#L50-L52) to locate the engine when run in a project-centric.
It technically doesn't need to use that command, as all that needs to be done is to locate the "engine_version" value from the engine.json file

**Comment by VinnyVicious** [comment]
I don't think it is related to that, but actually these:

https://github.com/o3de/o3de/blob/development/cmake/Platform/Linux/libunwind_linux.cmake#L11
https://github.com/o3de/o3de/blob/development/cmake/Platform/Linux/libzstd_linux.cmake#L11

PkgConfig should not be a dependency, since it is distro-specific. Also, why can't those libraries be bundled with the engine? Linking to them dynamically is a nightmare for portability across Linux systems.

**Comment by byrcolin** [comment]
Manjaro is not a supported distro as of yet so we should do not test it on Manjaro. That being said we want to run on as many platforms as possible even if they are not explicitly tested. We have a rule about accepting issues for unofficially supported platforms which is not accept triage but to give it another label which is "Triage/Deferred" so that we can track the issue and hopefully someone from the community that can help get the issue resolved has a place to start. Basically it means we have triaged the issue, have not officially accepted it, we have not declined the issue, we acknowledge the issue and informs the community so that interested members can action it if they choose.

**Comment by VinnyVicious** [comment]
I don't think this is Manjaro-specific, though. Using PkgConfig the way it is currently being used in the build is quite a bad practice and makes porting harder. Ideally the build should try to find those dependencies in the system, and if unable, instead of total failure, build a local vendored copy instead.

Are there any guidelines or best practices documented for O3DE?

**Comment by ericwomer** [comment]
It should be System -> CMake Find Scripts -> then pkg-config

**Comment by fhdk** [comment]
Please see  https://forum.manjaro.org/t/is-something-different-about-manjaros-runpath-handling/159464/18

**Comment by ericwomer** [comment]
> Please see https://forum.manjaro.org/t/is-something-different-about-manjaros-runpath-handling/159464/18

^^ When keeping it real goes wrong.
