### ISSUE TITLE
[Linux] Simulating Cloth leads to the Editor crash

### ISSUE THREAD

**Issue by LB-KacperKapusta** [o3de/o3de#16937]
**Describe the bug**
Enabling Cloth simulation leads to the Editor's silent crash. The issue occurs when using the _Simulate in editor_ toggle, as well as, when attempting to enter the Game Mode with the Cloth asset added in the level. Reproduction rate: 3/4.

Please note that the issue might be related to #16157.

Note that the issue has been reproduced on the following Ubuntu machines:

Machine#1 (branch: Point-Release)
- Version: Ubuntu 22.04.3 LTS
- CPU: CPU: Intel Core i7-11700F
- GPU: NVIDIA GeForce RTX 3070 (using NVIDIA driver metapackage from nvidia-driver-535 (proprietary))

Machine#2 (branch: Development)
- Version: Ubuntu 20.04.6 LTS
- CPU: AMD Ryzen 5 3600
- GPU: NVIDIA GeForce RTX 2060 SUPER (using NVIDIA driver metapackage from nvidia-driver-525 (proprietary))
 
Machine#3 (branch: Point-Release)
- Version: Ubuntu 22.04.3 LTS
- CPU: AMD Ryzen 9 3900X
- GPU: NVIDIA GeForce RTX 2060 SUPER (using NVIDIA driver metapackage from nvidia-driver-525 (proprietary))

The following Ubuntu machine did not reproduce the issue:

Machine#4 (branch: Point-Release)
- Version: Ubuntu 22.04.3 LTS
- CPU AMD Ryzen 5 3600X 6-Core Processor
- GPU AMD Radeon RX 5700 XT

The issue did not reproduce on any Windows machine (neither on the Development nor the Point-Release branch).

Please refer to the attached video for more information. Note that the _error.log_ was not generated.

**Prerequisites**
- Cloth gem enabled for the project under test.

**Steps to reproduce**
1. Launch the Editor.
2. Create an entity with Actor and Cloth components.
3. Assign _chicken.actor_ as _Actor asset_ inside the Actor component.
4. Change _Mesh node_ to _chicken_mohawk_.
5. Toggle "Simulate in editor".

**Expected behavior**
Cloth is simulated without any issues.

**Actual behavior**
Editor crashes upon attempting to simulate cloth on most Ubuntu machines.

**Screenshots/Video**

https://github.com/o3de/o3de/assets/86953659/742abc86-0cdd-491c-aa60-d2be93e65d55

**Found in Branch**
Point-Release/23101
Development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
Point-Release/23101 (https://github.com/o3de/o3de/commit/55aa477c9d6ff2eb0277f9f02a00fa53424b9f7e)
Development (https://github.com/o3de/o3de/commit/c8f19bbe664a89ad92007fb7674cb8c6aa165bd9)

**Desktop/Device**
- Device: PC
- OS: Linux
- Version: Ubuntu 22.04.3 LTS
- CPU: CPU: Intel Core i7-11700F
- GPU: NVIDIA GeForce RTX 3070
- Memory: 32GB

**Additional context:**
[Editor.log](https://github.com/o3de/o3de/files/13069966/Editor.log)

**Comment by byrcolin** [comment]
Adding graphics in case this is GPU/NVIDIA driver specific; The hardware seems to indicate a NVIDIA driver issue. If so, I'm not sure if this is something we can fix because of the the use of the proprietary driver in which case a work around may be the only thing, this is assuming the GPU is even being used for cloth sim. I'm not sure but I thought it was CPU sim by default.

**Comment by RoddieKieley** [comment]
I attempted to reproduce this issue based on a build from the 23.10 tagged source on Fedora 38 with an nVidia A4000 and driver 'version 535.98'. Loading a previously working level with physics simulation, a pong tutorial implementation, and hitting the 'play' button I observe that the Editor hangs, the Editor processes go defunct, and eventually I see my log end as per:

```
.
.
.
==================================================================
AssetProcessorConnection: Trace::Warning
 /wip/src/github.com/o3de/o3de/Code/Framework/AzFramework/AzFramework/Asset/AssetSystemComponent.cpp(693): 'virtual bool AzFramework::AssetSystem::AssetSystemComponent::WaitUntilAssetProcessorConnected(AZStd::chrono::duration<float>)'
AssetProcessorConnection: Network connection attempt failure, Connect returned error AzSockError::eASE_ECONNREFUSED
AssetProcessorConnection: ==================================================================
AssetSystem: Ping time to asset processor: 0.49 milliseconds
Editor: Connected to Asset Processor
AssetSystem: Ping time to asset processor: 0.53 milliseconds
Editor: CriticalAssetsCompiled
AssetCatalog: Initializing asset catalog with root "/wip/Projects/np-76ff7aec2-0/Cache/linux"AssetCatalog: Loaded registry containing 9158 assets.
Module: Attempting to load module:/wip/Projects/np-76ff7aec2-0/cmake-build-debug/bin/debug/libCrySystem.so
Module: Success!

Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

```
While the cloth simulation aspect may be missing the hardware driver is one of the reported versions, and a similar behaviour is observed.

In further testing by simply loading the same level and hitting simulate instead of Play, I observe the same behaviour. The Editor becomes unresponsive, the processes are defunct, and the same logging as above is seen where it goes from 'Module: Success!' directly to 'Process finished with exit code 139...'

This was a debug build, but simply run and not debugged yet at this point.

**Comment by RoddieKieley** [comment]
Stacktrace from debugger after hitting the simulate button and observing the above described behaviour:
![Screenshot from 2023-10-27 15-53-02](https://github.com/o3de/o3de/assets/980979/a5231dfd-45d2-481e-8a65-9aa592f4bfe9)

**Comment by nick-l-o3de** [comment]
please retest - I believe this is fixed but it might be a memory shuffle phantom fix.
