### ISSUE TITLE
Renamed gem name in gem.json has linker errors in monolithic release builds

### ISSUE THREAD

**Issue by AMZN-alexpete** [o3de/o3de#17034]
**Describe the bug**
If you copy a gem and rename it in gem.json (e.g. AudioEngineWwise -> AudioEngineWwiseExtra) you will get linker errors about a missing module when building in release mode.

The goal is to be able to include a gem in your project's folder but rename it so that it doesn't collide with any registered gems that have the same name.  This is useful when making minor edits to a gem, or including a gem in your project so users don't have to download it separately.

A workaround to this issue is to change the `version` field in `gem.json` and then specify in your `project.json` that you want your project to use that exact version using the format `<gem name>==<version>`

**Assets required**
An o3de project to modfiy

**Steps to reproduce**
1. Copy the `AudioEngineWwise` gem into your project path
2. Edit your project.json and add `AudioEngineWwise` as an external_subdir and rename `AudioEngineWwise` in `gem_names` to `AudioEngineWwiseExtra`
3. Edit the `gem.json` in `AudioEngineWwise` folder inside your project and change the name to `AudioEngineWwiseExtra`
4. configure and build a monolithic release game launcher
5. See error

**Expected behavior**
configure and build succeeds

**Actual behavior**
build fails with missing symbols error looking for the old gem module name

**Found in Branch**
dev

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
735a539283600acb666292dc6415de2d26229189

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10

**Comment by lumberyard-employee-dm** [comment]
This is due to the name of the Gem module in the [AZ_DECLARE_MODULE_CLASS](https://github.com/o3de/o3de/blob/development/Gems/AudioEngineWwise/Code/Source/AudioEngineWwiseModule.cpp#L58-L61) macro for a Gem.

The code that generates the [StaticModules.inl](https://github.com/o3de/o3de/blob/development/Code/LauncherUnified/launcher_generator.cmake#L343-L344) file which gets linked into the Monolithic launcher uses the name of the gem to try to find the externed function needed to create the AZ::Module derived class.

So the code is looking for a `CreateModuleClass_Gem_AudioEngineWwiseExtra` function, but the only function available is `CreateModuleClass_Gem_AudioEngineWwise`.


My preliminary thoughts on a solution is to be able to somehow update the Module source file that contains [AZ_DECLARE_MODULE_CLASS](https://github.com/o3de/o3de/blob/development/Templates/DefaultProject/Template/Gem/Source/%24%7BName%7DModule.cpp#L48) macro to somehow read the gem name from the Gem.json at preprocessor time and use that instead for name of the externed "C" module class function
