### ISSUE TITLE
RHI: [Android] [Vulkan] If validation is enabled, errors may be reported

### ISSUE THREAD

**Issue by mcphedar** [o3de/o3de#1737]
- Incorrect Sample Count for image
- Shader struct not aligned 
- Queue family flag
- Query Pool Pipeline Statistics Validation Error- 
- Compute Shader workgroup too large

**Comment by superkitcath** [comment]
@AMZN-tpeng, is this a critical? Thanks!

**Comment by moraaar** [comment]
With the latest from development (https://github.com/o3de/o3de/commit/f1d46fc8f7626f5bcac919013d3ebde3d8551e40) I just run a default level using vulkan rhi on PC with validation enabled and I don't get the validation errors listed here (I get others which I'll open GHIs for).

Closing this since it doesn't provide much information.

**Comment by moraaar** [comment]
Individual GHIs have been creating for Vulkan validation errors on Android which provide more information that this ticket. Closing this.
