### ISSUE TITLE
Script Canvas: If Developer Gem Is Enabled on Launch the Project Editor Shows "Modules Entities Cannot Be Activated"

### ISSUE THREAD

**Issue by G13D** [o3de/o3de#17572]
**Describe the bug**
Module Manager:
Modules Entities cannot be activated.

Multiple 'AudioSystemComponent' found, but this component is incompatible with others of the same type.

A component is incompatible with a service provided by another component.
Check that the component's service functions ['GetProvidedServices','GetIncompatibleServices' etc] are accurate.

**Steps to reproduce**
1. Enable Script Canvas Developer Gem on Project
2. Build Project
3. Click On Open Editor

**Expected behavior**
Editor is Opening Successfully

**Actual behavior**
A Project has the Gem enabled Shows Errors On Opening The Editor

**Screenshots/Video**
![ModuleManagerScreenshot](https://github.com/o3de/o3de/assets/58872135/25737671-7579-4469-b637-301ea321566b)

**Found in Branch**
Nightly Development Build

 - OS: [ Windows ]
 - Version [ 10 ]

**Additional context**
The Module Manager On Different Projects Show Different text Lmbr Central System Components ...

**Comment by lumberyard-employee-dm** [comment]
This like an issue with the ScriptCanvas Developer Gem is enabling the Game version of the LmbrCentral Gem in the Editor alongside the Editor Version of the LmbrCentral Gem causing a conflict.
Only the Editor version of the LmbrCentral Gem should be enabled in the Editor.

**Comment by nick-l-o3de** [comment]
this was active in stabilization.  Turns out that Script Canvas developer editor module depends on ImGui NON-editor module and that in turn depends on LmbrCentral NON-editor module.    This causes all the otehr gems to bring in LmbrCentral.Editor but Script Canvas Developer to bring in LmbrCentral (base) which conflict.


To fix this, editor modules should depend on editor modules - so SCD needs to depend on ImGui.Tools instead of  just ImGui.

**Comment by nick-l-o3de** [comment]
This is fixed in the release and dev, now.
