### ISSUE TITLE
Cannot run ExpandOptionsFullCombinatorial.py on Linux

### ISSUE THREAD

**Issue by zakmat** [o3de/o3de#17692]
**Describe the bug**
I would like to adjust system options for my shader variant lists using provided UI. I can generate a shader variant list from my shader, but an attempt to run ExpandOptionsFullCombinatorial.py fails. I use `standardpbr_mainpipeline_forwardpass_standardlighting.shader` as an example, but the same error happens for the other shaders as well.

**Assets required**
[!Important!] Please provide sample assets needed to reproduce the issue, either as an [attachment](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files) or as a link to a public asset in Github.

**Steps to reproduce**
1. Build the project including ShaderManagementConsole
1. Add the current directory to LD_LIBRARY_PATH (without it ShaderManagementConsole fails to generate shader variant list) and start the tool.
2. Select shader and run CreateShaderVariantListDocumentFromShader.py for it.
3. Save the variant list in the project.
4. Right-click on a row and select Python Scripts -> ExpandOptionsFullCombinatorial.py
5. See the following error in PythonTerminal:
```
==== Begin shader variant expand option combinatorials script ====
CB163070-0DAE-4945-BB4C-9C55B52E32C7
{CB163070-0DAE-4945-BB4C-9C55B52E32C7}
getting options for uuid {CB163070-0DAE-4945-BB4C-9C55B52E32C7}
Traceback (most recent call last):
  File "/home/mzak/projects/engine/o3de/Gems/Atom/Tools/ShaderManagementConsole/Scripts/ExpandOptionsFullCombinatorials.py", line 596, in <module>
    main()
  File "/home/mzak/projects/engine/o3de/Gems/Atom/Tools/ShaderManagementConsole/Scripts/ExpandOptionsFullCombinatorials.py", line 536, in main
    optionDescriptors = [None] * optionCount
TypeError: can't multiply sequence by non-int of type 'NoneType'
Detected script failure in Python script(/home/mzak/projects/engine/o3de/Gems/Atom/Tools/ShaderManagementConsole/Scripts/ExpandOptionsFullCombinatorials.py); return code -1!
```

**Expected behavior**
I expected to see a window to select and manage system shader options.

**Actual behavior**
I see error in the Python Terminal, no new window is displayed.

**Screenshots/Video**
If applicable, add screenshots and/or a video to help explain your problem.

**Found in Branch**
development

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) Repository**
629bdba50a

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Linux Ubuntu
 - Version 22.04
 - CPU Intel I7-12700H
 - GPU NVidia RTX 3070 Mobile
 - Memory 32GiB

**Additional context**
I have seen a video with that option working on Windows. I believe it might be Linux-specific.

**Comment by lemonade-dm** [comment]
The logic to check if the `GetShaderOptionDescriptorCount` event from the ShaderManagementConsoleBus should check if the optionCount is not None, as the Bus handler might not be connected when running the script.
https://github.com/o3de/o3de/blob/d7461304fac3df8af4aa1d3d0965946a1ac2776e/Gems/Atom/Tools/ShaderManagementConsole/Scripts/ExpandOptionsFullCombinatorials.py#L530-L532

Looking at the ShaderManagementConsoleDocument, there must not be an instance of it running as the EBus handler for it is not connected.

Otherwise the logic would always return an integer
https://github.com/o3de/o3de/blob/0f955467d86dc5eb1a83002f8835ffebf2fab598/Gems/Atom/Tools/ShaderManagementConsole/Code/Source/Document/ShaderManagementConsoleDocument.cpp#L391-L40

**Comment by spham-amzn** [comment]
> The logic to check if the `GetShaderOptionDescriptorCount` event from the ShaderManagementConsoleBus should check if the optionCount is not None, as the Bus handler might not be connected when running the script.
> 
> https://github.com/o3de/o3de/blob/d7461304fac3df8af4aa1d3d0965946a1ac2776e/Gems/Atom/Tools/ShaderManagementConsole/Scripts/ExpandOptionsFullCombinatorials.py#L530-L532
> 
> Looking at the ShaderManagementConsoleDocument, there must not be an instance of it running as the EBus handler for it is not connected.
> 
> Otherwise the logic would always return an integer https://github.com/o3de/o3de/blob/0f955467d86dc5eb1a83002f8835ffebf2fab598/Gems/Atom/Tools/ShaderManagementConsole/Code/Source/Document/ShaderManagementConsoleDocument.cpp#L391-L40

It turns out that bus call to the [ShaderManagementConsoleDocumentRequestBus](https://github.com/o3de/o3de/blob/5e7b0991120d7d422dc4b83e90b0aa35997ff41d/Gems/Atom/Tools/ShaderManagementConsole/Scripts/ExpandOptionsFullCombinatorials.py#L526-L528) with the input [document id](https://github.com/o3de/o3de/blob/5e7b0991120d7d422dc4b83e90b0aa35997ff41d/Gems/Atom/Tools/ShaderManagementConsole/Scripts/ExpandOptionsFullCombinatorials.py#L517) fails to resolve handler for that document id. 

What is strange is that this does not occur with the same bus in [CreateShaderVariantListDocumentFromShader](https://github.com/o3de/o3de/blob/5e7b0991120d7d422dc4b83e90b0aa35997ff41d/Gems/Atom/Tools/ShaderManagementConsole/Scripts/CreateShaderVariantListDocumentFromShader.py#L34-L39). When this script is invoked, the document is created and connected to the bus id with the new document id. But with the result ShaderVariantList, right clicking on a row in the variant list, trying to invoke the [GetShaderOptionDescriptorCount](https://github.com/o3de/o3de/blob/5e7b0991120d7d422dc4b83e90b0aa35997ff41d/Gems/Atom/Tools/ShaderManagementConsole/Scripts/ExpandOptionsFullCombinatorials.py#L526-L528) fails to locate the same document id that was connected previously.

**Comment by spham-amzn** [comment]
Figured out the root cause, described in the [PR](https://github.com/o3de/o3de/pull/17753) to fix it
