### ISSUE TITLE
Rendering Crash Viewing Character Mesh

### ISSUE THREAD

**Issue by AMZN-Gene** [o3de/o3de#18099]
I get 2 rendering related crashes when attempting to view the simple Mixamo YBot
https://www.mixamo.com/#/?page=1&query=y&type=Character

**Steps to reproduce**
1. Open an empty level and add a character (example: YBot)
[ybot.zip](https://github.com/user-attachments/files/16146499/ybot.zip)

**Expected behavior**
Level doesn't crash

**Actual behavior**
I receive 1 of 2 callstacks.
**1) Device Lost**
```
Atom_RPI.Editor.dll!AZ::RPI::RPISystemComponent::OnDeviceRemoved(AZ::RHI::Device * device) Line 205	C++
[Inline Frame] Atom_RHI_DX12.Private.dll!AZStd::Internal::INVOKE(void(AZ::RHI::RHISystemNotificiationInterface::*)(AZ::RHI::Device *) &) Line 177	C++
[Inline Frame] Atom_RHI_DX12.Private.dll!AZStd::invoke(void(AZ::RHI::RHISystemNotificiationInterface::*)(AZ::RHI::Device *) &) Line 54	C++
[Inline Frame] Atom_RHI_DX12.Private.dll!AZ::EBusEventProcessingPolicy::Call(void(AZ::RHI::RHISystemNotificiationInterface::*)(AZ::RHI::Device *) &) Line 437	C++
 	Atom_RHI_DX12.Private.dll!AZ::Internal::EBusContainer<AZ::RHI::RHISystemNotificiationInterface,AZ::RHI::RHISystemNotificiationInterface,0,1>::Dispatcher<AZ::EBus<AZ::RHI::RHISystemNotificiationInterface,AZ::RHI::RHISystemNotificiationInterface>>::Broadcast<void (__cdecl AZ::RHI::RHISystemNotificiationInterface::*)(AZ::RHI::Device *),AZ::RHI::Device *>(void(AZ::RHI::RHISystemNotificiationInterface::*)(AZ::RHI::Device *) && func, AZ::RHI::Device * && <args_0>) Line 1360	C++
Atom_RHI_DX12.Private.dll!AZ::RHI::Device::SetDeviceRemoved() Line 124	C++
Atom_RHI_DX12.Private.dll!AZ::DX12::Device::OnDeviceRemoved() Line 754	C++
```
Log Output
```
D3D12: Removing Device.
(Device) - Device was removed because of the following reason:

(DX12) - DXGI_ERROR_DEVICE_HUNG - The application's device failed due to badly formed commands sent by the application. This is an design-time issue that should be investigated and fixed.

(Device) - Could not retrieve DRED bread crumbs (auto-breadcrumbs not enabled): DXGI_ERROR_UNSUPPORTED

(Device) -  ===========================End of OnDeviceRemoved================================
```
**2) Shader Resource Group**
```
>	Atom_RHI_DX12.Private.dll!AZ::DX12::ShaderResourceGroupPool::CompileGroupInternal(AZ::RHI::DeviceShaderResourceGroup & groupBase, const AZ::RHI::DeviceShaderResourceGroupData & groupData) Line 209	C++
 	Atom_RPI.Editor.dll!AZ::RHI::DeviceShaderResourceGroupPool::CompileGroup(AZ::RHI::DeviceShaderResourceGroup & shaderResourceGroup, const AZ::RHI::DeviceShaderResourceGroupData & shaderResourceGroupData) Line 351	C++
 	Atom_RPI.Editor.dll!AZ::RHI::DeviceShaderResourceGroupPool::CompileGroupsForInterval(AZ::RHI::Interval interval) Line 370	C++
 	[Inline Frame] Atom_RPI.Editor.dll!AZ::RHI::FrameScheduler::CompileShaderResourceGroups::__l19::<lambda_3>::()::__l5::<lambda_1>::operator()() Line 391	C++
 	[Inline Frame] Atom_RPI.Editor.dll!AZ::JobFunction<``AZ::RHI::FrameScheduler::CompileShaderResourceGroups'::`19'::<lambda_3>::operator()'::`5'::<lambda_1>>::ArgHelper<``AZ::RHI::FrameScheduler::CompileShaderResourceGroups'::`19'::<lambda_3>::operator()'::`5'::<lambda_1>,0>::Process(AZ::RHI::FrameScheduler::CompileShaderResourceGroups::__l19::<lambda_3>::()::__l5::<lambda_1> &) Line 70	C++
 	Atom_RPI.Editor.dll!AZ::JobFunction<``AZ::RHI::FrameScheduler::CompileShaderResourceGroups'::`19'::<lambda_3>::operator()'::`5'::<lambda_1>>::Process() Line 42	C++
 	EditorLib.dll!AZ::Internal::JobManagerBase::Process(AZ::Job * job) Line 31	C++
 	EditorLib.dll!AZ::Internal::JobManagerWorkStealing::ProcessJobsInternal(AZ::Internal::JobManagerWorkStealing::ThreadInfo * info, AZ::Job * suspendedJob, std::atomic<bool> * notifyFlag) Line 421	C++
```

**Found in Branch**
development
July 4th commit c7fb2ee2d08841ee4a40cb94c87373782a6eaf3e

**Desktop/Device:**
 - Device: PC
 - OS: Windows 11
 - GPU NVidia RTX 3070 Ti

**Comment by gadams3** [comment]
Multiplayer sample and other projects experiencing device failure immediately upon loading levels in the editor. After enabling #define AZ_FORCE_CPU_GPU_INSYNC, the following output revealed that the issue was happening in the after the ray tracing acceleration structure pass.

D3D12: Removing Device.
Exception thrown at 0x00007FFD40B6FABC in Editor.exe: Microsoft C++ exception: _com_error at memory location 0x000000C3141A9268.
Exception thrown at 0x00007FFD40B6FABC in Editor.exe: Microsoft C++ exception: _com_error at memory location 0x000000C3141A9478.
<17:05:30> (Device) - The last executing pass before device removal was: Root.MainPipeline_0.RayTracingAccelerationStructurePass

<17:05:30> (Device) - Device was removed because of the following reason:

<17:05:30> (DX12) - DXGI_ERROR_DEVICE_HUNG - The application's device failed due to badly formed commands sent by the application. This is an design-time issue that should be investigated and fixed.

<17:05:30> (Device) - Could not retrieve DRED bread crumbs (auto-breadcrumbs not enabled): DXGI_ERROR_UNSUPPORTED

<17:05:30> (Device) -  ===========================End of OnDeviceRemoved================================

'Editor.exe' (Win32): Loaded 'C:\Windows\System32\TextShaping.dll'. Symbol loading disabled by Include/Exclude setting.
The thread 21028 has exited with code 0 (0x0).
The thread 34340 has exited with code 0 (0x0).
The thread 25180 has exited with code 0 (0x0).
