### ISSUE TITLE
shadow color error

### ISSUE THREAD

**Issue by flyskyosg** [o3de/o3de#18395]
I am using o3de version 2409. I found that the shadow color in the default scene of this version is a bit blue, not completely black, and the color depth cannot be modified. Is it a problem with my usage or other issues?
Thank you

![image](https://github.com/user-attachments/assets/a9af014d-99fd-48cf-a27c-bea8a5fc39fd)
[](url)

**Comment by dKumin8** [comment]
Hi, I think your shadow color is a bit blue because there is a Global Skylight (IBL) on the level.
Global Skylight (IBL) is enabled:
![image](https://github.com/user-attachments/assets/c2ea8364-a297-4360-b3aa-f2bd9777d0b5)
Global Skylight (IBL) is disabled:
![image](https://github.com/user-attachments/assets/ae76ccec-2052-4d87-82a9-ef579abb1159)

**Comment by flyskyosg** [comment]
I apologize for the delayed response. The method you suggested is indeed effective. Are there any reputable sources for downloadable IBL resources? Additionally, is it possible to adjust the color deep blend ratio of the shadow? 
Thank you.
