### ISSUE TITLE
Rename file extension used for shaders to be something else

### ISSUE THREAD

**Issue by aaronfranke** [o3de/o3de#1883]
### Summary:

The shader file format in O3DE is currently `.shader`. I propose renaming it to something else. This is a fairly simple feature so I will keep this RFC fairly short.

### What is the relevance of this feature?

`.shader` is a very generic name.

* Ideally `.shader` shouldn't be attributed to one particular engine since it's a generic word. However, in practice, some tools assume `.shader` files are Unity shaders.

* It's a good idea to be specific of what the file format is so that third-party tools can detect it's from O3DE, what language it is, what program should be used to open it, what kind of syntax highlighting to give it, etc.

### Feature design description:

https://o3de.org/docs/atom-guide/look-dev/shaders/shader-file-spec/

The shader format documented here would be given an alternative file extension to the current `.shader`. Moving forward, this new extension would be the primary option and the one used when saving new shader files, but it makes sense for O3DE to keep reading existing `.shader` files for compatibility.

### What are the advantages of the feature?

Better detection of this file format in third-party tools so that they can detect it's from O3DE, what language it is, what program should be used to open it, what kind of syntax highlighting to give it, so that tools won't be confused with Unity shaders, etc.

### What are the disadvantages of the feature?

Slight inconvenience to existing users if they want to rename their shader files, or they can just keep using `.shader`.

### How will this be implemented or integrated into the O3DE environment?

The code will be modified to write shaders to a new file format, and read shaders from either this format or `.shader`.

### Are there any alternatives to this feature?

There are many options of what to use. Perhaps `.o3deshader` or `.o3desl`, or perhaps someone can think of a better extension.

**Comment by olegbc1** [comment]
Wholeheartedly agree with the suggestion - thanks @aaronfranke! How about `.bestshader`, `.supershader` or `.yepanothershaderformat` extensions?  :innocent:  :grin:

**Comment by hultonha** [comment]
What about `.azsl` as that's the name of the shading language? 🤔

I'm not on the Atom team I'm afraid so there might be good reasons for not calling it that but you never know, hopefully someone from Atom will chime in (calling @rgba16f 🙂)

**Comment by rgba16f** [comment]
@galibzon @santorac @wintermute-motherbrain Question about using something other than shader for our file type.

**Comment by rgba16f** [comment]
I think this is asking us to make way for unity, why not message them and ask them to change their shader file extension :)

**Comment by wintermute-motherbrain** [comment]
Let's discuss this at the next sig-presentation meeting on 7/21.

**Comment by aaronfranke** [comment]
> I think this is asking us to make way for unity, why not message them and ask them to change their shader file extension :)

Both would be good.

Remember that there are other advantages besides just avoiding confusion with Unity.

**Comment by moudgils** [comment]
> What about `.azsl` as that's the name of the shading language? 🤔
> 
> I'm not on the Atom team I'm afraid so there might be good reasons for not calling it that but you never know, hopefully someone from Atom will chime in (calling @rgba16f 🙂)

We cant because .shader file references .azsl files
.azsl contains shader code and .shader contains info about Renderstate, supervariants, which azsl file to reference, etc.

**Comment by galibzon** [comment]
Both .o3deshader or .o3desl are reasonable.

**Comment by rgba16f** [comment]
> Both .o3deshader or .o3desl are reasonable.

I'd vote for o3deshader.

**Comment by santorac** [comment]
I totally agree that .shader isn't great, especially as people tend to call the azsl file a "shader". Here at Amazon we often disambiguate in conversation by saying "dot shader file" instead of just "shader file". This could certainly be improved.

.o3deshader or .o3desl begs the question: why don't other extensions have an "o3de" prefix? To me it seems a bit awkward if we add a prefix only for this one file type. For context, here is a list some other extensions in the engine:

- .shader (similar to a "technique", includes a reference to shader code, render states, permutation information, compiler flags, etc)
- .azsl (actual shader code)
- .shadervariantlist (list of shader variants or shader permutations that should be compiled)
- .materialtype (defines the layout and behavior of a class of materials, similar to Unreal master material)
- .material (references a material type and includes a list of property values)
- .azasset (generic json data container)
- .pass (a pass or pass sub-tree used in the render pipeline)

I suggest we either:
1. Establish an engine-wide convention for an extension prefix
2. Come up with some other name to distinguish the "shader" file. Maybe one of...
    - .shaderasset
    - .shaderconfig
    - .shadermanifest
    - shadermain

**Comment by Adi-Amazon** [comment]
+1 on .shaderconfig as it is a name that well represents the purpose of the file, unlike .shader that in addition to the above points, is also somewhat misleading.
