### ISSUE TITLE
C# programming language.

### ISSUE THREAD

**Issue by 111ukasz111** [o3de/o3de#1893]
**Describe the solution you'd like**
Many Unity users will migrate to o3de.

**Describe alternatives you've considered**
-

**Additional context**
C# is a very popular language.

**Comment by Mobs1024** [comment]
why do you need `C#` but o3de is a programming language in `Lua` similar to Python syntax but performance is not great

**Comment by S3r1ous** [comment]
i am no expert in these things but anything that avoids complexity blowing up as things get added/improved is probably a good i think
switching languages/major components etc is big thing, its not as easy as it looks and often whatever perceived benefits either aren't worth it or get outweighed by whats already there, you need really good reasons to do these big changes and crystal clear or as close to it understanding why
Lua, C# languages like that, have a lot of uses and in a lot of things benefit the workflow, but if i could i would prefer do things with just a few very specific tools to avoid all the compatibility etc headache
just my 2 cents

**Comment by Dimous** [comment]
It would be great if there was something like Godot's NativeScript. Want Rust -- no problem, want C# -- here you go.

**Comment by olegbc1** [comment]
Should probably leave it to a SIGs but FWIW, transitions from C# to C libs will cause significant performance degradation. C# makes a lot of sense in Unity since so much of it is written in C# and execution can just stay in CIL, but for an engine written in C++, implementing C# for scripting just wouldn't be optimal. There are things than performance to consider of course...
