### ISSUE TITLE
Registered external Gems do not show up in Configure Gems when creating a project

### ISSUE THREAD

**Issue by fabioanderegg** [o3de/o3de#1965]
**Describe the bug**
Registered external Gems do not show up in "Configure Gems" when creating a project in the Project Manager (o3de.exe)

**To Reproduce**
1. Create a new Gem: `.\scripts\o3de.bat create-gem -gp D:\dev\open3d\MyTestGem`
2. Register Gem with engine: `.\scripts\o3de.bat register -gp D:\dev\open3d\MyTestGem`
3. Open `o3de.exe`, create new project, click "Configure Gems"

**Expected behavior**
The registered Gem should be selectable in the list of available Gems, but it is not in the list.
The Gem is selectable after the project has been created using "Edit Project Settings" => "Configure Gems".

**Additional context**
SDK build of the development branch, commit ec026963b8a6440b755aecd622864e43b0603c48.

**Comment by lumberyard-employee-dm** [comment]
@AMZN-alexpete @amzn-jillich If I were to guess what the issue is, is that the list of available gems isn't populated from a call to `manifest.get_all_gems` in the Project Manager, if attempting to configure for project that has not been created yet

It looks like that only "get_engine_gems" is invoked when the project is not created yet in [GemCatalogScreen.cpp](https://github.com/o3de/o3de/blob/stabilization/2106/Code/Tools/ProjectManager/Source/GemCatalog/GemCatalogScreen.cpp#L90-L100)

I believe that calling "get_all_gems" unconditionally would resolve the issue
