### ISSUE TITLE
Gems registered with the Engine SDK and added to a project via the Project Manager do not get built

### ISSUE THREAD

**Issue by fabioanderegg** [o3de/o3de#1967]
**Describe the bug**
Gems registered with the engine SDK and added to a project via the Project Manager do not get built.

**To Reproduce**
1. Create a new Gem: `.\scripts\o3de.bat create-gem -gp D:\dev\open3d\MyTestGem`
2. Register Gem with engine: `.\scripts\o3de.bat register -gp D:\dev\open3d\MyTestGem`
3. Open `o3de.exe`, create new project
4. Edit project settings, activate Gem created above (can't select gem in the creation wizard, see #1965)
4. Build project in `o3de.exe`

The Gem gets successfully added to both `o3de_manifest.json` and `enabled_gems.cmake` and can be selected in the Project Manager. However, the Gem is not added to the Visual Studio Solution and therefore does not get built by the Project Manager.

**Expected behavior**
* The Visual Studio Solution should contain the Gem project, so it can be built from source
* The build process in the Project Manager should build the Gem

**Additional context**
This is on an SDK build as described in the official docs, unsure if this also happens on a non-SDK build.

**Comment by lumberyard-employee-dm** [comment]
@AMZN-alexpete @amzn-jillich The fix for this issue, is that when a Gem is enabled in the Project Manager, it should be checked to see if it is registered in either the project's project.json file or the engine's engine.json file.
If it is not, then it should be registered within the project's project.json file

The following python commands can gather that information.
- manifest.py  [get_engine_gems](https://github.com/o3de/o3de/blob/development/scripts/o3de/o3de/manifest.py#L287)
- manifest.py  [get_project_gems](https://github.com/o3de/o3de/blob/development/scripts/o3de/o3de/manifest.py#L319)

Afterwards the register.py [register](https://github.com/o3de/o3de/blob/development/scripts/o3de/o3de/register.py#L597-L602) method can be used with the arguments of `gem_path` and `external_subdir_path` arguments to register that gem with the project.json

**Comment by lumberyard-employee-dm** [comment]
> @AMZN-alexpete @amzn-jillich The fix for this issue, is that when a Gem is enabled in the Project Manager, it should be checked to see if it is registered in either the project's project.json file or the engine's engine.json file.
> If it is not, then it should be registered within the project's project.json file
> 
> The following python commands can gather that information.
> 
> * manifest.py  [get_engine_gems](https://github.com/o3de/o3de/blob/development/scripts/o3de/o3de/manifest.py#L287)
> * manifest.py  [get_project_gems](https://github.com/o3de/o3de/blob/development/scripts/o3de/o3de/manifest.py#L319)
> 
> Afterwards the register.py [register](https://github.com/o3de/o3de/blob/development/scripts/o3de/o3de/register.py#L597-L602) method can be used with the arguments of `gem_path` and `external_subdir_path` arguments to register that gem with the project.json

I have a better idea. The o3de.py `enable-gem` command will just register the gem with the project if it is not already registered with either the project or engine.

That way this works for both the o3de.py script and the o3de.exe
