### ISSUE TITLE
Bug Report - Windows, HOME environment

### ISSUE THREAD

**Issue by LiteLessomoroff** [o3de/o3de#2071]
**Describe the bug**
Can't building any project. Seems than engine in different situation using different .o3de paths.
E.g. when registering engine, it's creates .o3de folder in HOME's folder; when building project - it's using User's folder.
But if copy .o3de from HOME to Users folder then another error appears.

**To Reproduce**

On Windows:
Create HOME variable(environment variable) and set folder.

**Expected behavior**
Expecting that .o3de folder has 1 place(if HOME var entered, then in HOME's path).
If HOME variable using - expecting that all links in code goint to this path - HOME/.o3de

**Screenshots**
-

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version [10]
 - CPU [Threadripper 1920x ]
 - GPU [Radeon VII]
 - Memory [96 GB]

**Additional context**
Think than it's not so critical, but inconvenient in some cases

**Comment by Srekel** [comment]
I disagree about the solution.

> (if HOME var entered, then in HOME's path).
> If HOME variable using - expecting that all links in code goint to this path - HOME/.o3de

Any "if this then there1 else there2" solution is bound to cause headaches in the vein of "it works on my machine".

In my case, the only reason I have a HOME path, as far as I know, is that I've installed cygwin for a specific purpose, and I guess it has set my home path there as HOME in Windows. I certainly don't want any applications thinking that's where I think my "home" is.

In fact I would like to not have it on my C drive at all by default, especially since it's going to use a lot of space. Not the manifest file, but the default folders which are right next to the manifest file. 

IMHO, it would be better to explicitly need to pass the path in when o3de sets up that folder.

**Comment by LiteLessomoroff** [comment]
True. 

.o3de folder was in context: manifest location(separated folder).
Certainly, data storing in other disk.
Since there is more specifically theme
#2078 
Closing this.
Thanks.
