### ISSUE TITLE
Asset processing failed at Asset processor

### ISSUE THREAD

**Issue by YiMunDong** [o3de/o3de#2125]
![image](https://user-images.githubusercontent.com/44878188/125419851-3c67ca67-5d24-4d5c-933e-8bc6b7725075.png)
![image](https://user-images.githubusercontent.com/44878188/125420126-dd20da70-cd53-4c28-8955-276b06b66375.png)

All builds were successful. When I run the editor, a problem occurs. Asset processing fails. this file is exists normally. What can I do?

**Comment by mbalfour-amzn** [comment]
@YiMunDong do you have the ImageProcessingAtom gem enabled in the "MyDefaultProject1" project?  I haven't seen this problem myself, but given the error message of "Failed gradient image conversion job for %s.\nFailed loading source image %s.\n", my best guess is that it's failing to load the input image because ImageProcessingAtom isn't available to load it.

**Comment by monroegm** [comment]
@YiMunDong Please reopen if this is still an issue
