### ISSUE TITLE
When adding Gems using `external_subdirectories` in `project.json`, the Editor version of the Gem is not built

### ISSUE THREAD

**Issue by fabioanderegg** [o3de/o3de#2127]
**Describe the bug**
When a Gem is added to `external_subdirectories` in `project.json`, building in the Project Manager only builds the "normal" Gem, but not the Editor version of the Gem. This is kind of expected, because the GameLauncher only references the "normal" Gem, and I suppose this is the target that gets built.

Context: We distribute our Kythera Gem https://o3de.org/docs/user-guide/gems/reference/kythera-ai/kythera-ai-gem-setup/ as separate download for now, and we would like to make it as easy as possible to add the Gem to a project created in and SDK build and later in an engine build from the installer. Our Gem has quite a few editor features, so the Editor Gem should be built when adding the Gem this way.

This previous bug describes a problem where the building of the Gem did not work at all, and has the same repro steps as this one: https://github.com/o3de/o3de/issues/1978

**To Reproduce**
1. Create a new project in Project Manager
2. Create a new Gem: `.\scripts\o3de.bat create-gem -gp D:\dev\open3d\MyTestGem`
3. Register Gem with project: `.\scripts\o3de.bat register -gp D:\dev\open3d\MyTestGem --external-subdirectory-project-path D:\dev\open3d\projects\MyTestProject`
4. Try building the project in the Project Manager

**Expected behavior**
The Editor version of the Gem is also built.

**Comment by amznestebanpapp** [comment]
The project manager is trying to build the Editor but that project doesn't exist in project-centric/engine-prebuilt. Editor exists as a target in CMake in project-centric/engine-source and in engine-centric, but its an imported target in project-centric/engine-prebuilt and does not generate a VS project (therefore is not a build target).

We talked it internally and I was creating a `RUN_Editor` target for project-centric/engine-prebuilt so the editor could be run/debug from VS. @lumberyard-employee-dm suggested to rename the `Editor` target to `Editor.Imported` and use `Editor` for the `RUN_Editor`. Since `Editor` will depend on `Editor.Imported`, O3DE will build that utility project and build the proper dependencies.

**Comment by lumberyard-employee-dm** [comment]
It looks Like the ProjectManager tries to build the [Editor](https://github.com/o3de/o3de/blob/development/Code/Tools/ProjectManager/Platform/Windows/ProjectBuilderWorker_windows.cpp#L135-L146) target already when building the project, but that target doesn't exist when using an SDK Engine.

If we add a custom_target of  `Editor` when making the Install Layout, then there shouldn't need to be any changes made to the ProjectManager itself, since that would now just pick up the target.
