### ISSUE TITLE
Renderdoc does not work with O3DE. Add support to easily disable OpenImageIO as that does not work with Renderdoc

### ISSUE THREAD

**Issue by moudgils** [o3de/o3de#2132]
Renderdoc does not work with O3DE. This is because OpenImageIO interferes with Renderdoc. If MS was a partner we could ask them to look into this but until then we need to easily disable OpenImageIO (via a #define?) so that Renderdoc can work.

**Comment by akioCL** [comment]
Is this DX12 or Vulkan or both?

**Comment by moudgils** [comment]
> Is this DX12 or Vulkan or both?

Yes

**Comment by hershey5045** [comment]
Hi, the current workaround for this is as follows:

### For Editor
1. In Gems\Atom\Feature\Common\Code\Source\Platform\Windows\platform_windows.cmake, disable the OPEN_IMAGE_IO_ENABLED definition
```
set(LY_COMPILE_DEFINITIONS
    PRIVATE
#        OPEN_IMAGE_IO_ENABLED  
)
```

### For AtomSampleViewer
1. Follow step 1 above
2. In AtomSampleViewer\Gem\Code\Source\Platform\Windows\ScriptReporter_Windows.cpp, uncomment the following lines:
* line 10 - header include for OpenImageIO
* lines 16-44 - the whole function implementation except for the return statement
3. Add [[maybe_used]] to the function arguments if compile errors are occurring
```
bool ScriptReporter::LoadPngData(
     [[maybe_unused]] ImageComparisonResult& imageComparisonResult, 
     [[maybe_unused]] const AZStd::string& path, AZStd::vector<uint8_t>& buffer,
     ...
)
```

**Comment by moudgils** [comment]
Pix/Renderdoc markers setup

- Go to this link and download WinPixEventRuntime. https://www.nuget.org/packages/WinPixEventRuntime

- At the time of writing this I tested this with 1.0.210209001. I downloaded winpixeventruntime.1.0.210209001.nupkg file and renamed it to winpixeventruntime.1.0.210209001.zip and unzipped it.

- Add an environment variable (User variable) called ATOM_PIX_PATH and point it to the path where the package is downloaded and unzipped. As an example, for me it points to C:\Users\moudgils\Downloads\winpixeventruntime.1.0.210209001

- Reconfigure and recompile and you should have pix markers for Renderdoc and Pix captures.

**Comment by jeremyong-az** [comment]
Fortunately, it turns out that enabling renderdoc can work without needing to disable OpenImageIO (the demonstration capture below was taken without removing it).

![image](https://user-images.githubusercontent.com/87345238/127735983-1420e884-301e-4c00-bf56-18674df7ce5c.png)

My suspicion is that the `LoadLibrary` hook injected by RenderDoc on launch is somehow happening too late (after device creation), or the process is launching in such a way that the injection fails. It's possible that because we spawn multiple processes on launch, that the hook is injected in the wrong process module.

Either way, the remedy is simply to invoke `LoadLibrary` or `dlopen` ourselves manually, if requested by the user using a cvar.

Here are the snippets of code I added to make this work.

```cmake
# D:\o3de\Gems\Atom\RHI\DX12\3rdParty\Platform\Windows\renderdoc_windows.cmake

# Common installation path for renderdoc path
set(RENDERDOC_PATH "C:/Program Files/RenderDoc")
if(DEFINED ENV{"ATOM_RENDERDOC_PATH"})
    set(RENDERDOC_PATH ENV{"ATOM_RENDERDOC_PATH"})
endif()

# Normalize file path
file(TO_CMAKE_PATH "${RENDERDOC_PATH}" RENDERDOC_PATH)

if(EXISTS "${RENDERDOC_PATH}/renderdoc.dll")
    ly_add_external_target(
        NAME renderdoc
        VERSION
        3RDPARTY_ROOT_DIRECTORY ${RENDERDOC_PATH}
        INCLUDE_DIRECTORIES "."
        RUNTIME_DEPENDENCIES "${RENDERDOC_PATH}/renderdoc.dll"
    )
endif()
```

In `D:\o3de\Gems\Atom\RHI\DX12\Code\CMakeLists.txt`, add the following lines near the top somewhere

```
include("../3rdParty/Platform/Windows/renderdoc_windows.cmake")
if(TARGET "3rdParty::renderdoc")
    message(STATUS "Renderdoc found")
    set(USE_RENDERDOC_DEFINE "USE_RENDERDOC")
    set(RENDERDOC_BUILD_DEPENDENCY "3rdParty::renderdoc")
else()
    message(STATUS "Renderdoc missing")
    set(USE_RENDERDOC_DEFINE "")
    set(RENDERDOC_BUILD_DEPENDENCY "")
endif()
```

and for each target, add `USE_RENDERDOC_DEFINE` as a build definition and `RENDERDOC_BUILD_DEPENDENCY` as a private dependency. This needs to happen for the Vulkan RHI layer as well (and we should handle Linux).

Now, on build, if Renderdoc was available at configure time or if it was supplied via the `ATOM_RENDERDOC_PATH` environment variable, the `renderdoc.dll` file will be copied to the build directory.

The only thing remaining to do is invoke `LoadLibraryA("renderdoc.dll")` somewhere prior to device creation if requested based on a cvar. In my case, an opportune moment to do this was in `SystemComponent_Windows.cpp`, where I added the following before we create the `dxgiFactory`:

```c++

#if defined(USE_RENDERDOC)
            HMODULE rdocModule = LoadLibraryA("renderdoc.dll");
            if (rdocModule)
            {
                pRENDERDOC_GetAPI RENDERDOC_GetAPI = (pRENDERDOC_GetAPI)GetProcAddress(rdocModule, "RENDERDOC_GetAPI");
                int ret = RENDERDOC_GetAPI(eRENDERDOC_API_Version_1_1_2, (void**)&rdocApi);
                AZ_Assert(ret == 1, "Failed to fetch Renderdoc API address");
            }
#endif
```

At the top of the file of course, I have the following:

```c++
#if defined(USE_RENDERDOC)
#include <renderdoc_app.h>

RENDERDOC_API_1_1_2* rdocApi = nullptr;
#endif
```

Now, it isn't required that we query the API pointer, but this just demonstrates that we can in fact query it and use that to drive captures programmatically in the future. Implementing this properly is a matter of exposing the cvar, supporting vulkan, and lifting the Rdoc initialization and routines to access the API pointer in a common module.

**Comment by jeremyong-az** [comment]
See PR #2680 which addresses the above with some refinement over my hackier implementation.

The PR with corrections supports Vulkan/Windows, _should_ work on Linux (but I can't test it) and should be not too difficult to get working on Android either (also can't test this).

**Comment by superkitcath** [comment]
This was fixed
