### ISSUE TITLE
Context Menu Pops Up After Rotating Camera

### ISSUE THREAD

**Issue by santorac** [o3de/o3de#2251]
**Describe the bug**
In the Editor, when you RMB-drag to rotate the camera, it sometimes registers as a right-click and opens the context menu.

**To Reproduce**
1. Run the Editor
2. Open any level
3. Right-click and drag to rotate the camera
4. Repeat several times

**Expected behavior**
The context menu should only pop up when the user is doing a simple right-click.

**Screenshots**
See attached video.
https://user-images.githubusercontent.com/55155825/126027836-1ab98c1e-af79-45cc-8ecb-c570a1fb04d1.mp4

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version: 10
 - CPU: AMD Ryzen Threadripper 3970X
 - GPU: GTX 1660 SUPER
 - Memory: 64GB

**Additional context**
I am running on dual 4k monitors with 150% desktop scaling.

**Comment by pr0g** [comment]
This is on me, I can disable hiding the mouse cursor temporarily to resolve this (there is a workaround to set `ed_showCursorCameraLook` to true in a `user.cfg` file in the root. I'll try and get a PR out early next week to resolve it

**Comment by hultonha** [comment]
This is on me, I can disable hiding the mouse cursor temporarily to resolve this (there is a workaround to set `ed_showCursorCameraLook` to true in a `user.cfg` file in the root. I'll try and get a PR out early next week to resolve it

**Comment by cgalvan** [comment]
@hultonha  Should we close this one and just link it with this instead?  https://github.com/o3de/o3de/issues/2493

**Comment by hultonha** [comment]
@cgalvan Yeah I think this makes sense, this particular issues #2251 is 'fixed' at the moment because we don't try to hide the cursor. I'm going to restore that soon (been looking at lots of input stuff lately so will try switch to this so it's complete as part of the same work) it's just right now the context menu pop-up is _more_ annoying than seeing the cursor which is why we set `ed_showCursorCameraLook` to true for now.
