### ISSUE TITLE
Bootstrap.setreg Doesn't Support Paths without escaped Backslashes

### ISSUE THREAD

**Issue by AMZN-Gene** [o3de/o3de#2437]
Bootstrap.setreg doesn't support paths with backslash.  On Windows users will want to copy+paste their folder paths in order to set the bootstrap.setreg project_path setting, but this won't work.

**To Reproduce**
1. Use a Windows machine
2. Open o3de.\Registry\bootstrap.setreg
3. Set the project_path to a game project path on your Windows machine 
    i. Example:  "project_path":  C:\prj\o3de-gamejam-0721
4. Open Editor.exe
5. See error
Unable to parse registry file "C:\Users\genewalt\.o3de\Registry/bootstrap.setreg" due to json error "Invalid escape character in string." at offset 177.

**Expected behavior**
Bootstrap should accept valid folder path

**Screenshots**
![image](https://user-images.githubusercontent.com/32776221/127029301-0d00b291-7776-458b-96a0-b04565e2514f.png)

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows

**Comment by amzn-phist** [comment]
I think in json files backslashes need to be escaped.  So in your example it should be `"C:\\Users\\genewalt\\.o3de\\Registry/bootstrap.setreg"`.  Can you try it again with escaped backslashes?

**Comment by lumberyard-employee-dm** [comment]
@AMZN-Gene The issue isn't with the forward slashes, it is with the backslashes. 
Because `.setreg` and .setregpatch` files are JSON files, any backslashes need to be escaped with a second backslash.

Also to alleviate the ability for users to enter in paths with a single backslash into the `bootstrap.setreg` file manually, the `o3de.py set-global-project -pp <project-path>` exist just for this.

**Comment by AMZN-Gene** [comment]
Totally understand there are work arounds to the problem, but not knowing JSON I just found it odd that providing a traditional windows path failed.  If you're like me, you want to quickly copy+paste the path from Windows Explorer. People will figure it out when they see error message. Otherwise, considering bootstrap only contains a project path, we could make it easy on ppl by replacing the slashes in code.  Feel free to close it, just thought this would happen often and I could potentially stop one papercut.

**Comment by lumberyard-employee-dm** [comment]
> 
> 
> Totally understand there are work arounds to the problem, but not knowing JSON I just found it odd that providing a traditional windows path failed. If you're like me, you want to quickly copy+paste the path from Windows Explorer. People will figure it out when they see error message. Otherwise, considering bootstrap only contains a project path, we could make it easy on ppl by replacing the slashes in code. Feel free to close it, just thought this would happen often and I could potentially stop one papercut.

I understand wanting to make sure users could avoid errors with Windows Paths copied from the Windows Explorer, but the issue is that the JSON parser(rapidjson) parses the JSON text directly.

There is no way we could transform the text within the JSON Content itself, because there is no way to guess the intent of the user when parsing a JSON blob.
The context of the text is determined by how the JSON fields are used, which means that we can only supply the text to the JSON Parser and let it parse valid JSON. Backslashes are an escaped character according to the JSON [rfc7159](https://datatracker.ietf.org/doc/html/rfc7159#section-7).

Pretty much what I am trying to say, is that in order to modify a *.setreg or a *.setregpatch file via a text editor the user must know JSON.
If the user doesn't know JSON, then they shouldn't modify a *.setreg or a *.setregpatch file via text editor.

It is the same as a user trying to modify C++ Code. In order for a user to modify C++ Code, they must know about the C++ Language.

I have added a [feature request](https://github.com/o3de/o3de/issues/2218) about making a UI Editor for the Settings Registry, which would help alleviate the need for users to know JSON to modify settings, but if and when that feature gets worked on is an unknown
