### ISSUE TITLE
Cloth Simulation Test Scenario Fails With Cloth Not Connected to Model

### ISSUE THREAD

**Issue by santorac** [o3de/o3de#2454]
**Describe the bug**
A specific test case used by Amazon fails. A cloth mesh that is supposed to be connected to an actor falls through the ground when simulated.

**To Reproduce**
-Create a new level in the AtomTest project
-Right-click the main viewport and choose 'instantiate slice'
-Search for and choose Chicken_Actor.slice
-Select the Chicken_Actor entity (a child entity of Chicken Rigidbody)
-Navigate to the cloth component in the entity inspector
-Toggle 'Simulate in editor' on
-Expected behavior - the chicken mohawk flops over instead of standing straight up, but stays attached to the head
-Toggle 'Preview In Editor' on in the Simple Motion component

**Expected behavior**
The chicken animates, and the mohawk should move/flop around when the chicken moves its head. But the mohawk just falls straight through the scene and out of sight.

**Screenshots**
![image](https://user-images.githubusercontent.com/55155825/127058729-dcb834ce-32ba-42e2-be71-b793da1391c5.png)

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version: 10
 - CPU [e.g. Intel I9-9900k , Ryzen 5900x, ]
 - GPU [AMD 6800 XT, NVidia RTX 3090]
 - Memory [e.g. 16GB]

**Additional context**
This was discovered on Amazon's development branch as of 8f35def25bd3cf977e6eb06761df9ba6b67a7152

**Comment by moraaar** [comment]
The cause of this issue is the Mesh Optimizer.  When it's disabled (by commenting out the BindToCall line in MeshOptimizerComponent constructor and rebuilding) and the asset is reprocessed, the non-optimized mesh has the correct vertex color information.

It seems like the mesh optimizer is not correcting carrying the vertex color data when optimizing the mesh. Debugging ClothRule::ExtractClothData function while AP is processing the mesh showed that all the vertices red color is 1, where without the optimizer some of the vertices red color is 0 (which will make those vertices static in cloth).
