### ISSUE TITLE
PhysX Force Region disappears depending on camera orientation

### ISSUE THREAD

**Issue by amzn-jillich** [o3de/o3de#2466]
PhysX Force Region disappears depending on camera orientation

**To Reproduce**
![ForceFields_lq](https://user-images.githubusercontent.com/43751992/127125446-34ce72ab-a11c-45d0-bc61-87b46023ed32.gif)

**Expected behavior**
Force field is always visible and just gets skipped to render when the debug visualization is fully out of the view frustum

**Comment by rgba16f** [comment]
I think this is the force region entity going offscreen. Does the force region entity update it's bounding box to match the region?

**Comment by rgba16f** [comment]
@hultonha I think this may be fixed by your change?

**Comment by hultonha** [comment]
@rgba16f This won't be fixed by my change, but it will require the same change for the PhysX Force Region (to correctly implement `GetLocalBounds` and `GetWorldBounds` on the `BoundsRequestBus`.

It should be simple to add (just figure out what you're drawing, and return the AABB for that geometry). I'll mention it to the team here as this would definitely be something useful to pick-up. If you know of other components with this problem please let me know and we can point them at the LightComponent PR as an example. Ideally the owning teams/sigs for the components should implement this bus.

**Comment by hultonha** [comment]
I've updated the labels and cleared the assignees as this is really a physics/sig-simulation issue. Tagging @lgleim as something we should discuss in sig/simulation triage briefly
