### ISSUE TITLE
The Material Editor only intermittently updates the material when the shaders are recompiled

### ISSUE THREAD

**Issue by jonawals** [o3de/o3de#2475]
**Describe the bug**
The Material Editor only intermittently updates the material when the shaders are recompiled.

**To Reproduce**
1. Edit the shader of a given material.
2. Save your changes.
3. Go back to the material editor (accept any prompts to reload the material).
4. There's a 50/50 chance the changes will actually be reflected in the Material Editor.
5. Repeat steps 1 to 4 by editing meaningless whitespace until the original changes are reflected.

**Expected behavior**
The Material Editor should always reflect the latest changes when a material is reloaded due to external changes.

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows

**Comment by gadams3** [comment]
There have been many changes since this was reported. My current tests relating to hot reloading after material and shader changes seem to work consistently. However, it takes several seconds for shader changes to be reflected in the viewport. There will be optimizations to this in the near future. In the mean time, here is a link that describes how to change settings to improve shader iteration times on a specific platform.

https://github.com/o3de/o3de/wiki/Faster-Shader-Iteration

https://github.com/o3de/o3de/pull/10555
https://github.com/o3de/o3de/pull/10468
