### ISSUE TITLE
[CRITICAL] CTRL+SHIFT+LEFT CLICK does not snap an entity to the 3D location clicked

### ISSUE THREAD

**Issue by AMZN-alexpete** [o3de/o3de#2480]
**Describe the bug**
When you have an entity selected and press CTRL+SHIFT and left mouse click in the viewport, the entity should snap to the 3d world position the mouse clicked on.  This is necessary to snap objects to surfaces (e.g. trees to terrain, windows to walls etc.)

**To Reproduce**
1. Open the editor and select the default ball entity
2. Move the model below the ground
3. In the viewport CTRL+SHIFT and left mouse click on the ground plane

**Expected behavior**
The ball entity position snaps to the surface of the ground plane

**Screenshots**
n/a

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version commit da474357f3d0ae9d9c3e884a397ccdcaec7e9be6

**Additional context**
n/a

**Comment by hultonha** [comment]
This is fixed by #5906

IMPORTANT: To remain consistent with existing entity (and manipulator) 'ditto' commands, the shortcut to snap to surface is 'Ctrl+Shift+MMB' (**not LMB**). We may revisit this in future, but it would require a reworking of more of the viewport controls so it has not been performed as part of this change.
