### ISSUE TITLE
Jinja files are not copied over to the INSTALL install laoyut when they are PUBLIC files

### ISSUE THREAD

**Issue by lumberyard-employee-dm** [o3de/o3de#2517]
**Describe the bug**
Any .jinja files that part of the O3DE Engine Source isn't copied over to the O3DE Engine SDK layout when running the INSTALL step.

Also the [AzAutoGen](https://github.com/o3de/o3de/blob/development/Code/Framework/AzAutoGen/AzAutoGen.py) script needed to execute AutoGen is also not copied over to the INSTALL layout, so AutoGen fails to create any outputs.

**To Reproduce**
1. Build an SDK Layout of the Engine using the command `cmake --build <build-dir> --target INSTALL --config profile
2. Notice the AutoGen folder with the Jinja templates for ScriptCanvas is missing from the Install Layout. They should be in the same directory structure as source Engine at [Gems/ScriptCanvas/Code/Include/ScriptCanvas/AutoGen](https://github.com/o3de/o3de/tree/development/Gems/ScriptCanvas/Code/Include/ScriptCanvas/AutoGen)
3. 

**Expected behavior**
Jinja templates that are part of the PUBLIC include directory structure are copied over to the Install Layout

**Screenshots**
![image](https://user-images.githubusercontent.com/56135373/127237941-8f81487c-3c19-445c-9f89-2ae87538b229.png)

**Desktop/Device (please complete the following information):**
 - OS: Windows

**Additional context**

**Comment by amznestebanpapp** [comment]
That wont be the destination folder... the files should be treated as "header files", so they would go to the include folder instead. I got them to "install" into `install\include\Gems\ScriptCanvas\Code\Include\ScriptCanvas\AutoGen`
Same for the `AzAutoGen.py` file, its in `install\include\Code\Framework\AzAutoGen`

Now, this does create an issue, because `LyAutoGen.cmake`  has paths like `${LY_ROOT_FOLDER}/Code/Framework/AzAutoGen/AzAutoGen.py` and some other code refers to the jinjas in a similar way.

I am leaning towards not having a `install/include` folder and instead have the same folder structure for the header files that they had in the source folder.

**Comment by lumberyard-employee-dm** [comment]
I would argue that the `AzAutoGen.py` shouldn't be treated as a "header" file, but as a python script that should be placed into a `scripts/AzAutoGen/` directory.

Now for the actual jinja templates that references ${LY_ROOT_FOLDER}/<path> such as the StartingPointInput gem referencing the [ScriptCanvas templates](https://github.com/o3de/o3de/blob/development/Gems/StartingPointInput/Code/startingpointinput_autogen_files.cmake#L10-L13), I would actually update those references to use the SOURCE_DIR property of the Gem Module target `$<TARGET_PROPERTY:ScriptCanvas>/Include/ScriptCanvas/AutoGen/ScriptCanvasGrammar_Header.jinja`. That way other CMake Targets are indirectly querying the root folder for where the jinja templates reside.

Now as to where to copy the templates, if you keep the folder structure the same as it was the in the source engine gem structure, then Projects using the SDK should still be able to work with it.

**Comment by amznestebanpapp** [comment]
`AzAutoGen.py` I don't disagree, however, having it in two different paths relative to the root (of source/install) makes other places more complicated (e.g. `LyAutoGen.cmake` will need to account for those two places.
for the Jinjas, the SOURCE_DIR of the imported gem is where the CMakeLists.txt is, not where the includes are.  So that still creates a problem. I agree those places should update it to use the target property, but they would have to account for another path if they are coming from install...

All this gets simplified if we just keep the same folder structure... will roll with that to see how it looks like.

**Comment by lumberyard-employee-dm** [comment]
For `AzAutoGen.py`, I was thinking we just move it in the source engine to the scripts directory and then copy it over with other included script folders during the INSTALL step.
We would only need to update LyAutoGen.cmake for it
