### ISSUE TITLE
The asset browser shows the root file system of your computer and includes folders just named '\'

### ISSUE THREAD

**Issue by lawsonamzn** [o3de/o3de#2552]
**Describe the bug**
If you use project-centric mode, with the project outside the engine, the asset browser shows the entire folder tree including a folder just called '\\'

<img width="303" alt="image" src="https://user-images.githubusercontent.com/70027408/127375253-1e16e58b-b36f-49b0-a337-4c34d6b3c31c.png">

**To Reproduce**
1. Create a project (external to engine)
2. Compile that project  (project centric mode)
3. Open the editor
4. See the asset browser

**Expected behavior**
Not sure what's expected here.  This looks really weird (see screenshot above), my impression was that 'watch folders' for assets could come from many places/drives/locations and the UI is going to be very cluttered and difficult to navigate if each drive is shown all the way down to the root folder, using up valuable space.
**Desktop/Device (please complete the following information):**
 - windows 10 pc

**Comment by lumberyard-employee-dm** [comment]
This is due to a change I made to fix an issue with the Asset Browser not showing directories outside of the Engine Root
https://github.com/o3de/o3de/commit/92a4c76797c4d9c5539855d21ed83799b3af8c43.

Specifically it is the AZ::IO::Path iteration logic that is in [RootAssetBrowserEntry](https://github.com/o3de/o3de/blob/development/Code/Framework/AzToolsFramework/AzToolsFramework/AssetBrowser/Entries/RootAssetBrowserEntry.cpp#L396) causing the root path separator to appear.

**Comment by lawsonamzn** [comment]
I was more expecting the root of Asset Browser to be a flat list of watched folders with custom names like
```
   AtomTextures
   DevAssets
   MyProject
   Engine
```

Sort of a synthetic tree, not actual drives.  What happens if things are on various drives?
It wastes a ton of space.

**Comment by lumberyard-employee-dm** [comment]
Well folder names for Gems and Project's don't have to be unique.
The only thing that does need to be unique is there "gem_name" or "project_name" entry.

There is nothing stopping a user from making a Gem called "Atom_LightIndexDeferredExtension", plaching the contents of that gem in a folder called "Atom" and then uploading that Gem to a repo on the web that others could download.

Another user might download this "Atom_LightIndexDeferredExtension" gem to their own machine and place it at `Q:\Gems\Atom`

The Build System, Gem module loading system and AP Scan Folder logic wouldn't have any conflicts with the `<engine-root>/Gems/Atom` because that gem has a different name of "Atom".
Both Gems would build without issue, loading the Asset Processor successfully and show process any assets from each.
But with a flat structure, both of their Assets folder would be aggregated into a single folder which isn't correct.

**Comment by lmbr-pip** [comment]
This will be partly fixed in https://github.com/o3de/o3de/pull/13778 - unsure if the `\` path will be fixed in this situation though
