### ISSUE TITLE
Building via Project Manager is painful

### ISSUE THREAD

**Issue by Kadino** [o3de/o3de#2661]
**Describe the bug**
Building through O3DE Project Manager seems slow and has no output. For a new project this initially took around 10 minutes before reaching full CPU usage (perhaps executing cmake configure and other setup steps). However nothing is output indicating the status of project build nor how to replicate on CLI, aside from a simple percentage indicator. This progress indicator is inaccurate: it took approximately four hours to build, though the percentage indicator arrived at 99% after only two hours. There is additionally no ability to use build acceleration tools like Incredibulid.

**To Reproduce**
1. Open the O3DE Project Manager
2. Click on 'New Project...' and create a new project
3. In the O3DE Project Manager click "Build Project"
4. One Eternity Later

**Expected behavior**
Machine quickly builds using available hardware resources, providing accurate status toward completion.

**Screenshots**
N/A

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Win
 - Version 10
 - CPU Intel i7-9750H
 - GPU NVidia RTX 2070
 - Memory 32GB

**Additional context**
It may be simpler to provide an option to open the project in an IDE, as the CMake GUI does, instead of adding features that an IDE already provides.

**Comment by AMZN-alexpete** [comment]
Hi @Kadino,  the Project Manager now allows you to open the CMake GUI should you wish to configure and build in an IDE.  The Project Manager provides a link to the build logs which you can open to see exactly what the build is doing, and if you use the engine as an sdk, the build should complete much faster because you no longer need t o build the engine.

When you get a chance could you please re-evaluate this issue using the latest Project Manager?

**Comment by AMZN-alexpete** [comment]
@Kadino I'm going to close this due to inactivity and also because we have made improvements in the area of showing build progress, logs, and added an optional button to "Open CMake GUI" from which the user can configure, generate and open the solution in an IDE if they want to.  If you disagree feel free to re-open.
