### ISSUE TITLE
[CRITICAL] (Editor) Editor camera rotation is sluggish and difficult to use 

### ISSUE THREAD

**Issue by AMZN-alexpete** [o3de/o3de#2802]
**Describe the bug**
The editor camera now has a nice ease in-out movement, but this ease in-out has also been applied to rotation which is not good and makes camera rotation feel sluggish and "drunk".  My recommendation is to disable all camera rotation easing when moving the camera in the editor viewport via mouse input - it's fine to leave it when zooming to an object using the 'z' key.  

**To Reproduce**
1. Rotated the camera in the editor viewport

**Expected behavior**
Camera rotation is precise and easy to control and doesn't lag or overshoot

**Screenshots**
n/a

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version da47435

**Additional context**
n/a

**Comment by pr0g** [comment]
@AMZN-alexpete @amzn-jillich had a similar experience, the current smoothing isn't for everyone (I can change the default if it's more common to be a problem). The value of smoothing is tweakable, you can change it by modifying a value in the editor Settings Registry file (I think it's editorpreferences.setreg in the Registry folder). If you change `RotateSmoothness` to 6.0 instead of the 5.0 that's default it should feel a lot sharper

```
Amazon : {
    Editor: {
        Preferences: {
            Camera: {
                RotateSmoothness: 6.0
            }
        }
    }
}
```

I think should work (or change the value locally in `EditorViewportSettings.cpp` - `CameraRotateSmoothness()`

There's a task to get this surfaced to the UI, it would just be much easier if we had a Settings Registry editor (I think there's one that's WIP or planned).

Let me know if that helps!

**Comment by AMZN-alexpete** [comment]
I think you actually want to be able to turn off the smoothness entirely, by making it optional in SmoothCamera https://github.com/o3de/o3de/blob/4268376587af6dd9d23d2746f701bb2525dfa974/Code/Framework/AzFramework/AzFramework/Viewport/CameraInput.cpp#L730

**Comment by hultonha** [comment]
We can definitely add that as an option but with smoothing turned off completely you do get more stuttery movement.

In the example you cited it'd be better in my opinion to adjust sensitivity not smoothness for those situations, but having both as an option I agree is good so people have the choice. We can totally get it added.

In the meantime can you try with a larger value just to see if it makes things more usable for you? Try 10 or higher for example.

**Comment by amzn-jillich** [comment]
+1 on disabling rotational smoothing entirely on default.

I've been using LY1.28 today where this is not in and it felt much more responsive. There is more happening under the hood in O3DE: Even after commenting out the code that smooths the rotation, it doesn't react instantly. Disabling vsync improves it but doesn't fully eliminate it. Maybe some update order issue?

**Comment by hultonha** [comment]
We have @aaguilea working on removing the Legacy Camera right now (https://github.com/o3de/o3de/pull/2997) which will make it a lot easier to expose all the new Modular Viewport camera settings to the UI (at the moment we display an intersection of the two so options like rotation smoothing are missing, even though they can be updated in the Settings Registry).

If you comment out the smoothing code I don't see why things should be different from a 1.x release. I'm not sure if this is down to Atom or the new viewport input code. @amzn-jillich can you try and disable the new camera locally (set `ed_useNewCameraSystem` to false in your `user.cfg` file) to see if things are still different vs 1.x even with the old camera?

If it's different, then we have an issue somewhere in the input, if it's the same then there's a problem somewhere with the new camera. We can hold off the removal change before we fix this issue if need be.

**Comment by amzn-jillich** [comment]
@hultonha and I just had a chat and testing session over this. We tried the legacy camera, disabling `ed_useNewCameraSystem` but using that camera, the problem just increases. It felt like 50% of the inputs event were eaten by something and not reaching the camera. Sometimes it was as bad as no rotation at all, just some jittering, while I was moving the mouse.

When moving the mouse left/right 100 pixels with different speeds, you always end up in different rotation angles depending on how many events actually reach the camera. This avoids users getting a feel for how much they need to move the mouse to look where they want to.

There must be something going on under the hood with the input events, unrelated to the camera itself.

**Comment by hultonha** [comment]
Thanks for following-up @amzn-jillich - I'm actually looking into some input handling issues right now that might actually be related to this very problem (https://github.com/o3de/o3de/issues/2702). We might need to put our heads together and involve @NicholasVanSickle, @bosnichd and @AMZN-alexpete too to get to the bottom of it as it seems related to something in the input system.

One idea @amzn-jillich had is to hook-up the new camera at runtime (potentially could use it with the FlyCameraInputComponent). If it works fine there, we know there's definitely an issue at edit time with how events are generated. I've found a few culprits already which I don't think are helping but I don't think I've totally gotten to the bottom of it yet.

**Comment by bosnichd** [comment]
Something else we should try is entirely disabling the 'real' input devices while in edit mode. For some context, originally everything in editor land (except game mode) listened directly to Qt input events. That changed with the introduction of the new viewport/viewport camera, which listens to AzFramework input events, but that then caused issues because other things in the editor were (are) still listening to the Qt ones. So the concept of 'synthetic' AzFramework input devices that listen to Qt input events and map them to AzFramework input channels was introduced, which may now be causing issues because the 'real' AzFramework mouse/keyboard input devices are also still active while in edit mode? This may or may not be the problem in this case, but we probably don't want two different mouse devices (or keyboard for that matter, but that's likely less problematic) active at the same time, unless we can guarantee that anything listening to input from them will only respond to events from one of them (there was a different issue with gesture recognizers that was happening because of this, which was fixed here https://github.com/o3de/o3de/pull/2181, but ideally systems consuming input should not have to differentiate between the 'real' and 'synthetic' devices).

If we want/need to go down the path of disabling the 'real' input devices when not in game mode, please see this for reference of how we can achieve that: https://github.com/o3de/o3de/pull/2180

Another similar (potentially cleaner) solution would be to not create new synthetic Qt based devices, but rather swap out the 'real' implementations of the existing input devices at edit time with ones that listen to Qt events. We do this for the Barrier (formerly Synergy) Gem, where we swap out the default mouse/keyboard implementations with ones that listen to a Barrier/Synergy server to get mouse/keyboard input from a remote machine. The benefit of that solution is that you keep the same device instances around all the time, such that anything listening to (or querying for) input from those devices doesn't have to change at all, as from their perspective it IS the exact same input device that is reporting the input; the only thing that changes is under the hood the device is using a different implementation to get input from somewhere else (eg. a remote machine, or Qt in this case that we're talking about). It's possible this approach wouldn't work for this situation, but I think it would likely be the least error prone approach if it can be achieved.

**Comment by hultonha** [comment]
Thanks for the detailed comment @bosnichd, the info is super helpful.

I found a few things on my travels, one that is related to what you mentioned is `EditorQtMouseDevice` that drives from `InputDeviceMouse`. The Qt version still connects to the normal input buses so gets various events from the system and does not override `TickInputDevice` which I believe is causing at least one set of issues. In my local testing I overrode that function to be a noop and it seemed to reduce some of the erroneous events but not all (might be more we can do like disconnect from all buses in the Qt derived class).

The second option you proposed might be the best option long term, though I'd like to get to the bottom of exactly what's causing the issues we're seeing in this case before we switch to it (even if that's the right decision in the end).

We can all definitely catch up tomorrow! 🙂

Thanks!

Tom
