### ISSUE TITLE
[MINOR] (Atom) Some .png files default to ReferenceImage preset others to AlbedoWithGenericAlpha

### ISSUE THREAD

**Issue by AMZN-alexpete** [o3de/o3de#2805]
**Describe the bug**
When creating textures for the UI in our game jam I noticed some textures were not visible and upon investigation noticed that it was because they had automatically been set to use the ReferenceImage preset instead of AlbedoWithGenericAlpha

**To Reproduce**
1. Create a .png for a cursor image with alpha

**Expected behavior**
The image preset used is not ReferenceImage

**Screenshots**
n/a

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version da47435

**Additional context**
n/a

**Comment by VickyAtAZ** [comment]
The reason it didn't use AlbedoWithGenericAlpha automatically because the image may not have pow of 2 size (which some compressed format couldn't handle this kind of sizes previously) . 

The code has been changed so all the compressed format can handle odd sizes. 

So now it should be defaulted to use AlbedoWithGenericAlpha if the image doesn't have a valid file mask.
