### ISSUE TITLE
NvClothTests_Main.main failing on nightly clean

### ISSUE THREAD

**Issue by amznestebanpapp** [o3de/o3de#2963]
**Describe the bug**
NvClothTests_Main.main test suite is failing on nightly clean jobs

**Failed Jenkins Job Information:**
test_gpu_profile_vs2019
```
[2021-08-06T06:43:35.184Z] The following tests FAILED:
[2021-08-06T06:43:35.184Z] 	 24 - AutomatedTesting::NvClothTests_Main.main::TEST_RUN (Failed)
```
**Attachments**
[nvcloth.txt](https://github.com/o3de/o3de/files/6948149/nvcloth.txt)

**Comment by moraaar** [comment]
The warning that was causing the test to fail is the following:

`[Warning] (MeshFeatureProcessor) - No material provided for mesh. Skipping.`

Which I noticed a couple of weeks ago for some reason that the exporter didn't pick up any material from the cloth mesh using in the test and that's why it warned about it and the test failed.

With the latest from today (git commit ef9666cb10) the issue doesn't show up, the mesh asset is correctly processed and it detects 1 material, so the warning doesn't appear anymore. It must have been fixed at some point.

I tested locally and it worked, plus the `test_gpu_profile_vs2019` job from last nightly builds passed and are green.

Resolving the issue.
