### ISSUE TITLE
[PhysX] PhysicsAsset cannot load triangle mesh as its input.

### ISSUE THREAD

**Issue by Jackie9527** [o3de/o3de#2994]
Currently, before creating a PhysX Collider with a mesh, I have to edit the mesh file in the Fbx Settings dialog, set Export As to Convex. If I create a PhysX Collider with PhysicsAsset as its shape and give a triangle mesh as its input, then Editor would conplain that "The Physics Asset triangle.pxmesh is a Triangle Mesh, it is not compatible with a Dynamic Rigidbody, either: Change the PhysicsAsset to Convex Mesh or set the Rigidbody to kinematic."

>Like graphical triangle meshes, a collision triangle mesh consists of a collection of vertices and the triangle indices. Triangle mesh creation requires use of the cooking library. It is assumed here that the cooking library has already been initialized.

As [PhysX Geometry](https://gameworksdocs.nvidia.com/PhysX/4.1/documentation/physxguide/Manual/Geometry.html), PhysX supports Triangle Meshes. It is convenient that PhysX Collider with PhysicsAsset could support triangle as its input.

**Comment by greerdv** [comment]
PhysX does support triangle meshes, but only for static or kinematic bodies. They are not supported for dynamic rigid bodies, and that is a limitation of PhysX rather than O3DE. 

There are ways to mitigate this problem, for example you can select convex output in the FBX settings and use the decompose meshes setting to split a triangle mesh into multiple convex parts which approximate the original shape (and which are supported on dynamic rigid bodies). See https://o3de.org/docs/user-guide/components/reference/physx/collider/#dynamic-body-with-collider-using-convex-decomposition and https://o3de.org/docs/user-guide/assets/fbx-settings/physx-export/ for more details.

The restrictions around what geometry can be used where are unfortunately a bit complicated - if you have any suggestions how to improve the documentation or workflow to make things easier to follow, please let us know.

**Comment by greerdv** [comment]
Closing this issue as it has been inactive for months, and the feature is already supported, it's just that PhysX has restrictions on when you can use triangle mesh colliders.
