### ISSUE TITLE
.gltf support what works and what needs support.

### ISSUE THREAD

**Issue by WashedUpStudio** [o3de/o3de#3058]
**Is your feature request related to a problem? Please describe.**
I do not like fbx that much, and .gltf is an alternative that is open and has great support within assimp. 

**Describe the solution you'd like**
I would like to see .gltf be a format that is fully supported within o3de.

**Describe alternatives you've considered**
fbx is an alternative, but since o3de is open source there will never be perfect support for this format.

**Additional context**
I have started working/testing .gltf in the o3de engine, and have found a few things that work nicely with it, and some things that do not. For starters, here is some basic files I have used for testing: 
[gltfTests.zip](https://github.com/o3de/o3de/files/6971716/gltfTests.zip)

The first thing that needs to be done is go into you o3de directory, and search for sceneassetimporter.setreg to get the setreg file that needs the extra line added so gltf files can be imported which is adding ".gltf" after the .stl file extension. This file should look like this for the supported file types :
"SupportedFileTypeExtensions":
				[
					".fbx",
					".stl",
					".gltf"
				]

A few things to remember is all these files need to be scaled 10 times when they are imported since they do not have a scale option on export from blender. So when dragging each of these files into the editor just scale the transform component by 10 to get the correct aspect. Also the gltf settings inside of the editor does not work. All the settings are there that should be, but you cannot scale from within, change animation frames, or change needed bones/scale the actor.

The first file SimpleMeshTest is just a basic cube mesh with a colored material, everything imports correctly and shows that gltf has this support already in place.

The second file TextureAsMaterialTest is a gltf file that has a texture as its material diffuse. This does not work in o3de, but if you check it in a different software it does have the texture as its material color. This is one that does not work correctly yet for gltf files.

The third file ShapeKeyTest is a test for Morph Targets with the gltf format. This works like a charm if you open the animation editor select this file as the actor jump to morph targets window and drag it from 0 to 1.

The fourth file BoxAnimationTest is a test to see animations and skeletons working in the editor. This file will show you that the skeletons import correctly and the simple motion component will show that the animation is playing correctly with no issues, but the mesh does not animate with the skeleton. So meshes do not animate when imported into o3de, while the skeleton does work perfectly.

**Comment by AMZN-stankowi** [comment]
Thanks for digging into this! One of our goals with switching to AssImp for scene file processing was to enable more input scene file formats. We're only officially marking formats as supported that we've tested thoroughly. We're still digging through bugs with FBX files right now. We've enabled STL because it's a relatively straightforward format and we haven't seen any issues.

For GLTF we're waiting on a thorough test pass before marking it enabled by default, but as you've found we've made that setting data driven and you've enabled it on your end. From the bugs you've found it sounds like we don't want it enabled automatically yet, we'll need to get those bugs fixed before we can do so.

**Comment by WashedUpStudio** [comment]
Thanks for the response, I fully understand why it should not be enabled right now automatically, but from what I have found for bugs it does seem like a great candidate after a lot of the fbx issues are fixed to start up on this one as the next format.

**Comment by superkitcath** [comment]
Thanks for filling this issue! This issue was found to be for a substantial change, as part of today's sig/presentation triage session. Therefore, it should be vetted through the RFC process, under the sig-presentation [repo](https://github.com/o3de/sig-presentation/tree/main/rfcs). Please open an RFC, link it to this issue, and then close this issue. 
 
The RFC procedure can be found [here](https://github.com/o3de/rfcs#the-rfc-process).
Thank you!

**Comment by WashedUpStudio** [comment]
I will close the issue now, I wrote out an rfc here : https://github.com/o3de/rfcs/issues/42 , but one issue is it is not in the sig-presentation repo since I do not have access to write a rfc request there.

**Comment by superkitcath** [comment]
Thank you! I will look into this!
