### ISSUE TITLE
The MaterialComponentRequestBus nodes in Script Canvas require inputs which cannot have their values set

### ISSUE THREAD

**Issue by LB-TomaszSerwanski** [o3de/o3de#3072]
**Describe the bug**
Nodes from the _MaterialComponentRequestBus_ category in Script Canvas have input pins of types which cannot have their values set (i.e. _Name_, _any_). This makes modifying Material Properties in run-time impossible. 

For example, the _SetPropertyOverride_ node accepts the _MaterialAssignmentId_ (which can be obtained by using the _FindMaterialAssignmentId_ node) but it also requires the _Name_ and _any_ inputs which we haven't found a way to set a value for. 

Additionally - these nodes do not have any tooltip which could guide the User on how to use them.

Please refer to the attached video and screenshots for more details.

**To Reproduce**
1. Launch Script Canvas.
2. Create a new Script.
3. Add the _SetPropertyOverride_ node to the Graph.
4. Attempt to set a value of the _Name_ or _any_ inputs.

**Expected behavior**
Values for the data inputs on the nodes can be easily set.

**Screenshots and video**

https://user-images.githubusercontent.com/86953108/129172563-3f92ee74-5372-44a8-9910-8f577cafb3ec.mp4

![Nodes](https://user-images.githubusercontent.com/86953108/129172592-96fc9919-c5b2-4c77-9388-00d3bb888b8f.png)
ity
![Variable](https://user-images.githubusercontent.com/86953108/129172595-ba63dc6d-560d-4517-90f6-b33509089864.png)

**Desktop/Device:**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU AMD Ryzen 5 3600
 - GPU Nvidia RTX 2060 Super
 - Memory 16GB

**Comment by lsemp3d** [comment]
Moving to sig/graphics-audio, this is an issue related to a rendering scripting API. On latest development I see the Name field is a string, so that part does not appear to be a problem anymore. The only question I have is with regards to Set/Get Property Override which has an 'any' slot, it would appear the only valid configuration possible is the following:

![image](https://user-images.githubusercontent.com/58790905/143311430-8409280f-0a69-49ac-962b-d406e6dc2feb.png)

is this the intention behind these nodes? If not, the 'any' slot can be changed such that it accepts any of the valid override types.

**Comment by gadams3** [comment]
Functions have been added that allow finding the material assignment ID and working with specific data types. https://github.com/o3de/o3de/pull/3156

**Comment by LB-TomaszSerwanski** [comment]
Fix verified in Development (1e96ca4).
