### ISSUE TITLE
Support Shape Keys for FBX file format

### ISSUE THREAD

**Issue by NiklasHenricson** [o3de/o3de#3083]
**Is your feature request related to a problem? Please describe.**
It has become a bit of a standard in the gaming industry to customize avatars/actors through shape keys in body and facial features. Those initial shape keys can already be pre-defined by 3D tools (Maya, Blender, Reallusions, etc.) and are normally exported through the FBX file format (the information is carried on). 

**Describe the solution you'd like**
As it is right now. Neither Lumberyard or O3DE has anything scheduled on the roadmap for such a basic feature (almost at the same level as material editing), for character models/actors. Please consider this feature to be added at least for FBX file formats and adapted into the O3DE engine. 

**Additional context**
Example of shape keys in Blender,
<img src="https://blenderartists.org/uploads/default/original/4X/e/7/8/e78069ff66a2f0aad1efa7888b8d24c12bb85e0d.png">

Example of shape keys in Reallusions,
<img src="https://i.ytimg.com/vi/wIaNT4x032s/maxresdefault.jpg">

**Comment by NiklasHenricson** [comment]
Just to clarify... We need to access those Shape Keys from LUA as well. Supposedly developers need to create a "Character Creation" level and customize body features on their actors. We need to save those customizations as an array of numbers per Shape Key. Morph Target that is under the Motion Editor doesn't provide assistance or access to that through LUA? Or does it?

**Comment by NiklasHenricson** [comment]
Any news on this item?

**Comment by NiklasHenricson** [comment]
> This is on the animation side; sending to sig/content for triage, removing sig/graphics-audio.

Hello Cath, could you please advocate for the devs to look into this Lumberyard doc? This is exactly what we need....


https://github.com/awsdocs/amazon-lumberyard-user-guide/blob/master/doc_source/animation-editor-using-morph-targets-to-deform-characters.md

**Comment by CSteel22** [comment]
@amzn-jillich I looked into this issue on our end at the behest of @NiklasHenricson.  It appears that while the shape keys do not import directly from CC3 into O3DE properly, we can use Blender as an intermediary.  When I originally communicated our issue with Shape Keys to Niklas, the Shape Keys were distorting and creating graphical artifacts when inside the Animation Editor.  It turns out that it was an error on my part as I had "Apply Modifiers" checked on my export settings from Blender.  It needs to be unchecked.  The following is an example of what not to do:
![image](https://user-images.githubusercontent.com/35277774/140250324-de3d2c53-0582-41e0-aaf8-447bd8bd8d14.png)

**Comment by NiklasHenricson** [comment]
Thank you @CSteel22 @amzn-jillich 
Let me know if you want me to close this issue, or if you guys can proceed doing that on your own.

Sincerely,
Niklas Henricson
Epos Studios LLC

**Comment by amzn-jillich** [comment]
Thanks @CSteel22 and @NiklasHenricson , I'll close the issue.
