### ISSUE TITLE
Prefabs:  Adding entities to the level causes all other entities to deactivate/reactivate

### ISSUE THREAD

**Issue by mbalfour-amzn** [o3de/o3de#3168]
**Describe the bug**
When editing a prefab-based level, adding or removing an entity to the level causes all other entities to deactivate/reactivate.  This causes significant performance problems with the vegetation and terrain systems, since it ultimately forces a refresh of all vegetation and terrain with every entity addition and removal.

**To Reproduce**
1. Create a new prefab-based level.
2. On the 'Atom Default Environment'->'Ground' entity, add the 'Mesh Surface Tag Emitter' component
3. Create a new entity at 0,0,0
4. Add the following components:  Vegetation Layer Spawner, Box Shape, and Vegetation Asset List
5. Set the Box Shape to 50,50,50
6. In the Vegetation Asset List, set the Slice Asset to a valid asset, such as AutomatedTesting/Slices/PinkFlower.slice
7. Wait for all the vegetation to finish spawning
8. Add a new entity to the level
9. Observe all the vegetation disappearing and then slowly refreshing
10. Delete the entity from the level
11. Observe all the vegetation disappearing and then slowly refreshing

**Expected behavior**
Adding and removing entities shouldn't cause unrelated entities to refresh.

**Comment by monroegm** [comment]
This no longer repros on development at https://github.com/o3de/o3de/commit/4cde568ea4f4cfdb039664ea544d9b93367ae1b7 when adding/removing entities (I believe @AMZN-mnaumov fixed that), but it still occurs when instantiating/deleting prefabs.

**Comment by srikappa-amzn** [comment]
This is now fixed with the changes in https://github.com/o3de/o3de/pull/9795 . Closing this.

If the entity containing the vegetation spawner is modified, it'll still get deactivated and reactivated causing the vegetation to refresh. That is because the reloading logic has now been moved to a per-entity basis instead of per-prefab basis. @mbalfour-amzn , let us know if that behavior matches your expectations. If it doesn't, please open a new issue and we can explore the idea of per-component reloading. However, that does come with a few challenges and may need some design work to change existing behaviors of the current ECS system.
