### ISSUE TITLE
Implement Native Input support for Linux

### ISSUE THREAD

**Issue by spham-amzn** [o3de/o3de#3180]

**Comment by RoddieKieley** [comment]
While the addition of the mouse and keyboard input on Linux via xcb was welcome, the gamepad/joystick support is as of yet not available. In reviewing previous discussions around this issue both sdl and glfw were discussed, and with sdl being removed recently and the glfw a seemingly simpler to grok and perhaps extract while being fairly mature.

In an effort to not re-invent the wheel, I've started with an approach of creating a gem to first use glfw directly to get gamepad/joystick input on Linux with a plan to then hollow that out to just the gamepad/joystick functionality. As well glfw may lend itself to helping with #745 for wayland support. Timeline unknown however, and atm investigating an issue where the mouse cursor does not reappear when I swtich away from the windowed o3de app which is a pita.

**Comment by RoddieKieley** [comment]
For the moment when in debugging mode I simply ensure that ShowCursor always shows the cursor as per this commit on the 'HiddenCursorInDebugFix' branch in my copy of the repo at commit [758e4e6e8939e771559fc054f4b7762d4c4a4928](https://github.com/RoddieKieley/o3de/commit/758e4e6e8939e771559fc054f4b7762d4c4a4928). The behaviour was such that the cursor was hidden globally for the X window system, yet unconstrained so that I could interact with the debugger but not ascertain the cursor position until an element was lit by hovering or I clicked.

This likely should be more nuanced so that when the o3de app gives up the window focus it re-shows the cursor, but potentially still hides it when self focused and running. However this change unblocks me for the moment for the task at hand.

**Comment by RoddieKieley** [comment]
Started to scaffold this in in o3de via my [issue3180 branch](https://github.com/RoddieKieley/o3de/tree/issue3180) while also subsequently refactoring glfw to separate the joystick/gamepad processing via an [o3de_issue3180 branch](https://github.com/RoddieKieley/glfw/tree/o3de_issue3180) in that project.

**Comment by RoddieKieley** [comment]
A little long between being able to focus on this and it may be so again, however with the latest commit [466ab4c4397501ea951c40e9048f73741060dcd2](https://github.com/RoddieKieley/o3de/commit/466ab4c4397501ea951c40e9048f73741060dcd2) input is being polled and received per tick via the integrated glfw based gamepad code.

Pretty rough still but next steps will be seeing about processing the incoming input data into input channels for distribution via the event bus.

**Comment by spham-amzn** [comment]
This issue is closed from https://github.com/o3de/o3de/commit/46d1b198162084d1f089439b74b54fa5b25acdf6
