### ISSUE TITLE
MacOS Python.framework needs to patch to allow it to be notarized

### ISSUE THREAD

**Issue by lemonade-dm** [o3de/o3de#3349]
Can you fill in the @amzn-sj details about this task?

Patch Python.framework to allow it to be notarized

**Comment by amzn-sj** [comment]
The way O3DE's Python.framework is currently structured, signing it with the --deep flag does not sign all the binaries subside the framework. This is because the codesign tool expects binaries to be placed in directories with specific names. Ideally, we would want the Python framework to stick to Apple's recommended framework bundle format. However, we can't simply move/rename files and directories because dependencies found using rpath would no longer work. In the long term, we should fix this. For O3DE as an SDK, we can simply sign the binaries individually without using the --deep option. Apple recommends signing bundles inside out too.

**Comment by tkothadev** [comment]
Assuming Python is the only executable in question, we may be able to change the rpath using `install_name_tool` for the relevant python binaries so that they point to folders that work with the layout requirements.

I recently found another article for the older version of mac OSX which discussed creating a distributable version of python with a localized directory structure:
https://joaoventura.net/blog/2016/embeddable-python-osx/

It may be worth exploring this, but it likely breaks the recommended framework bundle format
