### ISSUE TITLE
Missing platform icons

### ISSUE THREAD

**Issue by yuyihsu** [o3de/o3de#3526]
**Problem description**
[Migrated from JIRA LYN-4441]
The platform info should be shown in the gem. either in an icon view or in text form.

**Solution**
 UX team already has the design to suport this. please ask for the platform icon when ready to implement this task.

**Acceptance criteria**
1. The UI should show the supported platform in each gem row. following the design here: link to be provided by @bhanuja-s

**Comment by tkothadev** [comment]
Per PR https://github.com/o3de/o3de/pull/13106, we now show the platforms using text due to reviews with Legal and UX.

![](https://user-images.githubusercontent.com/112996779/201162530-ce9b059f-b486-4a6f-a478-efe4a2432406.gif)

If later on we get approval for platform icons and want to revise this design, we can re-open this issue. Until then, closing for now.
