### ISSUE TITLE
Investigate how to implement a 'Grayscale' effect in the viewport

### ISSUE THREAD

**Issue by AMZN-Liv** [o3de/o3de#3596]
To improve feedback around what is currently 'editable' by the user in the viewport (for use in the new Prefab Isolation mode) we want to 'gray-out' and objects that are not currently interactive (cannot be clicked or selected).

This gives the user an immediate indication that a single click will have no effect.

It's not clear at the time of writing how best to achieve this effect (should it be a screen-space post-processing effect or something we could do with materials? etc..)

Some exploration and collaboration with the Atom team will be required.

**Comment by yuyihsu** [comment]
We suggested to move it to Critical because when users are handling thousands of assets, they need a way to differentiate the selected assets vs. the assets in the background. We need some kind of visual presentation to show the differences. So after discussing with Josh/Lee, we are changing this to Critical. Please let us know if you disagree.

**Comment by yuyihsu** [comment]
This ticket may be duplicated by this ticket: https://github.com/o3de/o3de/issues/3638
