### ISSUE TITLE
Feedback: Simplify the search results

### ISSUE THREAD

**Issue by alexmontAmazon** [o3de/o3de#3693]
[Migrated from JIRA LYN-5330]
*Description:*

The search results in the asset browser should be simplified to make it easier for user to find the file they are looking for.

 

*Details:*

When searching a file in asset browser, the results are returned with the folder structure, and the file would be hidden inside the folder, which make it hard to find the file that the user is looking for. The user has to open the folders one by one to make sure, which is very time consuming and not consistent to the industry standard.

To improve the experience and speedup the process, we should return only the files or folders, without showing the folder structure.

The same search behavior should work in the asset picker as well.

Question-
 - can we make this search behavior as a behavior pattern? So other areas with the search behavior can also leverage this.
 - Can we make the tagging system not hard coded so users can add their own tags?

 

 

*Acceptance Criteria:*

 

*Additional Information:*

**Comment by amzn-leenguy** [comment]
I reviewed this with Ignacio this morning and i suggested to update the following:
high:
- make sure hover states are whole row (for both asset picker modal and asset browser search results)
- name should be ascending sorted by default, and have descending sorting as state B. same for other rows.

Med:
- columns can have resizing ability
- Look into last selected state and why its not appearing
- do we have truncation ... on the filename text? and paths? if not, lets add it to qt. (this will be relevant for resizing)

**Comment by NicholasVanSickle** [comment]
@AMZN-Igarri I spoke to @amzn-leenguy who said you're actively working on iterating on the UX here, which is great! Please let me know if you need any support.

**Comment by mcphedar** [comment]
This is currently being worked on through a different ticket.

**Comment by AMZN-Igarri** [comment]
I've been working on this for a bit. I added a view to flatten the Asset Browser Entries and now I am working on how to properly differentiate between source and product entries. This is what i got for now.
![image-2021-09-10-11-02-52-023](https://user-images.githubusercontent.com/82394219/132829364-b5bfaaed-7d4d-4738-b5ce-d0798e67e262.png)
![image-2021-09-10-11-01-56-738](https://user-images.githubusercontent.com/82394219/132829384-b3d632b2-20ae-43c9-8de3-f4a3f59733fe.png)

**Comment by amzn-leenguy** [comment]
This is great @AMZN-Igarri . I'm loving how this is looking. I have a curious question: In your second screenshot, how did the script canvas tag appear? Did you type script and a dropdown suggestion appeared under the text field?

**Comment by AMZN-Igarri** [comment]
@amzn-leenguy Thanks a lot! The ScriptCanvas tag appears when you use filters by asset type in the asset browser. I used that to show that it also works fine with the String filter and AssetType Filter enabled :D

**Comment by amzn-leenguy** [comment]
Great. Are you able to show me a video of the workflow of you doing the regular use case of searching and so on, but also make a video of using the filters by asset types in the asset browser for me?

Id love to try and review and approve this asynchronously. If not, happy to sync over a call! My calendar is always open.

**Comment by AMZN-Igarri** [comment]
@amzn-leenguy here you got a quick example of a real common workflow in the asset browser
https://user-images.githubusercontent.com/82394219/133235330-d66c2879-92ea-41d7-95d6-3d04488899a3.mp4

**Comment by amzn-leenguy** [comment]
Thanks for the video @AMZN-Igarri . This makes more sense. After reviewing this, I am fine with how the workflow is going.

Feedback:
- Are you able to make the hover state across both columns still the same on the asset picker model as well? (just so its the same as the asset browser too)
- If you navigated to a section on the asset picker for e.g. physX Mesh, and then did something else, and came back, will it remember where you last left off? or does it just reset to the top again. AND what happens if you actaully did select an asset for PhysX mesh, and then clicked the folder again. Does it remember where you last were? Or does it reset again from the top?
- Do we plan to add the filter functionality to the model box as well? (just like asset browser?) Can the model picker be smart enough to know which kinds of assets are getting shown in the list there?

Suggestions for future (no need to do now, but feel free to log this down for better UX):
- Would love to have a message appear in the search area that says "No search results found."
- The user can just drag an asset from the asset browser to viewport still the same right? Nothing has changed about this?
- Do we plan to add any horizontal scroll bars? Incase the user wants to read the full path name, how can do they do this?
- Any plans for typeahead search? (google it if unknown) in the future

Great work so far. I would love for you to answer these questions as the SME right now for these. Feel free to tap @hultonha as well if there's any questions you want to leave to him.

**Comment by AMZN-Igarri** [comment]
@amzn-leenguy 

Feedback: 
- Yes, the hover state should be working out of the box in both views, I'm investigating why this isn't happening right now.
- Right now it doesn't remember where you left, for that we would need to create a some kind of QTableViewWithStateSaving (like the QTreeViewWithStateSaving for the original AssetBrowser) and it will take quite some time to get done.
- The AssetPicker already knows what kind of assets it should show just like the previous one. The type filter is getting applied in its AssetBrowserFilterModel which is the model that sits on top of the TableViewModel.

Suggestions:
- I think that would be a great idea!
- Yeah, the user can drag the asset to the Viewport and the entity inspector just as before.
- Right now the whole view fits to the available space so if the users wanted to see the whole path they would need to resize the columns which is in this PR https://github.com/o3de/o3de/pull/4087
- I think that would be a really nice addition but might be a bit out scope for this project. In fact this could be an improvement for all the SearchWidgets in the engine.

Hope this resolves your questions. If you got any more just let me know.

**Comment by amzn-leenguy** [comment]
Thanks for answering them so smoothly @AMZN-Igarri . I have no other questions or feedback. Your videos and images have provided enough feedback for me that I can consider this approved from UX. Great work!

**Comment by hultonha** [comment]
@AMZN-Igarri is this now complete with the most recent changes? Can this issue now be closed? Thanks!

**Comment by AMZN-Igarri** [comment]
@hultonha Yes this is complete now, the only thing left would be to merge the CVar flip and send the impactful change mail

**Comment by hultonha** [comment]
Okay perfect, once that is merged, and the mail is sent (happening today I take it?) let me know and we can close out this ticket 👍

**Comment by AMZN-Igarri** [comment]
The last pull request just got merged. https://github.com/o3de/o3de/pull/4370
