### ISSUE TITLE
deleting a UI canvas from script via “destroy entity and child” caused the editor to crash

### ISSUE THREAD

**Issue by monroegm** [o3de/o3de#3707]
[Migrated from JIRA LYN-4248]
– We needed to use Ui Canvas Unload instead. we should not crash the editor.

**Comment by michabr** [comment]
After some investigation, at appears this is the same issue as LYN-4599 and will just need to be verified after that general fix is in.

"Destroy Game Entity And Descendants" ends up unloading the UI Canvas correctly in the UiCanvasRefComponent's deactivate method, so the assert/crash seems unrelated to UI Canvases. Also verified that this issue is not present in slice mode.

**Comment by monroegm** [comment]
@jckand-amzn  added a comment - 25/Jun/21 12:15 PM
Repro Steps:

1. Create a new entity.
2. Add a UI Canvas Asset Ref component.
3. Assign any UI Canvas to the component, and toggle on Load automatically.
4. Add a Script Canvas component to the same entity.
5. Open a new script in Script Canvas, and add the following nodes to the graph:

On Graph Start
Time Delay
Destroy Game Entity And Descendants
6. Set the Time Delay node to a few seconds
7. Connect the On Graph Start to the TimeDelay node, and the Done on the TimeDelay node to Destroy Game Entity And Descendants.
8. Save and assign the script to the entity's Script Canvas component.
9. Enter Game Mode.
10. Once the canvas is cleared, exit Game Mode.

Expected:
Game Mode is exited cleanly.

Actual:
Editor crashes.

**Comment by Amzn-Catdo** [comment]
Verified this issue is fixed now that https://github.com/o3de/o3de/pull/4154 has been merged to dev
