### ISSUE TITLE
SC node "Request tagged entities" should be renamed and improved 

### ISSUE THREAD

**Issue by svitlani** [o3de/o3de#4060]
[Migrated from JIRA LYN-3901]
**Describe the bug**
The node "Request Tagged Entities" should be... "Get First Entity by Tag" or "Get Entity by Tag"
It only returns the first tag
This will better match the node "Get Entities by Tag" which returns a list
So we'll have "Get Entities by Tag" and "Get Entity by Tag"

This issue is a part of  GHI #3763 https://github.com/o3de/o3de/issues/3763

and GHI #2708 https://github.com/o3de/o3de/issues/2708 and will be addressed along with the work mentioned in GHIs above.

**Comment by yuyihsu** [comment]
Moving this to critical based on the RTE conversation. Jira also puts this ticket as critical.

This ticket is super critical because there are lots of inconsistent naming convention and behaviors in our SC nodes today. It has prevented users from building and iterating faster, and sometimes even blocked them from moving forward because users thought it is their problem that the scripts aren’t running. Based on what Luis told me last time, this ticket would fix all the usability problems the users are facing today. Please let me know when you plan to work on this ticket, we will need to review the SC usability again before we close this ticket.

**Comment by lsemp3d** [comment]
Merged to stabilization/2110
