### ISSUE TITLE
Spamming errors "Failed to open log file [@log@/Game.log]"

### ISSUE THREAD

**Issue by onecent1101** [o3de/o3de#4104]
**Describe the bug**
Get Spamming errors "Failed to open log file [@log@/Game.log]" while debugging o3de project on Xcode/Android Studio for iOS/Android platform.

**To Reproduce**
1. Configure and build solution for iOS/Android
2. Connect device with host Mac/PC
3. Run application
4. See spammed errors in IDE logging output

**Expected behavior**
No spammed errors, get logging message generated properly.

**Desktop/Device (please complete the following information):**
 - OS: iOS, Android

**Comment by lumberyard-employee-dm** [comment]
The change would not fix it on iOS and Android, since most likely the `@log@` alias isn't writable.
I guessing that the "user/log" directory is failing to be created in the Dev Write location on those devices: https://github.com/o3de/o3de/blob/development/Code/Framework/AzCore/AzCore/Settings/SettingsRegistryMergeUtils.cpp#L696-L703

**Comment by byrcolin** [comment]
@lemonade-dm Can we close this one out?
