### ISSUE TITLE
Buffer Memory Leak

### ISSUE THREAD

**Issue by baothientran** [o3de/o3de#4323]
**Describe the bug**
When `AZ::RPI::Model` is created and destroyed using `MeshFeatureProcessor` often. The memory goes down slowly or stop going down 

**To Reproduce**
Below is a small example that shows the leak in the Atom Sample Viewer:

[LeakExampleComponent.cpp.txt](https://github.com/CesiumGS/o3de/files/7171230/LeakExampleComponent.cpp.txt)
[LeakExampleComponent.h.txt](https://github.com/CesiumGS/o3de/files/7171232/LeakExampleComponent.h.txt)

This example allocates roughly 80 mb buffer/frame (a bit extreme) and destroy them right away. I also have a imgui to force the example to stop creating buffers; however, the memory only goes back down very little. It's possible that the FrameGraph is holding on those buffers, but I'm not sure if there are any benefits for FrameGraph to do so since they are not used anywhere

**Expected behavior**
Memory goes down when deallocating meshes

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version: 10
 - CPU: Intel Core i7
 - GPU: Nvidia GTX 1650
 - Memory: 32 GB

**Additional context**

**Comment by jeremyong-az** [comment]
Thanks for filing this @baothientran! I was wondering if I could trouble you for some more information.

Memory in DX12 (and other RHIs) are allocated in pages of committed resources, and buffers (like those associated with mesh components) are suballocated from those pages. In general, we wouldn't expect total memory usage to drop immediately after releasing buffers.

However, it's possible what you are describing is a request for a new feature, which is to release/defragment pages that are empty when over a particular memory budget. Does that sound correct to you?

Additionally, it would be appreciated if you could attach some numbers to your report to understand the sense of scale involved (how many meshes added/removed, how much memory consumed, what the desired consumption is, etc.)

**Comment by moudgils** [comment]
It seems like in your example the buffers should not be using the Page allocator and hence they should be release once the ref count hits 0 and 3 more frames has passed (as GPU can be 3 frames behind the CPU). @VickyAtAZ will take a deeper look to see who is holding on the Buffer reference in your example

**Comment by baothientran** [comment]
Hi everyone, thank you for looking into this! Below are some stat that I gather on the CPU side:

Stat for the whole run:
- The whole dataset is around 3 GB in disk space
- During the whole run in AtomSampleViewer, the Gem keeps around 512 Mb of vertex buffer alone (The actual number is around 460 Mb, but I round it up). Those numbers are in the CPU side only. It maybe larger when sending to GPU due to alignment
- There are around 460 number of buffers during the whole run. I pack all vertex attributes into one single buffer per model. So you can assume there are around 460 ModelAssets that are kept in the LRU cache. Also since I use 1 material (StandardPBR) per ModelAsset, so there are 460 materials in the cache as well. There are no textures. They are all base color.
- All vertex buffers are allocated with InputAssembly and ShaderRead flags, which like @moudgils says, it doesn't seem to use page allocator behind the scene

Stat per frame:
- There are 5 - 11 buffers allocated per frame (also depend on if the model is in the camera view).
- Common buffer size is around 0.5 Mb - 1.5 Mb.
- For deallocation, there are  5-10 buffers deallocated depend on if the cache is full. But it can happen often and usually around that number

Total memory usage report by visual studio is 12 GB and keep increasing. In some cases, it will be out of memory, which doesn't trigger out of memory exception. It usually logs error saying no vertex buffer/material shader group can be created

Please let me know if you need more info

**Comment by moudgils** [comment]
We have an internal ticket to track if we can move IA buffers back to using pages. At the moment this was disabled as IA buffers needed the ShaderRead flag in order to be accessed for Ray Tracing shaders and that caused other alignment issues. Adding @dmcdiarmid-ly  for better context.

**Comment by VickyAtAZ** [comment]
I have done some digging and I found a major issue which causes memory leaking (both cpu and gpu). 
So the RPI::Buffer, RPI::BufferAsset and RHI::Buffer are all released properly. The leaking is with DX12 backend in the AsyncUploadQueue's implementation. The ID3D12CommandAllocator wasn't reset which lead to dx12 objects leaking when record and execute command list for uploading buffer (or image) data to GPU. 
I am preparing a PR with the fix. 

Another thing I want to mention is that you may see a CPU memory increase (around 160M) the first time run your test code, and this is expected behavior. It's because in your code, you creates a 80M buffer to create asset which the asset make a copy with that buffer which ends up to 160M. Since they are using AZStd::vector for the buffer. The system allocator (HpAllocator) will grow its allocation tree to allocate these two big chunk of buffer. So even these buffers got released. The system allocator is still keep allocated trunk there and just mark them as available. 
So if you trigger the creation again, you won't see another increase since the system allocator will have the trunks ready which they don't need to do the actually allocation again.

**Comment by VickyAtAZ** [comment]
PR: https://github.com/o3de/o3de/pull/4444

**Comment by baothientran** [comment]
Thanks @VickyAtAZ and everyone! I can confirm this fix the issue
