### ISSUE TITLE
ImGUI CPU Profiler window has focus issues

### ISSUE THREAD

**Issue by LB-ArturSiewniak** [o3de/o3de#4366]
**Describe the bug**
The **ImGUI CPU Profiler** seems to lose focus on certain actions, these are:
* Holding Right-Mouse Button and moving the mouse to move the **Visualizer** graph.
* Scroll the Mouse Wheel to scroll through the **Visualizer** graph.
* Typing into the **Statistics Filter** Text Field is not possible, even though it's selected.

It should be noted that e.g. holding Left-Mouse Button on the slider and moving it by hand works to scroll the **Visualizer**/**Statistics**. Scrolling Mouse Wheel in the **Statistics moves** the list, and all buttons seem to be responding fine. If the input has an equivalent in the Viewport and the user performs any action listed above, it will be executed as well (e.g. if the Mouse Wheel is scrolled, the Viewport Camera will zoom in and out).

**To Reproduce**
1. In the Viewport, press the Home key to bring up the ImGUI.
2. In the **ImGUI** go to **Atom Tools** > **Cpu Profiler**.
3. Press **Swap to visualizer** button and then the Pause button.
4. Attempt to move the graph by holding the Right-Mouse Button and moving the mouse.
5. Attempt to scroll through the graph using the Mouse Wheel.
6. Press **Swap to statistics** button.
7. Select the **Filter** text field and attempt to type something in.

**Expected behavior**
The **ImGUI CPU Profiler** window is focused correctly.

**Video**

https://user-images.githubusercontent.com/86952082/135066939-077b3966-e6a3-4ad0-920e-83bf8c5e8313.mp4

Desktop
Device: PC
OS: Windows
Version 10
CPU AMD Ryzen 5 3600
GPU NVIDIA GeForce RTX 2060 SUPER
Memory 16GB

**Comment by LB-ArturSiewniak** [comment]
Some of the issues still occur on the Development (798a847) build. Mouse Wheel scrolling does not work in the Visualizer menu, and while the input is registered in the Filter text field, it is not consumed and is still being forwarded to the Viewport. Please refer to the attached video (ImGUIFocus.mp4). Should this issue be reopened, or should a new one, mentioning only these issues, be reported instead?

https://user-images.githubusercontent.com/86952082/146798838-93269213-a083-4a7f-a523-283ab8875b05.mp4

**Comment by AMZN-ScottR** [comment]
Hi @LB-ArturSiewniak,

The mouse wheel not working in the visualizer is by design and doesn't work in the client launcher either, so that would be considered a feature request.  

As for the text/key input consumption, that's a trickier answer.  In the client launcher, text and key events are sent independently of each other so neither can consume the other.  The behaviour currently implemented in the editor matches that, so what you are seeing is technically by design.  Going to consult @bosnichd and/or @hultonha to get their thoughts on if editor events should get special treatment here.
