### ISSUE TITLE
Channel Packing

### ISSUE THREAD

**Issue by NiklasHenricson** [o3de/o3de#4746]
**Is your feature request related to a problem? Please describe.**
Missing out channel manipulation on textures with multiple channel data.

**Describe the solution you'd like**
Each texture file is made up of either 3 or 4 channels. Each channel is made up of a grayscale dataset. This is normally represented as RGB or RGBA (Alpha).

Some textures such as the Color (Diffuse/Albedo/etc.) need at least the 3 channels to function, but many others (Metallic/ Roughness/ Bump/) are a greyscale image and can be represented as a single channel of data. 

In the case of Normal maps, most games engines do not need the blue channel of data. I am not sure of how O3DE handles Normal map channel data. 

Instead of loading individual texture files complete with their 3+ channels into the games engine for each texture, it makes sense to allow the design team easy access to the function of each individual channel separately.

In the material editor, just below the “Texture” dialogue box, there can be a “Channels” section. 
R/G/B/A/ can all be laid out, with an “On/Off” tick-box, and an “Invert” tick-box.

For a Color texture RGB will all be ticked on. Metallic and  Roughness can import the same texture, but only tick on the channel which matches the requisite texture as required. If the model is White=Hot or Black=Hot, this can be easily flipped with the “invert” tick-box as needed. 

The Normal Map can be loaded up Using R and G, and the G can be inverted as needed depending on how the normal map was made. The B channel can be used for a bump map completely separately.

**Comment by Irishlostboy** [comment]
Hi, I wrote this request to our team leader. I am looking for arbitrary channel control, as much as possible, so artists can pack their channels in whatever means is most optimal in their specific use cases. The method described is one I have seen in effective use in other engines. In O3DE, I do not know if the blue channel is being used from the normal map. Some engines seem to ignore the blue channel. If the blue channel is being used, the suggestions for the normal map can be ignored, but over-all I am looking for a way to make more efficient use of colour channels. having a 3 channel texture for a single channel's worth of information is wasteful. I hope this clarifies my request somewhat. Thanks for you time.

**Comment by santorac** [comment]
Just to make sure I understand...

You are looking for general purpose flexible texture packing, so instead of sampling separate texture assets at runtime it samples a packed texture once and extracts various data from each channel. The conversation above kind of started focusing on normal maps, but that's just one example; you generally want to be able to find unused texture channels and pack other grayscale data into those channels as you see fit.

It seems the conversation got confused a bit by statements like "having a 3 channel texture for a single channel's worth of information is wasteful". If I understand correctly, it's not the _storage_ of data that is wasteful, because as others pointed out the asset processor does strip out unused channels and compresses things down so that a grayscale map is stored in an image asset with a single channel, a normal map is stored in an image asset with two channels, etc. The thing that's wasteful is the texture _sampling_ done on the GPU: we sample one texture to get single grayscale channel, sample another texture to get two channels, etc. We would get better performance if we just sample one texture and collect several pieces of data from it.

As Vicky was pointing out, the texture compression schemes tend to work better when you don't pack data like this. You'll likely get higher quality results by not packing data together. But to your point, this is a personal decision for each game team as the optimize for quality vs speed.

**Comment by santorac** [comment]
All that being said, texture packing is something that @HogJonny-AMZN and I have talked about many times. We recognize that this needs to be supported in some fashion, and we have a task on our roadmap to take a closer look and come up with a design.

We aren't sure yet how flexible we think it should be though. At the most flexible, it would be something like you describe where the user can pick any channel from any texture. And at the other end of the spectrum, it could be just support a few commonly used schemes like BaseColor-Opacity, Occlusion-Roughness-Metallic, etc. Obviously having maximum flexibility is desirable from a user perspective, but might also come at the cost of complexity and potential performance costs that come from additional shader permutations. It definitely needs more thought.

**Comment by santorac** [comment]
@NiklasHenricson and @Irishlostboy ...

1. Will your image sources already have the channels packed together? Or would you expect the Asset Processor to automatically combine images and pack them for you?
2. Would you be able to provide a list of texture all the packings combinations that you predict you will need on your project?
3. How comfortable would you be with making a custom .materialtype? If you can identify a few packing schemes that you'll use throughout your project, it might be reasonable to just make your own variation of StandardPBR.materialtype that does the packing you want. I could help provide some guidance on this.

**Comment by HogJonny-AMZN** [comment]
FWIW - This has been anticipated and on the roadmap for a very long time, it's bee discusses at several points in development.

"So could you please let me know why not do a fundamental basic feature as this in O3DE? It's been around in the gaming industry as well in Adobe tools since early 2000's"

Fundamentally the core features are in place that would allow for this (like forking standardPBR and implementing the texture packing strategy that matches your content), the reason it hasn't been done yet mostly comes down to resourcing and priorities.  It has not been urgent yet. The community needs to help take on the work that is valuable to the community.  We are hear to help make that happen.

I think that we can do this in several increments ... for instance start with the most common packing which we already know would be useful for gltf support, which would be ORM.  https://www.khronos.org/blog/art-pipeline-for-gltf

It needs to remain flexible that teams can decide what approach makes the most sense for their game and production:

Split textures:
- better compression and thus quality
- in many situations might be better for pre-vis and early production 

Packed textures:
- manage memory footprint vs quality
- may also reduce texture fetches?
- many apps such as 'Substance Designer' have configurable texture packing, so from the upstream content side of things this can be 'automated'.  https://substance3d.adobe.com/documentation/integrations/generated-textures-packing-170459638.html

We have to deal with how the channels are treated and fetched, for instance if you put something_ORM.png image into the asset folder it's most likely to cook as 'a color image' ... on the shader side we need to be working with linear data. 

I think there are in fact a number of directions that could be taken

0. custom_packed_PBR.materialType and shaders
- alter to fetch from packed textures 
- more work for the customer team but also gives them full control to optimize their content pipeline

1. Any texture asset field could have a channel selector pulldown (RGB, RGBA, R, G, B, A)
- most flexible / generic / would support most strategies
- all the work would mainly be in the materials and shader system
- lots of shader variations and permutations possible
- will add a lot of additional controls all over the material reflection (UX concern)

2. Data-driven configurable texture packing
- TA/TD defines the texture packing schema for the project (some kind of map, probably json)
- The material has one pull down, to switch from 'split textures' to 'packed textures'
-- could extend this
- We might want/need new 'image processor' profiles, example _pbr_orm.png
-- Need to make sure that we fetch the linear values properly
--- they either are linear in the cooked texture
--- or they are transformed when fetched
- set up your texture packing in Substance, specify the same schema for your O3DE project

3. Asset Processor and packaging
- Artists can work with 'split textures' in look dev and early production cycles
- Asset processor can pack textures and deliver the most optimal downstream runtime assets

IMO long term I would recommend doing both 1) and 2) in that order to because the second could just hide the granular controls and operate the underlying properties (from UX, material reflection). 

We will also need to consider future conversations like what that ideal way is for end users to work with packed-textures in something like a 'Material Graph'.?  If the 'Shading model' (standardPBR) is just the primary node you connect texture channel(s) data into in a graph UX experience, then what you are fetching and how it's transformed happens before feeding the shading model.   Whatever we do now, should also be in preparation of that direction?

**Comment by HogJonny-AMZN** [comment]
We should look at both the front end (asset ingress) and the output (runtime) happy paths.
And we must consider what this means in the end-to-end content process/pipeline.
For example this guide suggests that when generating glTF asset exports from Blender, that the input textures are already packed (in a image app like photoshop or gimp), while suggesting that if using 3dsMax as the exported that you retain 'split textures'.  This is just evidence that teams should pick both the process and formats that make them most efficient.   https://www.khronos.org/blog/art-pipeline-for-gltf

But there is good reference in there of 'material graphs', it's common in many graph style editing to have a 'image read' node that allows how a texture is interpreted to be set such as 'Color' vs 'Non-Color' data (and ensure it's linear in the render pipe.)

1. I think we should consider starting with 'remixable materials' so most of the .materialType and shaders can share as much as possible.

2. Have a gltf_metalrough_packed_PBR.materialType that just utilizes the gltf schema

This would be a good first approach specific to unblocking gltf, and we can always continue to improve 'data-driven texture packing' as a more generalized feature.

**Comment by Irishlostboy** [comment]
Thank you all for taking a look at this feature. From an asset artist's point of view, the advantage of being able to pack channels starts within Blender (or whatever mesh editor) as I can have my textures working in Blender much the same as I would within the game editor. Having channels packed lowers the pressure on my computer. I just finished a basic 2k texture for a tiled roof. With colour, height, normal, AO, and metal maps, they were nearly 200mb as 16 bit tif. (sure, which ones get put to 8 bit, or downscaled is another discussion, I just tend to use 16 bit 2k as a starting point. Old guy habit) With channel packing I can nest 3 into 1 (4 counting the alpha channel) and significantly reduce the pressure on my machine before it even goes near the engine. 
I am looking forward to seeing what system you come up with for giving more access to texture channels to the artists and designers. We appreciate your work in making these tools which we use.

**Comment by HogJonny-AMZN** [comment]
@Irishlostboy good insights ... I know from experience that sometimes it is easiest when working with some applications like Substance Designer to just select one image file format type and use it for everything (all generated textures 16-bit .png, lots of harddrive space).

Also understood that some teams will set up automated 'texture packing' in the material process/workflows/pipelines.  And Substance supports this well.

However, there are other approaches teams take, like mapping all textures for a single material into layers of a PSD file.

Ideally we can support the many ways of working that various studios like as best practice.

That said, focusing on how to get to 'packed textures' in a manner that supports the glTF schemas/formats, is a good forcing function and place to start and ideally gives us one more layer of abstraction and data configuration that will make it easier to add other configurations moving forward.

**Comment by NiklasHenricson** [comment]
@HogJonny-AMZN @santorac @Irishlostboy @jeremyong-az @superkitcath 

Do we close this issue, or do we keep it open for potential changes? What's the process?

**Comment by santorac** [comment]
I would think we keep this open until someone writes an RFC for the feature, then we can close it? Not sure.
@wintermute-motherbrain 

We also have an internal task to work on this feature, and I linked that task to this GHI.

**Comment by superkitcath** [comment]
Yes, we should leave it open until then, thanks!

**Comment by wintermute-motherbrain** [comment]
The sig has accepted this RFC into the backlog.  For details on potential implementation strategy, please see this ticket: https://github.com/o3de/o3de/issues/5211

**Comment by gadams3** [comment]
Even though material canvas is still under construction and the current material template is experimental, you can create new material templates and types, sample 2D textures, interpret, and connect texture color channels to as described.
