### ISSUE TITLE
[macOS] Processing iOS assets by Asset Processor takes an excessive amount of time

### ISSUE THREAD

**Issue by LB-MateuszSzweda** [o3de/o3de#4818]
**Describe the bug**
Processing iOS assets for the Automated Testing project by the macOS Asset Processor takes up to 5 hours on a Macbook Pro 2017.

Please note that processing the same assets, but only for the macOS platform takes up to 40 min.

For further information please refer to the Asset Processor output log.

[macOS iOS assets asset processor log.txt](https://github.com/o3de/o3de/files/7381569/macOS.iOS.assets.asset.processor.log.txt)

**Prerequisites**

* Asset Processor and Editor were configured and built on macOS.
* AutomatedTesting was set as the active project.

**Steps to reproduce**

1. Go to _o3de/Registry_ directory and uncomment the iOS platform in the _AssetProcessorPlatformConfig.setreg_ file.
2. Run the following command in the terminal:
 _/Users/<home folder name>/o3de/osx_build/bin/profile/AssetProcessor.app/Contents/MacOS/AssetProcessor --project-path=AutomatedTesting_ command in terminal.
3. Wait for the assets to finish processing.

**Expected behavior**
iOS assets are processed by the Asset Processor within 2 hours.

**Actual behavior**
macOS assets are processed within 40 minutes whereas iOS assets take 5 hours to process.

**Found in Branch**
Development (064a72b)

**Desktop/Device:**
- Device: Mac
- OS: macOS
- Version: Big Sur 11.3.1
- CPU: Intel Core i7 2,8 GHz
- GPU: Radeon Pro 555
- Memory: 16GB

**Comment by lawsonamzn** [comment]
So the stats tracking I added revealed some interesting stats after repeated runs.  To get these stats, I tried a few different runs as follows.  On a new empty project (So all gems and stuff), each test was done with batch AP + no cache folder to start.

* Ran AP with 11 builders set to idle priority
```
Total Assets Processing Time: 2155.644043s
Time to process a 4k texture: 21m15s633ms
```

* Ran AP with 4 builders set to idle priority
```
Total Assets Processing Time: 2153.604004s
Time to process a 4k texture: 08m38s614ms
```

* Ran AP with 11 builders set to normal priority
```
Total Assets Processing Time: 2003.277954s
Time to process a 4k texture: 19m30s726ms
```

* Ran AP with 4 builders set to normal priority
```
Total Assets Processing Time: 2164.254883s
Time to process a 4k texture: 08m48s494ms
```

* Ran AP with 24 builders (many more than I have cores) set to idle priority
```
Total Assets Processing Time: 1980.998047s
Time to process a 4k texture: 26m37s627ms
```

Note that I also tested compiling the texture compressor with AVX2 and SSE2 instead of just native (like it is now for mac) and the performance gains were roughly 30-40% so thats definitely worth doing.

What this basically illustrates is that despite there being huge thread contention, and a big difference in "individual time" of any given specific asset in a situation where many threads are launched, the actual completion time (how long it takes to process the entire cache) is fairly consistent regardless of how many threads and what the "nice value" is.

REcommendations:
* recompile the texture compressor with SSE4.x support across the board (the engine already requires this anyway).
* Slightly reduce thrash by launching "num physical cores-1" builders instead of "num logical cores-1"
* (Longer term) Allow builders to indicate they are able to take advantage of multithreading (not all can), and if they do, launch fewer jobs in parallel to those jobs so as to reduce context switch/contention.

**Comment by lawsonamzn** [comment]
Note that nearly 100% of the time was spent in image compression
```
AssetProcessor:     Time: 02h08m48s060ms, Count:   96, Average:    01m20s500ms, EventName: ProcessJobsByJobKey,TIF Atom Compile
AssetProcessor:     Time: 01h26m19s795ms, Count:   13, Average:    06m38s445ms, EventName: ProcessJobsByJobKey,EXR Atom Compile
AssetProcessor:     Time: 01h24m46s546ms, Count:  625, Average:       08s138ms, EventName: ProcessJobsByJobKey,PNG Atom Compile
AssetProcessor:     Time:    13m53s394ms, Count:  115, Average:       07s246ms, EventName: ProcessJobsByJobKey,Shader Asset
```

**Comment by lawsonamzn** [comment]
So with the above merged the performance on mac (x64) should be equivalent to the performance of PC (x64) given the same number of cores, cache, and memory.   

Note that IOS and Android are going to be slower to build for both on mac and PC, since ASTC-encoding is slow in general, even using all threads and all cores.

Hopefully with this patch though, it can improve somewhat.  The only other recourse seems to be to do things like reduce texture size and/or compression quality, which I may investigate next.

**Comment by LB-MateuszSzweda** [comment]
Today it was verified that unfortunately performance did not improve much for OSX on both Development (7975629) and
Stabilization_2110 (99d0c39) builds.
The processing time for AutomatedTesting iOS assets on Macbook Pro 17 (2017) with Intel Core i7 2,8 GHz is still about 4 hours.
PC with a Ryzen7 2700X CPU processed them in about 5 minutes.
Currently we do not have access to OSX machines with better CPUs but as soon as machine with M1 chip will become available it will be checked against it.

**Comment by lawsonamzn** [comment]
> PC with a Ryzen7 2700X CPU processed them in about 5 minutes.

Is this PC Processing assets for IOS, or is it PC processing assets for PC?
IOS assets require ASTC compression which takes a lot longer in general.  So to get comparison times in the same area you'd have to use AssetProcessorBatch with the
```
/platforms=ios
```
switch to make it compile for ios, instead of the default (compiling for directx12) which uses a different faster image compression.

I'll do some measurements, I want to see what the difference is between PC compiling for IOS, versus a similar mac compiling for IOS.  I have a similar mac and pc (both 6-core HT intel i7s) so I would expect the total time to be similar if they are both using ASTC.

**Comment by lawsonamzn** [comment]
Yes, there's definitely something else wrong here.
Here's 2 compiles of the same texture, both **for** ios platform, but one on PC, and one on Mac hardware.  Both machines have eqiuvalent CPUs (core i7 12 core) same amount of ram and both are using the SSE4.1 library for ASTCEnc:
```
Mac, Intel Core i7, 12 core:

AssetBuilder: Running processJob task
AssetBuilder: Source = /Volumes/Lumberyard/o3de-repos/o3de/Gems/Atom/TestData/TestData/Textures/TextureHaven/4k_castle_brick_02_red/4k_castle_brick_02_red_hp_bc.png
AssetBuilder: Platform = ios
Info: Performing image conversion: /Volumes/Lumberyard/o3de-repos/o3de/Gems/Atom/TestData/TestData/Textures/TextureHaven/4k_castle_brick_02_red/4k_castle_brick_02_red_hp_bc.png
Image Processing: Step [ConvertToLinear] took 1.805000 seconds
Image Processing: Step [Mipmap] took 15.018000 seconds
Image Processing: Image [2048x2048] was compressed to [BC1] format by [CTSquisher] in 1.198 seconds
Image Processing: Image [2048x2048] was compressed to [BC1] format by [CTSquisher] in 1.647 seconds
Image Processing: Step [ConvertOutputColorSpace] took 8.128000 seconds
INFO: Unable to find low weight encoding within search error limit
Image Processing: Image [2048x2048] was compressed to [ASTC_6x6] format by [ASTCCompressor] in 965.183 seconds
Image Processing: Step [ConvertPixelFormat] took 965.198000 seconds
Image Processing: Image [2048x2048] [ASTC_6x6] converted with preset [Albedo] [/Volumes/Lumberyard/o3de-repos/o3de/Gems/Atom/Asset/ImageProcessingAtom/Assets/Config/Albedo.preset] and saved to [/Volumes/Lumberyard/o3de-repos/o3de/AutomatedTesting/user/AssetProcessorTemp/JobTemp-MnCkQx] (2497600 bytes) taking 991.178000 seconds
S: 0 errors, 0 warnings

Windows, Intel Core i7, 12 core:
AssetBuilder: Running processJob task
AssetBuilder: Source = D:/o3de_repos/o3de/Gems/Atom/TestData/TestData/Textures/TextureHaven/4k_castle_brick_02_red/4k_castle_brick_02_red_hp_bc.png
AssetBuilder: Platform = ios
Info: Performing image conversion: D:/o3de_repos/o3de/Gems/Atom/TestData/TestData/Textures/TextureHaven/4k_castle_brick_02_red/4k_castle_brick_02_red_hp_bc.png
Image Processing: Step [Mipmap] took 6.746000 seconds
Image Processing: Image [2048x2048] was compressed to [BC1] format by [CTSquisher] in 0.411 seconds
Image Processing: Image [2048x2048] was compressed to [BC1] format by [CTSquisher] in 0.363 seconds
Image Processing: Step [ConvertOutputColorSpace] took 1.743000 seconds
Image Processing: Image [2048x2048] was compressed to [ASTC_6x6] format by [ASTCCompressor] in 19.563 seconds
Image Processing: Step [ConvertPixelFormat] took 19.574000 seconds
Image Processing: Image [2048x2048] [ASTC_6x6] converted with preset [Albedo] [D:/o3de_repos/o3de\Gems/Atom/Asset/ImageProcessingAtom/Assets/Config/Albedo.preset] and saved to [D:/o3de_repos/o3de/AutomatedTesting/user/AssetProcessorTemp/JobTemp-aUSQDg] (2497600 bytes) taking 28.627000 seconds
S: 0 errors, 0 warnings
```

28 seconds vs nearly 1000 seconds.  Something is wrong.   But what?

**Comment by lawsonamzn** [comment]
I figured it out.  The mac version of the ASTC library is compiled in debug mode.  I will need to issue a new package.

**Comment by lawsonamzn** [comment]
A fix for the package is being prepared here
https://github.com/o3de/3p-package-source/pull/72
A fix for the o3de source to use the new package is forthcoming

**Comment by lawsonamzn** [comment]
this is now live in Development
