### ISSUE TITLE
Terrain_re:Invent_Bug - Game launcher fails to load if Terrain Gem is enabled for the project

### ISSUE THREAD

**Issue by jckand-amzn** [o3de/o3de#5226]
**Describe the bug**
Game launcher fails to load if Terrain Gem is enabled for the project

**Steps to reproduce**
1. Install the latest build from https://o3debinaries.org/stabilization-2110/Latest/Windows/o3de_installer.exe
2. Create a new project
3. Build the project (necessary workaround for another issue where Gems can't be immediately added to a new project)
4. Add the Terrain Gem to the project, and rebuild
5. Load <GameProject>.GameLauncher.exe (may need to pre-launch the AP due to #5224)

**Expected behavior**
Launcher runs without issue.

**Actual behavior**
Launcher fails to open. The process will be open in Task Manager, however no window ever appears and no icon ever appears on the taskbar.

**Found in Branch**
stabilization/2110 installer

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version: 10 - 20H2
 - CPU: Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz   2.90 GHz
 - GPU: RTX 2080
 - Memory: 32.0 GB

**Comment by jckand-amzn** [comment]
[terrain_launcher_logs.txt](https://github.com/o3de/o3de/files/7464314/terrain_launcher_logs.txt)

**Comment by jckand-amzn** [comment]
This looks to possibly be the relevant portion of logs:

`==================================================================
Module Manager: Trace::Error
 D:/workspace/o3de/Code/Framework/AzCore/AzCore/Module/ModuleManager.cpp(608): 'void __cdecl AZ::ModuleManager::HandleDependencySortError(const class AZ::Outcome<void,struct AZ::Entity::FailedSortDetails> &)'
Module Manager: Modules Entities cannot be activated.

Component 'TerrainSurfaceDataSystemComponent' is missing another required service: 0x1d44d25f
Module Manager: ==================================================================`

**Comment by mbalfour-amzn** [comment]
@jckand-amzn did you also enable the SurfaceData Gem?  Or just Terrain?  The required service that's missing is the "SurfaceDataSystemService".

**Comment by mbalfour-amzn** [comment]
Looking further, this appears to be a bug with O3DE Project Manager.  Gems that are listed as enabled with a greyed-out switch because they're a dependency, like SurfaceData or Vegetation, don't seem to appear in the enabled_gems.cmake file for the project.  Somehow they're still showing up in the Editor, but this is probably why they don't show up in the Launcher.

**Comment by AMZN-alexpete** [comment]
The new system is a bit different and only the selected "top" level gems need to be in the enabled_gems.cmake file and dependencies should automatically be pulled in based on what is declared in the CMakeLists for those gems.  For example, in the default template's enabled_gems.cmake only Atom is listed and not all the gems Atom depends on, note also that LmbrCentral is missing from there.  

In this case, it appears that the dependency on SurfaceData in the Terrain gem's CMakeLists.txt resolved to a dependency on the SurfaceData static.lib, so the dll wasn't getting built and because it wasn't a runtime_dependency, it was also not getting loaded at runtime. I think we just need to add a BUILD_DEPENDENCY and RUNTIME_DEPENDENCY for SurfaceData in the CMakelists.txt for Terrain (and GradientSignal while we're at it).  I'll post a review that uses variants to get feedback on that approach.

We may also need to do another once over on the gems to verify the dependencies, I suspect we have other gems related to this.

**Comment by jckand-amzn** [comment]
I'm hitting this issue again outside of Terrain on the latest installer build:

```
Module Manager: 
==================================================================
Module Manager: Trace::Error
 D:/workspace/o3de/Code/Framework/AzCore/AzCore/Module/ModuleManager.cpp(621): 'void __cdecl AZ::ModuleManager::HandleDependencySortError(const class AZ::Outcome<void,struct AZ::Entity::FailedSortDetails> &)'
Module Manager: Modules Entities cannot be activated.

Component 'AtomLyIntegrationCommonFeaturesSystemComponent' is missing another required service: 0x6398eec4
Module Manager: ==================================================================
```

**Comment by AMZN-alexpete** [comment]
The fix for this issue has been submitted to stabilization/2110
