### ISSUE TITLE
[GNU/LINUX] Grid snapping and angle snapping not exact digits

### ISSUE THREAD

**Issue by Magical10240** [o3de/o3de#5298]
**Describe the bug**
Enabled grid snapping and angle snapping digits is `0.4` sometimes not exact digits `0.39999913` this is a bug

**Screenshots/Video**

https://user-images.githubusercontent.com/17591539/140290148-3926c865-36a8-4b4a-a311-902d41173554.mp4

https://user-images.githubusercontent.com/17591539/140290177-a9787659-a64c-4e5a-b2a1-76c8800c16cb.mp4

**Found in Branch**
stabilization/2110 5a0b6314e4da5446e8888bff7344203e73e09bd8

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Xubuntu
 - Version: 20.04.03 LTS
 -  CPU: AMD 3 3100
 - GPU: AMD 5500 XT [Mesa 21.0.3]
 - Memory: 16GB

**Comment by hultonha** [comment]
@Magical10240 Thanks for raising this but this technically isn't a bug, this is just a limitation of floating point numbers.

They cannot always represent exact values (e.g. with `0.4`, the closest 32 bit representation is is either `0.3999999761581421` or `0.4000000059604645`. One option in the Editor would be to have the display round to a smaller number of significant digits, the problem is then you technically hide what's actually happening, so it's a tough call on what the best option is sometimes...

There are some fantastic posts about floating point math here which are worth reading to learn more about the topic - https://randomascii.wordpress.com/2012/01/11/tricks-with-the-floating-point-format/ and https://randomascii.wordpress.com/2012/02/25/comparing-floating-point-numbers-2012-edition/ to name a few).

It might be worth looping in UX to get their take on this, the underlying logic itself though is sound (after having watched the attached videos, thanks again for including them! 👍)
