### ISSUE TITLE
Irregular entity motion when using offset in PhysX Collider

### ISSUE THREAD

**Issue by MoMoPF** [o3de/o3de#5898]
**Describe the bug**
When I set the Offset in the PhysX Collider component to make the entity and the collider separated, the collision seems to be confusing that the entity may make irregular circular motions when it collides with the plane while it is just affected by gravity.
I thought the offset just determines the real position of collider and it won't change the motion. Is it a bug or my misunderstanding?
 I'm looking forward to receiving answers about it. Thanks.

**Attachments**
Attach the Jenkins job log as a .txt file and any other relevant information.

**Additional context**
The way to recurring this problem:
Step 1:
1. Create an entity which works as ground
2. Add a PhysX Collider component to the entity and set the shape to box.
![image](https://user-images.githubusercontent.com/49116245/143193950-b5e3f2e0-c1dd-4bb9-ab3b-68cabd3e922a.png)

Step 2:
1. Create another entity which works as a dynamic rigid body
2. Add Mesh component to the entity and choose suitable Mesh Asset
3. Add a PhysX Collider component to the entity and set the Offset to some value where I set X to 5.0
4. Add a PhysX Rigid Body component to the entity, enable gravity and set the Z velocity to -5.
![image](https://user-images.githubusercontent.com/49116245/143194816-6bb3131a-0058-4cd1-84c4-b696aea57ebe.png)
![image](https://user-images.githubusercontent.com/49116245/143522767-24358b1f-b656-4b76-b9bd-b6c8ce14c5f9.png)

Step3:
1. Press Ctrl + G
2. Watch the simulation and you will find that the entity move in circle after colliding with the ground while it should make linear motion. Finally, it move in a strange way.
3. If I didn't set the Offset in the PhysX Collider component, the motion becomes normal which is linear along the Z-axis.
![image](https://user-images.githubusercontent.com/49116245/143522874-16ac8508-fc7b-4bb5-8e34-995d467ee6e8.png)

**Comment by greerdv** [comment]
Apologies for the delay in responding to this issue, looks like we didn't spot it because it was missing some labels.

In the screenshots it looks like you have a mesh asset collider for the collider component where you're applying the offset. If you do that it will mean the collider won't align with the render mesh which will affect how the collision behaves. It also looks like you have compute COM enabled on the rigid body component, which means that the centre of mass will automatically be updated based on the size and position of the colliders attached to that rigid body, which will also affect the simulation. If you enable the collider debug draw or turn on PhysX debug (physx_debug 1 at the console when the PhysXDebug gem is enabled) you will be able to see the collision geometry as it appears to the physics simulation.

The collider offset is generally not that useful for asset type colliders since they will be generated from the assets in such a way that they appropriately align with the render mesh, which is usually what is desired. The position and rotation offsets are mostly intended for when manually creating primitive colliders and needing to align those with the visual mesh.

**Comment by MoMoPF** [comment]
> Apologies for the delay in responding to this issue, looks like we didn't spot it because it was missing some labels.
> 
> In the screenshots it looks like you have a mesh asset collider for the collider component where you're applying the offset. If you do that it will mean the collider won't align with the render mesh which will affect how the collision behaves. It also looks like you have compute COM enabled on the rigid body component, which means that the centre of mass will automatically be updated based on the size and position of the colliders attached to that rigid body, which will also affect the simulation. If you enable the collider debug draw or turn on PhysX debug (physx_debug 1 at the console when the PhysXDebug gem is enabled) you will be able to see the collision geometry as it appears to the physics simulation.
> 
> The collider offset is generally not that useful for asset type colliders since they will be generated from the assets in such a way that they appropriately align with the render mesh, which is usually what is desired. The position and rotation offsets are mostly intended for when manually creating primitive colliders and needing to align those with the visual mesh.

Thanks for replying. Maybe I have understood what is happening when I changed the offset. The physical simulation is based on the collider, so when I change the offset of collider, there is some distance between collider and mesh. The motion of collider is absolutely correct but when rendering mesh, some errors occur for reason of the distance. I think the relative location  between collider and mesh is fixed when rendering. This may explain the phenomenon.  Is it right? Thanks.

**Comment by greerdv** [comment]
Yeah, during simulation the render mesh and the collider are both fixed relative to the entity. The collider offset allows you to change where the collider will be created relative to the entity. That can be useful in order to make a primitive collider align with a render mesh, but if you're using an asset collider rather than a primitive collider (sphere, capsule, box), the render mesh and collider should already be aligned when the asset collider is created by the asset processor.  

There was a workshop at the O3DE conference a few months ago which you might find helpful - it covered a bunch of physics topics, including colliders and offsets https://www.youtube.com/watch?v=NDfJiETcBYo.

**Comment by MoMoPF** [comment]
> Yeah, during simulation the render mesh and the collider are both fixed relative to the entity. The collider offset allows you to change where the collider will be created relative to the entity. That can be useful in order to make a primitive collider align with a render mesh, but if you're using an asset collider rather than a primitive collider (sphere, capsule, box), the render mesh and collider should already be aligned when the asset collider is created by the asset processor.
> 
> There was a workshop at the O3DE conference a few months ago which you might find helpful - it covered a bunch of physics topics, including colliders and offsets https://www.youtube.com/watch?v=NDfJiETcBYo.

Thank you very much!
