### ISSUE TITLE
[macOS] First launch of a project causes permissions check for AccessibilityAccess

### ISSUE THREAD

**Issue by lmbr-pip** [o3de/o3de#6032]
**Describe the bug**
On first launch of GameLauncher on bigSur, was unexpectedly asked to approve accessibility access. Unclear why I needed to grant permissions (not documented), this would also be a concern for devs as it introduces unnecessary friction into the process.

**Steps to reproduce**
1. Build clean project on mac, for example `cmake --build build/mac/. --target Editor MultiplayerSample.GameLauncher --config profile`
2. Launch project by clicking icon

**Expected behavior**
Game client launchers cleanly

**Actual behavior**
OS blocked launched and asked me to approve accessibility access for client

**Assets required**
Provide sample assets needed to reproduce the issue.

**Screenshots/Video**
If applicable, add screenshots and/or a video to help explain your problem.
![Screen Shot 2021-11-29 at 1 40 23 PM (2)](https://user-images.githubusercontent.com/61438964/144087954-f6b03108-3b60-47aa-917a-2508dd877292.png)

**Found in Branch**
* stabilization/2110

**Desktop/Device (please complete the following information):**
 -  Device: Mac
 - OS: macOS
 - Version: Big Sur 11.6.1
 - CPU: 2.5 GHz Dual-Core Intel Core i7
 - GPU: Intel Iris Plus Graphics 640 1536 MB

**Additional context**
Was using MultiplayerSample as the project, it could be there something specific about that project. Will try and reproduce with standard template project.

**Comment by lawsonamzn** [comment]
So on the mac, Accessibility Permission is required to act on the user's behalf
* Type keys on the keyboard for them
* Click mouse buttons for them
* Move the mouse pointer for them

This kinda makes sense - you don't really want your computer to be moving the mouse pointer and clicking on your behalf without your permission.  Considering what you could do to the computer just by moving and clicking / typing keys on the keyboard.  Remote control is powerful.

However, most games (first person shooter) need to be able to do this, since the usual strategy is to each frame
* Hide the mouse cursor
* Get the mouse position and subtract it from some known center point.  This is the delta to use to rotate the camera by.
* Reset the mouse cursor to that known center point, so that the next frame will be a fresh delta.

The problem with this is that the third step requires moving the mouse pointer on the users behalf,  and thus requires the permission to do so.

A bigger problem with this is that even if you accept the permission, OSX seems to mess up how it stores it, and duplicate applications (ie, the Same MultiplayerSampleGameLauncher.App placed in different folders do not share the same permission but also cannot get the permission added to them as the system seems to store a hash of just 'app name' --> permissions, without taking location into account.
