### ISSUE TITLE
[GNU/LINUX] UI Editor the color of the image is unoriginal and the alpha with the texture is bad

### ISSUE THREAD

**Issue by Magical10240** [o3de/o3de#6380]
**Describe the bug**

![2021-12-13_13-07](https://user-images.githubusercontent.com/17591539/145794817-780118b3-cd5d-4eaa-adb0-8a5b343f08ff.png)

**Steps to reproduce**
O3DE Editor
UI Editor
Add new empty element
Add component Image
Sprite path file
*png
*jpg
*gif
*tif
*tiff
*bmp
*tga not working
look not nice and unoriginal with textures

**Found in Branch**
21.11.1 stable

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Xubuntu
 - Version: 20.04.03 LTS
 -  CPU: AMD 3 3100
 - GPU: AMD 5500 XT [Mesa 21.0.3]
 - Memory: 16GB

**Comment by monroegm** [comment]
Probably related to #6381

**Comment by monroegm** [comment]
Sending to SIG-Graphics-Audio as this is probably related to #6381

**Comment by VickyAtAZ** [comment]
The images you added may not be processed with the presets (UserInterface_Compressed and UserInterface_Lossless)for UI.  It probably was processed with albedo preset which may convert the image's color space to linear. Using the presets for UI won't have this issue. 
(To find out which preset it's using to build the image, you can search the image file in AssetProcessor's window and you can find the preset name in the file's log.)

You have two options to use the correct preset for these files. 
1. Add _ui prefix to the file name. For example, change test_png.png to test_png_ui.png. Then the image build will choose UserInterface_Compressed  preset automatically when process this file. 
2. Instead of changing file name, manually choose UserInterface_Compressed or UserInterface_Lossless preset in Texture Setting Editor. The Texture Setting Editor can be opened by right clean the image file in Editor's Asset Browser panel. After save the change, the editor generates an .assetfinfo file next to the image file. This file needs to be submitted to github repo.

**Comment by Altair1024** [comment]
already changed filenames at the end `* _ui` color changed bright and color not original in ui editor

https://user-images.githubusercontent.com/17591539/146256412-1b2eb6b2-a8a5-4b60-8af4-893aaa72f36f.mp4

**Comment by VickyAtAZ** [comment]
Hi, @Magical10240 
I have a fix for this issue. 
https://github.com/o3de/o3de/pull/7386

**Comment by VickyAtAZ** [comment]
The fix was submitted in https://github.com/o3de/o3de/commit/2d8b4d8285241125715dc19c519aa515a4d0a89c
