### ISSUE TITLE
Deleting a duplicated entity with an HDRi Skybox component causes the original skybox to stop drawing

### ISSUE THREAD

**Issue by LB-ArturZieba** [o3de/o3de#6640]
**Describe the bug**
If an entity with an HDRi Skybox component is duplicated, and the duplicate entity is deleted, the skybox of the original entity stops being drawn.

**Steps to reproduce**
1. Create a new level.
2. Delete the Atom Default Environment entity along with all its children entities.
3. Create a new entity and add an HDRi Skybox component to it.
4. Duplicate the entity.
5. Delete the duplicate entity.

**Expected behavior**
Viewport remains black.

**Actual behavior**
Viewport turns grey.

**Video**

https://user-images.githubusercontent.com/86952082/148036859-afe177fb-cb49-407b-8552-5d633bf0652b.mp4

**Found in Branch**
Development (7581967)

**Desktop**
Device: PC
OS: Windows
Version 10
CPU AMD Ryzen 5 3600
GPU NVIDIA GeForce RTX 2060 SUPER
Memory 16GB

**Comment by sDeemm** [comment]
I was looking at the provided video when I noticed that the user deleted the original entity instead of the duplicated one (see Entity Id in the inspector). Deleting the duplicated entity **does** the expected behavior ( viewport remains black ). Unless there's another scope to this issue, I think it's reasonable to close it.

**Comment by LB-ArturZieba** [comment]
We have reverified this on the Stabilization_2205 (a073665) build, and deleting the duplicated entity does not remove the black background as described in the above comment. Sorry for overlooking this one, closing the issue as per above comment.
