### ISSUE TITLE
Bug Report: Changing Directory of installation causes an error for launching

### ISSUE THREAD

**Issue by amzn-leenguy** [o3de/o3de#6798]
**Describe the bug**
When a user has the engine previously installed, and uninstalls it, and then does a fresh install again of O3DE (using the installer), It does not force a register of the new engine installation (and or update the registration).

Therefore it prompts an error saying CMAKE can't find the engine (Since I may have installed it else where previously).

I had help from the community that I had to manually delete the o3de_manifest.json file for it to force update the new location of the engine. This shouldn't be workflow to solve this. @AMZN-alexpete has a dialog box solution to solve this [here](https://github.com/o3de/o3de/pull/6184) But it has been suggested that we should do the following:

- If you install o3de and create a project, then install another o3de in another folder, that first project will think it can run with the new engine (since the user chose to install the new engine, therefore they intend for the new engine to open their following projects from this point on)

**Steps to reproduce**
1. Install O3DE in one location (E.g. C:/)
2. Uninstall it.
3. Install O3DE in a new location (E.g. E:/) 
4. See the CMAKE error it produces.

**Expected behavior**
If I was to install the editor in a new location, I expect the installer to automatically just force a registration and just work. I shouldn't need to read any dialog prompts or accept any changes. It should just accept and force update my most recent version of the engine I just installed.

**Actual behavior**
It prompts a CMAKE error and asks the user to open the CMAKE GUI and manually update the location. For a non-technical like myself, this request is unfamiliar to me.  

**Assets required**
n/a

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/82846749/148859586-9e45a9e0-9236-4292-9dc7-34e3ac55feaf.png)

**Found in Branch**
O3DE Stable 21.11 Release Installer (Date Jan 8, 2022)

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU
 - GPU
 - Memory 64 GB

**Additional context**
A comment from @amznestebanpapp 
BTW, the installer does not register the engine, the project manager does
The installer does not remove the manifest file, I dont think it should because there could be another installation or a source engine. Would be great if the installer removes the entry for that engine that is being uninstalled.

**Comment by AMZN-alexpete** [comment]
Potential related PR: https://github.com/o3de/o3de/pull/6828

**Comment by AMZN-alexpete** [comment]
> If you install o3de and create a project, then install another o3de in another folder, that first project will think it can run with the new engine (since the user chose to install the new engine, therefore they intend for the new engine to open their following projects from this point on)

This is certainly true for some users, but not for others.  Consider the following use cases:
1. Every engineer working on O3DE works out of a source build of the engine.  If they install the engine in a separate folder to test the installer, a branch or sdk, they do not intend the newly installed engine to open all their projects from that point on.  This is likely the most common setup for o3de users currently.  These users want projects to be engine specific until they choose to change the engine they're compatible with.
2. A game developer is working on multiple games and each of those game projects have their own engine.  This happens when a game team 'locks' on a specific version of an engine, or makes custom changes to the engine that they do not want to port to another version of the engine.  It's important to these users that their projects are tied to specific engines.

> Expected behavior
> If I was to install the editor in a new location, I expect the installer to automatically just force a registration and just work. I shouldn't need to read any dialog prompts or accept any changes. It should just accept and force update my most recent version of the engine I just installed.

Consider users that perform these common actions
1. a user clones the o3de github repo and registers the engine
2. user builds an engine sdk with the same name as the source engine and attempts to register it
3. user downloads an installer with the same engine name and runs it
4. user deletes a local github repo folder and clones the github repo in a different place

Most users who are currently using O3DE are trying all those actions in various orders and we don't have control over the engine name, except in the case of the installer we distribute.  When the user gets in a situation where they try to register an engine name that already exists, they need to know so they can:
1. fix an engine entry they deleted but didn't unregister
2. remove an engine they forgot to uninstall and no longer need
2. fix engine.json they manually edited
3. fix o3de_manifest.json they manually edited
4. let the user have multiple engines installed for different projects or multiple instances of the same project

> When a user has the engine previously installed, and uninstalls it, and then does a fresh install again of O3DE (using the installer), It does not force a register of the new engine installation (and or update the registration).
To fix this I think we need to:
1. have the installer un-register the engine as part of the uninstall process https://github.com/o3de/o3de/issues/6835
2. have the Project Manager perform a quick "health check" on startup to detect missing engines, duplicate engines - clean up the simple situations, and prompt the user for anything else.

**Comment by amzn-leenguy** [comment]
> To fix this I think we need to:
> 
> 1. have the installer un-register the engine as part of the uninstall process [O3DE installer does not unregister the engine on uninstall #6835](https://github.com/o3de/o3de/issues/6835)
> 2. have the Project Manager perform a quick "health check" on startup to detect missing engines, duplicate engines - clean up the simple situations, and prompt the user for anything else.

I agree with these two suggestions. Tagging @lawsonamzn for his opinion too.

**Comment by AMZN-alexpete** [comment]
I have just attempted to reproduce this error with the latest O3DE stabilization installer as follows:
1. Download https://o3debinaries.org/stabilization-2111RTE/Latest/Windows/o3de_installer.exe
2. Install in default location (C:/O3DE/0.0.0.0)
3. Uninstall it.
4. Install O3DE in a new location (D:/O3DE/0.0.0.0)

Looking in my `o3de_manifest.json` there is no entry for the new engine and there was no popup error when launching the Project Manager.  In the logs I see:
```
~~1642633526377~~1~~000000000000B250~~Python~~ERROR:root:Attempting to register existing engine "o3de-sdk" with a new path of D:/O3DE/0.0.0.0. The current path is D:/O3DE/stab_installer. To force registration of a new engine path, specify the -f/--force option.
Alternatively the engine can be registered with a different name by changing the "engine_name" field in the engine.json.
```
Once this PR https://github.com/o3de/o3de/pull/6984 is approved and merged, I should be able to test again and verify that a popup appears indicating the problem and that lets me solve the issue by pressing the "OK" button.

This will let the user "force" register the engine due to the issue I mentioned before that leaves the old install behind https://github.com/o3de/o3de/issues/6835

**Comment by amzn-leenguy** [comment]
Can you show a screenshot of the popup here for reference @AMZN-alexpete ? Does the pop up offer the user other options? If not, Is there any point of the pop up if there are no options? Or is it just informational? Do we need to show it? or can we just update it automatically so it just aligns with users expectations?

**Comment by AMZN-alexpete** [comment]
This is the popup dialog:
![image](https://user-images.githubusercontent.com/26804013/150274348-d2160329-dd06-4de0-baa0-93f762525c59.png)

**Comment by AMZN-alexpete** [comment]
PR #6984 did not fix the issue with these exact repro steps where the engine.json is missing or corrupt, so I put up a fix for it here https://github.com/o3de/o3de/pull/7049

**Comment by AMZN-alexpete** [comment]
This issue appears to be resolved based on the latest changes to the stab branch.  You should be able to test the installer here: https://o3debinaries.org/stabilization-2111RTE/Latest/Windows/o3de_installer.exe

There is a known issue where if you install the engine in a location that previously had an engine, you may run into a compile issue because the project manager does not detect that the new engine isn't registered.  This is because the engine path is already registered in `o3de_manifest.json` but the `engines_path` value for the engine `o3de-sdk` still points to some other location where there is no engine anymore. 

This is the order of ops to repro the issue I'm talking about.
1. Install engine in c:\o3de
2. Uninstall the engine
3. Install the engine in c:\location2
4. Uninstall the engine
5. Install the engine in c:\o3de again <-- here Project Manager fails to detect it needs to force register the engine
6. Create a project and try to build

**Comment by amzn-leenguy** [comment]
I will try and break it again over the weekend :)

**Comment by amzn-leenguy** [comment]
> I will try and break it again over the weekend :)

I used the test link above @AMZN-alexpete and it worked fine. Consider this issue / ticket resolved.
