### ISSUE TITLE
Gradient Surface Tag Emitter: Preview does not draw until a tag is added

### ISSUE THREAD

**Issue by jckand-amzn** [o3de/o3de#7554]
**Describe the bug**
The Preview on the Gradient Surface Tag Emitter component does not draw until a tag is added to the component's Extended Tags container.

**Steps to reproduce**
1. Create a new entity.
2. Add the following components:

* Image Gradient
* Box Shape
* Gradient Tag Modifier
* Gradient Surface Tag Emitter

3. Assign any valid gradient image to the Image Gradient component.
4. Expand the Previews on the Image Gradient and Gradient Surface Tag Emitter component.

**Expected behavior**
Previews for both components draw, regardless of if a tag is assigned to the Gradient Surface Tag Emitter component.

**Actual behavior**
No Preview draws in the Gradient Surface Tag Emitter component until a new tag is added to Extended Tags.

**Screenshots/Video**
![no_preview_gradientsurfacetagemitter](https://user-images.githubusercontent.com/82226555/153474393-1f68fb44-b6e7-4cfd-a98f-b1428aeca61c.jpg)

**Found in Branch**
development@ 6791b652cc3a544ad3650ec69b99a594a4b39caf

**Comment by monroegm** [comment]
@mbalfour-amzn Is this by design?

**Comment by mbalfour-amzn** [comment]
After some investigation, I can conclude that this is in fact by design, though it helps highlight the need for SurfaceData components to get some UX love.

Basically, right now the Gradient Surface Tag Emitter component will _modify_ existing surface points by adding tags and weights to them, but doesn't _generate_ any surface points. If there are no tags selected, the preview is correctly showing that no new data is getting added to any surface points. Once you add one or more tags, then the preview will start showing an output, but _only_ where surface points exist. See the following image, where the preview only shows data where the sphere is, because the sphere is a Shape Surface Tag Emitter that _generates_ surface points.

![image](https://user-images.githubusercontent.com/82224783/153489242-bddcaba6-4e03-49e2-96bb-c4801f4885e5.png)

The oddest part of what's reported here is that having a Surface Tag of "(unassigned)" is sufficient to generate outputs. However, it _is_ in fact generating an output. This can be seen by creating a Surface Mask Gradient that filters to a tag of "(unassigned)". This behavior may or not be a bug, it's debatable.

![image](https://user-images.githubusercontent.com/82224783/153489678-63987104-c29a-46e8-9d27-ab85573ef6cf.png)
