### ISSUE TITLE
Gem::Atom_RHI crash and segfault when run in parallel

### ISSUE THREAD

**Issue by Kadino** [o3de/o3de#7654]
**Describe the bug**
Test module intermittently crashes or exits early when executing Gem::Atom_RHI.Tests.main unit tests in parallel with other modules. This is likely environment-dependent, though reproduced consistently (61 exit code 0xc0000374, 31 segfault) across two machines with quite different hardware. Please prefer fixing the contention issue, versus simply excluding this module from parallel execution.

**Steps to reproduce**
1. Locally build O3DE in the profile configuration
2. Open a terminal and navigate into the CMake build directory
3. Run the following command `ctest -C profile -L "(SUITE_main|SUITE_smoke)" --output-on-failure -j 32`

**Expected behavior**
Test module can execute in parallel with other modules.

**Actual behavior**
One of two failure types:
`48 - Gem::Atom_RHI.Tests.main::TEST_RUN (Exit code 0xc0000374 `
`48 - Gem::Atom_RHI.Tests.main::TEST_RUN (SEGFAULT)`

**Found in Branch**
Development @ https://github.com/o3de/o3de/commit/4982787043a45449ef37a1435e37402611918ceb

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10
 - CPU Intel i7-9750H / Ryzen TR 3970X 
 - GPU NVidia
 - Memory 32GB / 64 GB

**Additional context**
This may be the cause of the hang in https://github.com/o3de/o3de/issues/7653

**Comment by Kadino** [comment]
Continuing to reproduce in a local soak test of b64cce7f14 with a failure rate of 100%
38/130 (30%) failed with "SEGFAULT"
92/130 (70%) failed with "Exit code 0xc0000374"

**Comment by jromnoa** [comment]
We advise against using parallel tests now and instruct users to use batched tests instead. While the parallel tests can be accessed and used, its a risk that is placed solely on the user until we have official support provided for it. 

You can read the wiki for the Multitest Framework here: https://github.com/o3de/o3de/wiki/Multitest-Framework:-Running-one-or-multiple-tests-in-one-or-multiple-executable(s). 

When we officially support parallel tests we can explore debugging and fixing the issues related to them, but for thew time being we use batched tests instead of parallel tests.
