### ISSUE TITLE
Script Canvas: User defined functions with multiple or branched outs with data output cause a crash at runtime. (User nodeables required a strictly interpreted ExecutionOut pipeline.)

### ISSUE THREAD

**Issue by michleza** [o3de/o3de#8054]
**Describe the bug**
If you include a math comparison node in your user function the editor crashes when you play the game

**Steps to reproduce**
1. open a new or existing level
2. open a new script canvas file
3. make input and output nodelings
4. add a string type output variable to the out nodeling. set it's value to something other than blank
5. add two number type input variables to the in nodeling.
6. connect a math greater than node to the input node. set the A/B values to your input variables
7. connect the greater than node's true value to the out nodeling
8. save the script canvas file
9. call the function in separate script canvas file so that it occurs when you play the game. supply values that will cause the comparison to evaluate to true.
10.  attach the script to a game entity
11. run the game

**Expected behavior**
two numbers you provided are compared and the rest of the connected graph executes.

**Actual behavior**
If the greater than comparison is true the engine crashes

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/98843754/156671942-ee13a68f-23d5-4c59-bd38-adba8cafed99.png)
[editorCallStack.txt](https://github.com/o3de/o3de/files/8181898/editorCallStack.txt)

**Found in Branch**
development
**Desktop/Device (please complete the following information):**
 - Device: win 10
 - CPU [Ryzen 9 5950
 - GPU nvidia 3070
 - Memory 32gb

**Additional context**

**Comment by carlitosan** [comment]
The cause of the issue is that the runtime call to `ExecutionOut` is calling through to the version that supports the call intended for C++ nodeables. However, given that the call will route straight through to a Lua function, a simpler mechanism is required (notably one that shouldn't use the C++ mechanism at all), that passes the the arguments directly to the to the waiting function which is the result of the graph that called `SetExecutionOut` on the nodeable, before calling the function on the nodeable that invoked `ExecutionOut` on the C++ nodeable method.

**Comment by carlitosan** [comment]
The user defined nodeables simply need to set/get lua functions directly and call them all in the Lua system, by passing the c++ mechanisms entirely. They should have their own version of `InitializeNodeableOutKeys`, `ExecutionOut`, and `SetExecutionOut` that entirely bypass the mechanism inplace to allow C++ defined nodeables to interact with the Lua interpreted system.
