### ISSUE TITLE
o3de Editor / Materials - O3DE will not clean up Prefab JSON files when adding or removing materials.

### ISSUE THREAD

**Issue by superkitcath** [o3de/o3de#8350]
[Migrated from JIRA ATOM-17440]
Provide a detailed description of the defect here and include any possible workarounds.
----
Found in Build: Development

Reproducibility: Yes

Prerequisites: o3de, a model with multi materials to test

Expected Result: JSON files clean up old materials

Actual Result: JSON files start to keep old materials, and they start to add up producing visual, and material errors, especially with LODs.

**Comment by gadams3** [comment]
I read through the repro steps on the wiki again. I don't think this is malfunctioning but we need to address UX issues related to menu option and dialog names.

In the wiki, a brand new material with a unique ID was created to replace FOUR with TEST. The data for the old slot is going to remain unless you clear it from the component wide context menu. All of the assignments and overrides will persist so that the data can be used with different models that have the same slots or so that the data is not lost if you assign a new model.

You're in the context menu for the individual material slot. Clicking clear material instance overrides only clears the properties for that specific slot. That's not going to clear the data from the other material.

I can rename the menu option to be more explicit, saying that it's clearing properties and UV data. I can add another menu option that also clears the material.

To remove that extra data you're seeing in the json, right click on the component or click the menu button on the component header to get the component wide context menu. There are several options to clear different sets of material overrides.

We have also discussed renaming some of the menu actions like “edit source material” back to "open material editor” and “edit material instance” to "open material property override editor” or something like that. TBD. Will also make sure that the menu options in those dialogs are more easy to discover.

But as far as the JSON data is concerned, I think it is as designed for copying and pasting and portability between models.
