### ISSUE TITLE
[ROS2 Gem] URDF support

### ISSUE THREAD

**Issue by adamdbrw** [o3de/o3de#8483]
**Is your feature request related to a problem? Please describe.**
Users would like to import Robot Definition files into simulations with o3de. Parsing and generating model from URDF is much better than trying to replicate it in supported formats.

**Describe the solution you'd like**
- Importing: .urdf files can be placed into Asset directory of a Project/Gem. They will be handled by the Asset Processor resulting in models/prefabs which can be added to the scene.
- For basic support, meshes, textures, colliders and joints are enough.
- Advanced support: handling scripting such as sensors (TBD)
- Advanced support: exporting to URDF.
- An example included in the Gem

**Describe alternatives you've considered**
Creating a few robot prefabs based on .fbx files and including them in the Gem, providing instructions on how to make such prefabs.

**Additional context**
Analysis and first PoC work is just starting. Best to (critically) reuse whatever is there in open source.

**Comment by AMZN-stankowi** [comment]
You mention joints, how critical is animation to this? That will help scope the work to be done. A lot of the complexity in supporting FBX and GLTF right now is around animation, blend shapes, skeletons, etc. However STL is simple for us to manage because it's just static geometry.

What are the primary benefits you imagine you would get by importing URDF directly instead of converting to FBX first? This will help scope the work to be done, if it's primarily a conversion issue (for example, "we just need the geometry to come through") that's going to be primarily done in the scene importer library. If there's data that doesn't survive the conversion from URDF to FBX, same thing. If most of the request is on the re-assembling things engine-side after the content is imported, then there will be additional work downstream there.

**Comment by adamdbrw** [comment]
I think that static geometry is a good starting point. First joints to support would probably be to enable wheel movement or similar basic locomotion, although it is certainly more complex to support in general. I will work on a PoC that will give us some insight into trade-offs.

**Comment by piotr-zyskowski-rai** [comment]
Since this is the work directly related to ROS2 Gem development I created a dedicated issue there and I will close this one. https://github.com/RobotecAI/o3de-ros2-gem/issues/100
