### ISSUE TITLE
PyTest TestResults Don't Archive User Logs

### ISSUE THREAD

**Issue by AMZN-Gene** [o3de/o3de#8573]
User logs are not copied to the TestResult folder after a pytest EditorSingleTest

**Steps to reproduce**
1. Run a pytest such as .\AutomatedTesting\Gem\PythonTests\Multiplayer\TestSuite_Main.py::TestAutomation::test_Multiplayer_AutoComponent_RPC
2. Open the TestResults to see the logs

**Expected behavior**
The files inside AutomatedTesting/user/log should be archived including server.log (if running the example multiplayer test)

**Actual behavior**
Only 3 logs appear: editor_test, toolsdebug, and toolsinfo

**Comment by Kadino** [comment]
There may be a previous bug workaround related to log saving during parallel execution.

**Comment by evanchia-ly-sdets** [comment]
If I'm remembering correctly, this may actually be by design. I believe we decided to only save those three logs due to some complications with parallel/batched logs. The user can use the save_artifact() function in their own teardown() to save the server logs as is.
I will investigate this issue to either find a solution or a reason for this design.

**Comment by evanchia-ly-sdets** [comment]
https://github.com/o3de/o3de/pull/15470
