### ISSUE TITLE
[Feature Request] Import optional 3rdParty package

### ISSUE THREAD

**Issue by bacTlink** [o3de/o3de#8576]
I successfully created [O3DE packages](https://www.o3de.org/docs/user-guide/build/packages/) and built my project on them.
I would like to set the packages as optional, i.e. my project can still run when the packages are not available due to network failure or something.
However, The function ```ly_associate_package``` marked my packages as required, and the project will fail to build without the them.

**Describe the solution you'd like**
```ly_associate_package``` can mark packages as optional.

**Comment by lumberyard-employee-dm** [comment]
@bacTlink Well the ly_associate_package is used to associate a downloadable package with a CMake TARGET name.
So if a package has failed to download, if a target within O3DE is trying to use the exposed downloadable package target name then the configuration would fail at a later point.

The failure with [ly_associate_package](https://github.com/o3de/o3de/blob/development/cmake/3rdPartyPackages.cmake#L279-L287) is meant to catch errors with using the package early, so that the user can troubleshoot the situation.

Once the package is downloaded to the user's machine however, it doesn't need to downloaded again at all.
As long as the same LY_3RDPARTY_PATH is used when [configuring](https://github.com/o3de/o3de/blob/development/cmake/3rdPartyPackages.cmake#L40-L43) then it re-use the downloaded packages.

Pinging @lawsonamzn to make sure you are in the loop.

**Comment by lawsonamzn** [comment]
I'd like to understand better what the user-facing workflow would be for an optional package.   Would we want to for example try to download, fail, but then continue anyway?  Or not to try to download and present a flag?  Or have a different user option for "enable_xyz" and if TRUE, download the package, (and fail), and if FALSE, don't try to download the package?

What would be ideal here?  What we want to avoid is a situation where failure to download a package is silent, but causes actual problems down the line.  So one way to make it optional (currently) is set a cache variable like "use_Feature_xyz" and only associate a  package if that's TRUE.   Then later on you only declare the dependency on th epackage if use_feature_xyz is TRUE.  Otherwise you set some define to make the code skip over it.

Network failure is a tricky one because its really difficult to tell a network failure "thats not meant to happen" and should in fact cause the build to fail vs one thats "expected" (?).   What we certainly don't want is a server to be down temporarily and find during that outage nobody notices and versions are shipped missing support for some package that people expect to be there... because it still works without it...
