### ISSUE TITLE
Script Canvas: Add a node in Script Canvas to Get Column of Transform

### ISSUE THREAD

**Issue by Hsuehnj** [o3de/o3de#8670]
**Is your feature request related to a problem? Please describe.**
Add a Script Canvas node that would get column of Transform by index.

**Describe the solution you'd like**
Such as the node in Lumberyard:
        AZ_INLINE Vector3Type GetColumn(const TransformType& source, NumberType index)
        {
            return source.GetColumn(AZ::GetClamp(aznumeric_cast<int>(index), 0, 3));
        }

**Describe alternatives you've considered**
No

**Additional context**
No

**Comment by greerdv** [comment]
I think you should be able to do this with GetBasis, which is exposed to Script Canvas. 

Transform is now based on a quaternion representation (because that makes more sense for networking, animation, interpolation and physics) rather than a matrix representation, so it doesn't have a concept of rows and columns, but GetBasis should return the equivalent result and it takes an index argument.

**Comment by hultonha** [comment]
Thanks for the suggestion @Hsuehnj! If the option provided by @greerdv implements the feature you were after would you be happy with us closing this ticket? We might want to follow-up with some additional docs to make this clearer which might help people in future (if you have a suggestion for where this might go to increase visibility let us know). Thanks!

**Comment by hultonha** [comment]
Hi @Hsuehnj, I'm going to close this issue for now given the suggestion offered by @greerdv. If you still have a problem/concern please feel free to reopen it. Thank you for reporting the problem!
