### ISSUE TITLE
[GNU/LINUX] Create terrain world renderer after editor crashes problem possible on vulkan

### ISSUE THREAD

**Issue by Darkinggq** [o3de/o3de#8711]
**Describe the bug**
Create terrain and editor immediately crashes problem maybe atom vulkan for Linux, 3-4 weeks ago it was working fine

**Video steps to reproduce**

https://user-images.githubusercontent.com/17591539/161712516-b397011c-187c-415b-94d6-fa87da03f5ee.mp4

**Date Nightly Build**
Development: 2/5/22

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Manjaro
 - CPU Ryzen 3 3100
 - GPU AMD RX 5500XT 8GB (Mesa 21.3.7)
 - Memory 16GB

**Additional context**
[Editor.log](https://github.com/o3de/o3de/files/8416308/Editor.log)

**Comment by invertednormal** [comment]
I'm also seeing a crash on Vulkan with an nvidia 3070, however it's due to a context loss, not out of memory. It's possible there's multiple things going wrong. The largest recent changes have been with the forward shader and the addition of height based blending, which did make the shader a fair bit more complicated. There could be an issue in the Spir-V cross compiler, or it's possible the shader is doing something wrong that directx is letting the shader get away with.

**Comment by Darkinggq** [comment]
Ok, check tomorrow

**Comment by mcphedar** [comment]
Can you please test this again?

**Comment by Darkinggq** [comment]
@mcphedar @jiaweig-amzn I have other problem and I can't test https://github.com/o3de/o3de/issues/10140

**Comment by Darkinggq** [comment]
@jiaweig-amzn Hi, I'm already check terrain not crashing everything is fine (31412043ce89a560f13cec877caf4f91c04c5af1)

https://user-images.githubusercontent.com/17591539/178298232-a508f61d-96d8-492d-b118-2478309bd437.mp4
