### ISSUE TITLE
[Linux] Animation editor is open in a transparent state and cannot be used normally

### ISSUE THREAD

**Issue by sysuNie** [o3de/o3de#9142]
**Describe the bug**
A clear and concise description of what the bug is. Try to isolate the issue to help the community to reproduce it easily and increase chances for a fast fix.

**Steps to reproduce**
1. Launch the Editor.
2. Open the animation editor
3. See error

**Expected behavior**
The animation editor works fine

**Actual behavior**
The animation editor is transparent and cannot be used normally

**Assets required**
Provide sample assets needed to reproduce the issue.

**Screenshots/Video**

**Found in Branch**
Name of or link to the branch where the issue occurs.

**Desktop/Device (please complete the following information):**
- Device: PC
- OS: Linux Ubuntu
- Version: 20.04
- CPU: AMD Ryzen Threadripper 3970X 32-Core Processor
- GPU: GeForce RTX 2060 SUPER running the NVIDIA 470.86 proprietary Linux driver
- Memory: 64 GB

**Additional context**

**Comment by spham-amzn** [comment]
Cannot reproduce on development ( commit 3e42c6a2e4ac2b1d3b88b9d4ff3fea893525b0f8 ). This error was occurred previously due to a missing Qt plugin. Check to see if there is a folder + File in the bin/profile directory (Where the Editor is launched) called
```
xcbglintegrations/libqxcb-glx-integration.so
```

https://user-images.githubusercontent.com/82231385/168702239-8568e351-0ebe-467d-8932-ae6f512aff81.mp4
