### ISSUE TITLE
Reflection Probe is very difficult and unweildy to edit dimentions.

### ISSUE THREAD

**Issue by shawstar** [o3de/o3de#9672]
**Is your feature request related to a problem? Please describe.**

Reflection Probe is very difficult and unwieldy to edit dimensions after it is created. Needs Shrink-wrap setting, easier ways to manipulate using scaling tools. Identify friction points with tool, also have ability to shift center point anywhere within the cube to avoid conflicts with objects that are too close.

**Describe the solution you'd like**
So, we can use 'CTRL KEY' to shift the center point, like tools like Maya using the D key. IMO I did not even know 'CTRL Key' did this function, it is more tribal knowledge maybe, could there be a clear way to expose this functionality?

Also, as for the unwieldy. I find that hard part is the the scale is symmetrical, but really, it would be much easier to just move a face of the cube to a point, and then so on to cover the area... fighting the symmetrical scaling takes time to get the placement where it needs to be.

![image](https://user-images.githubusercontent.com/87207603/169411318-50a3ad81-e77f-455e-813e-560ed21acd99.png)

**Comment by galibzon** [comment]
@hultonha This is more about gizmos for editing cube shaped components.

**Comment by hultonha** [comment]
Thanks for notifying me about this @galibzon - the fundamental problem here is how BoxShape is defined. Right now it just has a single `Vector3` for width/height/depth (there is no center or pivot). This is why adjusting one side with the manipulators is symmetrical. This issue impacts all components that use Box Shape (Terrain being another example).

We have looked into this in the past and it often turns into a bigger issue as if we add the ability to offset a cube, things get more complicated to calculate its transform as it won't always be centered about the entity transform.

One potential fix is to update `BoxShape` to store a Min and Max extent for the box, this would make it possible to adjust it asymmetrically, but this only works for `BoxShape`. As soon as we touch it we probably will want to fix the other shape components too (we could avoid this but using a consistent approach will probably help for future changes).

I don't know when sig-core or sig-simulation will be able to look at this but I agree it is relatively high priority. It will cause some breaking changes though to component using Box Shape.

Tagging @greerdv who has looked into this before too (as well as myself), this could be something we can schedule as part of RTE work but it's hard to confirm anything at this stage. There isn't anything simple to change with manipulators as they are just working with the data that's there.

**Comment by hultonha** [comment]
Adding sig/simulation and needs triage to discuss in the next sig-sim triage meeting

**Comment by yuyihsu** [comment]
We should also look into the shape editing across different systems. We've seen an inconsistent behavior across the different shape editing in different system.

**Comment by srikappa-amzn** [comment]
@o3de/sig-simulation , deferring triaging of this issue to you since sig-simulation owns shape component

**Comment by HogJonny-AMZN** [comment]
Why not a Box Shape Editor component and/or component edit mode, that has the ideal user interaction mechanisms.  This could still collapse down to the optimized box data for runtime?

If the reflection probe 'really' needs these additional features, like the ability to set/store the capture point center separately from the origin of the box, or even storing a pivot point that is separate from the box origin, maybe we should consider a new AdvancedBoxShape that does these things.  Solve for the User first, then determine how to get the optimal data to runtime?

**Comment by HogJonny-AMZN** [comment]
Moving a side is just a user interaction and presentation; dragging on a side could re-calc the box origin each frame.  I understand I am being a bit naive, you would need to shift the adjusted boxes transform and that itself might not jive with other aspects or components of that shared entity.

I'm just trying to think of how we can get to where we want to be, and the Reflection Probe itself seems to have enough special needs that maybe we should create a new ProbeBox type class, much like we needed to add a specialized AxisAlignedBox because that was needed by some terrain components.

**Comment by hultonha** [comment]
Adding a specialized box might be the quickest/easiest solution but would not be ideal long term and other components will have this problem. Adjusting the box component data affecting the overall entity transform sounds like a horrible idea to me to I'm afraid. This is solvable, it's just not as easy as it might seem on the surface, that's all I'm trying to get across. To do this properly there isn't a convenient short-cut we can take without some big trade off. I'll talk with the sig-simulation folks about prioritizing this as we now own Shape Components and might be able to help with it sooner rather than later

**Comment by yuyihsu** [comment]
UX work tracked in LYN-13866.

**Comment by amzn-leenguy** [comment]
There's a kick off meeting on 9/20 to talk about this. More updates to come.

**Comment by hultonha** [comment]
@shawstar This should now be fixed by the recent changes from @greerdv to add a shape component offset (see https://github.com/o3de/sig-simulation/issues/26 and https://github.com/o3de/o3de/issues/12370
