### ISSUE TITLE
Feature Request: Confusion on the file menu option "Save material" and "Save material to source"

### ISSUE THREAD

**Issue by yuyihsu** [o3de/o3de#9732]
**Is your feature request related to a problem? Please describe.**
Difference between "Save Material" and "Save Material to Source" on the Material Instance Editor is unclear. The only noted difference is the name provided on the "Save As" screen.

**Describe the solution you'd like**
Suggest changing "Save material" to "Save", and "Save material to source" to "Save As...".

**Describe alternatives you've considered**
N/A

**Additional context**
This feedback is from the WTE session on WF5 conducted on 4/28, and  [recording at :38](https://broadcast.amazon.com/videos/513246).

**Comment by gadams3** [comment]
I have made some modifications to the material instance inspector menus and heading. The menu action names have been renamed to save as and save over. Save over also includes the file name for the material source file that will be saved over if the file is not changed in the save file dialog. The heading also has links for all of the related material assets so that they can be opened in the material editor. In one of our UX meetings, there was discussion about getting rid of the menu and placing buttons at the bottom of the header, similar to what we used to have at the bottom of the window.
https://github.com/o3de/o3de/pull/9901
