### ISSUE TITLE
Feature Request: Entity is added to the viewport in the raycast location, instead of 0,0,0

### ISSUE THREAD

**Issue by yuyihsu** [o3de/o3de#9754]
**Is your feature request related to a problem? Please describe.**
It's confusing where an entity gets created if you right click in Outliner and create a new entity. User expected the new entity to be created at 0,0,0 here, but the entity was created at a raycast point from the center of the view instead.

**Describe the solution you'd like**
This is a larger discussion about where the entity origin should be in different situations, should it always be 0,0,0?  at selection in perspective viewport? at location of currently selected object? what if it is created in the outliner? should it match location of parent if it is created as a child? Editor team has debated this in the past, so first step is to follow up with them.

**Describe alternatives you've considered**
N/A

**Additional context**
This is part of the WTE session on WF5- environmental art. the recording is at :39.

**Comment by monroegm** [comment]
SIG-Content feels that this is a major relative to other items in the backlog

**Comment by amzn-leenguy** [comment]
@o3de/sig-ui-ux should have a group discussion with @o3de/sig-content and figure a call to resolve this issue. @amzn-leenguy to schedule a time slot for this.

**Comment by hultonha** [comment]
@yuyihsu I don't quite understand the issue

> It's confusing where an entity gets created if you right click in the Outliner and create a new entity. The user expects the new entity to be created at 0,0,0, but the **entity is created at a raycast point from the center of the view** instead.

I think this is the intention right now so that the user can see the new object they've created in their view (appearing at 0,0,0 in the context of a larger level may be more disorientating). Also the issue says 'random location' but is that true? Or is it always in the center of the view?

I'd really appreciate being included in the follow-up conversations about this as this is very much related to the viewport. Thanks!

**Comment by yuyihsu** [comment]
UX suggestion:
1. User can use F/Z key to zoom to the selection. We need to document this in the docs to educate the user.
2. Add a clear visual feedback to the empty entity in the viewport.

**Comment by mbalfour-amzn** [comment]
@hultonha This one has confused me too, let me see if I can add a visual aid to explain why it's confusing.

Steps:
1. Right-click in the Entity Outliner and choose "Create Entity"
![image](https://user-images.githubusercontent.com/82224783/171701926-e750d73b-7d26-4464-af55-7891575de29e.png)
2. Look at the values on the entity:
![image](https://user-images.githubusercontent.com/82224783/171702009-1d1fa9d1-9edb-4de9-9045-0889e7418ff9.png)

If I'm right-clicking in the Entity Outliner, I don't have any particular visual cue or expectation that the view in the adjacent viewport is affecting the location of the entity I'm creating. I would expect it to be created with default values at 0,0,0, because I'm trying to create an entity in the context of an outline, not a world position. If it _does_ get a world position, I don't really have any clear frame of reference to explain why it got a position. And in my case, I'm even super-familiar with the fact that creating entities _in_ the viewport raycasts, but even with that knowledge, I thought the entity positions showing up when creating entities in the Entity Outliner was a bug because I didn't connect the two.

FWIW, I've also had a problem with understanding the reverse - when creating entities in the viewport, I've been surprised when they get parented underneath a selected entity in the Entity Outliner. That one's at least more understandable after it happens though, because I at least have a visual clue that the parent was/is highlighted. I've just found myself surprised by it many times.

And one more related piece that I'll put out there - if you _do_ create an entity in the viewport while an entity is selected in the Entity Outliner, it appears that it _doesn't_ raycast, and instead gives it a transform of 0,0,0 relative to the parent, regardless of whether or not the parent is even currently visible in the viewport. I would think that if we're creating an entity in the viewport, it would consistently raycast regardless of whether or not it's making a child entity.

**Comment by Infurael** [comment]
Small but important detail to keep in mind; it's not the entity that's at the root of the problem but rather the initial coordinates for the TransformComponent. Pointing this out, because at some point in the future having a TransformComponent won't be mandatory. Not all entities require a position in the world, so creating an entity shouldn't come with the expectation that it will be put at the location is looking but rather adding a TransformComponent (either automatically or manually) is what places the entity where the user is looking.

**Comment by yuyihsu** [comment]
No UX action needed after discussing with @hultonha . Please review with @o3de/sig-ui-ux once the implementation is done.

**Comment by hultonha** [comment]
Resolved by https://github.com/o3de/o3de/pull/11819
