### ISSUE TITLE
Switch Material Color in Script Canvas?

### ISSUE THREAD

**Issue by ParasiteSt** [o3de/o3de#9821]
**Describe the bug**
As far as I can see (and a few others) with testing in script canvas you are not able to switch the color of a material through the nodes provided.

**Steps to reproduce**
1. Create a mesh with a material applied to it.
2. Make a new script canvas that On graph starts should switch the material color for the mesh you made.
3. See Error

**Expected behavior**
The nodes provided to switch material parameters should work correctly.

**Actual behavior**
The nodes provided to switch material parameters seem to not work at all, and always print out a default value with no connection to the material at all even with a get material parameter node which should allow to see what a value is on a material always comes back as a default 0/1.

**Found in Branch**
Development Branch

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Version 10

**Additional context**
If this is possible to do in script canvas, and no bug is in place, this issue can be closed, but documentation should be made on how to do so since 3 people at least have tried with no success on making a color/parameter switch through script canvas.

**Comment by amzn-tommy** [comment]
![SetColorRed](https://user-images.githubusercontent.com/82672795/171515059-305806b2-7cea-4cb4-b4e1-dc8c953a9108.PNG)

As discussed in discord (see thread https://discord.com/channels/805939474655346758/816043601754325023/981638734271377438), this will work as long as you have a default material applied and no materials on the individual slots. Otherwise, it would need to be modified to get the MaterialAssignmentId for each individual slot you want to override, and call SetPropertyOverride for each slot.

**Comment by ParasiteSt** [comment]
Thanks amzn-tommy this is exactly what I was looking for, and shows that it is not broke in script canvas so I will be closing this issue.
