### ISSUE TITLE
Source Engine built Editor fails to open and create new levels after FBX Settings (PREVIEW) tool window has been opened

### ISSUE THREAD

**Issue by LB-MateuszSzweda** [o3de/o3de#9853]
**Describe the bug**
Opening the FBX Settings (PREVIEW) tool window hinders the Source Engine built Editor ability to open and create new levels successfully.

Trying to open or create a new level leaves the user with an empty level without any entities.

Please note that this occurs even after the FBX Settings (PREVIEW) tool window was closed and in order to correctly load and create levels after its opening the Editor has to be restarted.

This issue occurs also on Linux platform.

For further information please refer to the attached video and Editor log file.

**Steps to reproduce**

1. Launch the Editor and create a new level.
2. Search for any .fbx object in the Asset Browser (ex. groundplane_512x512m.fbx) .
3. Right click the .fbx asset and select Edit Settings... .
4. Wait until the FBX Settings (PREVIEW) tool opens and close it.
5. Open a new level.

**Expected behavior**
The selected level is correctly opened.

**Actual behavior**
An empty level without any entities is loaded instead of the selected level.

**Screenshots/Video**

https://user-images.githubusercontent.com/86953456/171418734-27e43612-5e34-42f8-8673-f3fca7218eac.mp4

**Found in Branch**
Development (6f9e0be)

**Desktop/Device:**
- Device: PC
- OS: Windows
- Version: 10 Pro
- CPU: AMD Ryzen 7 2700X
- GPU: AMD Radeon Pro Duo
- Memory: 16GB

**Additional context**

[Editor.log](https://github.com/o3de/o3de/files/8814661/Editor.log)

**Comment by lmbr-pip** [comment]
Believe this should be a sig/content issue as its Editor, AssetBrowser and FBX related, does not appear to be for sig/simulation.

**Comment by AMZN-stankowi** [comment]
I talked to @srikappa-amzn about this one, he'll take a look.
This line here: https://github.com/o3de/o3de/blob/development/Code/Tools/SceneAPI/SceneUI/RowWidgets/ManifestNameHandler.cpp#L29

EBUS_EVENT(AzToolsFramework::PropertyEditorGUIMessages::Bus, RequestWrite, instance);

causes the prefab system to pause all propagation and spawning of entities: https://github.com/o3de/o3de/blob/development/Code/Framework/AzToolsFramework/AzToolsFramework/Prefab/Instance/InstanceUpdateExecutor.cpp#L292

m_shouldPausePropagation = true;

This issue was introduced by https://github.com/o3de/o3de/commit/f1479668cb59b7721c36168b526290e493f42917
