### ISSUE TITLE
Feature Request - Entity Collider PhysicsAsset visualization for when shape property is set to PhysX Material

### ISSUE THREAD

**Issue by shawstar** [o3de/o3de#9868]
**Is your feature request related to a problem? Please describe.**

![image](https://user-images.githubusercontent.com/87207603/171513203-ab30b8f1-fe63-48c7-a9cd-f4028016dd3e.png)
When a asset is set-up in a DCCs tool properly, o3de will auto-detect the PhysicsAsset.
![image](https://user-images.githubusercontent.com/87207603/171512925-7258ea6a-a540-40f9-9436-b7b5c76a3e1a.png)
However it will not show the PhysX Material, or let you change to another one inside of O3DE.

**Describe the solution you'd like**
The ability to Change the Physics Material in the PhysX Collider component.

**Comment by greerdv** [comment]
@moraaar can confirm but I think this was a weird workflow problem with the old material system and his recent change should address this.

**Comment by moraaar** [comment]
@shawstar when physx collider has a PhysicsAsset by default it uses the materials that the asset was configured with in FBX Settings.

To change the materials that the asset has do these steps:
- open the physics asset in the FBX Settings (you can go directly by clicking of the most right button on PhysX Mesh property)
- FBX Settings will open, go to PhysX Group tab.
- In the Materials list properties, assign materials.
- Click update button.

After clicking update the PhysX Collider will show the same materials that the asset has.

To put your own materials in the PhysX Collider you have to disable the option "Physics materials from asset", once disabled the list of materials will not be grey out and you can change them.

I'll close this Jira since this has been tested recently. @shawstar if you still find issues after following these steps, feel free to reopen the bug or file a new one.

Thanks.
